- carmajava/launch/params/SignalParams.yaml
- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/TrafficSignalPlugin.java
This changes the logic for making the continue through light pop-up in TSP appear earlier.
> Stop popup appears earlier

- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/TrafficSignalPlugin.java
Adds the obstacle subscriber for triggering NCV updates to the traffic signal plugin
> Add obstacle sub

- docs/Acknowledgements.md
PR created from github web site in VetteDriver/CARMAPlatform page.  PR defaults to setting the base as usdot-fhwa-stol and the same branch as I'm editing.  Nice!
> Test edit #4 in Acknowledgements.md.

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/util/GuidanceRouteService.java
- carmajava/guidance_plugin_api/src/main/java/gov/dot/fhwa/saxton/carma/guidance/util/RouteService.java
- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/ObjectCollisionChecker.java
- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/ead/PlanInterpolator.java
- carmajava/signal_plugin/src/test/java/gov/dot/fhwa/saxton/carma/signal_plugin/EADAStarPlanTest.java
- carmajava/signal_plugin/src/test/java/gov/dot/fhwa/saxton/carma/signal_plugin/MockCollisionChecker.java
- carmajava/signal_plugin/src/test/java/gov/dot/fhwa/saxton/carma/signal_plugin/ObjectCollisionCheckerTest.java
- carmajava/signal_plugin/src/test/java/gov/dot/fhwa/saxton/carma/signal_plugin/PlanInterpolatorTest.java
The first commit fixes a NPE issue on starting up.
> Integration Test on NCV Fix

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/pubsub/RosSubscriber.java
- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/TrafficSignalPlugin.java
I rethink the solution. I think the issue is not on subscriber but on its callbacks. So I keep the initialization of subscribers and move the registration of their callbacks.
> Remove message listeners for TSP

- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/TrafficSignalPlugin.java
- website/main.html
- website/scripts/control.js
- website/scripts/rosbridge.js
- website/widgets/traffic_signal/widget.js
Fix the issue when stopped and TSP plugin asks for Operator if it's safe to continue. The updates to logic are:
- When operator says it's not yet safe to continue, the service call will return false with a message "When it's safe to continue, please press the YES button." Removed the wait times and unecessary variables. 
- Updated UI for the icons to be smaller to fit the tablet screen. Used White Cadillac's tablet to fit properly. 
- Updated UI popup to add message field in the footer to display the service failure message properly.
- Updated TSP widget to remove unnecessary logging.
> Fix the Traffic Signal Plugin (TSP) & widget when Stopped

- carmajava/signal_plugin/src/test/java/gov/dot/fhwa/saxton/carma/signal_plugin/EADAStarPlanTest.java
Remove the comment because the test case is unrealistic.
> Remove an unusable test case

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/CarmaVersion.java
- carmajava/package.xml
- docs/Release_notes.md
Fixes #issuenumber ; refs #issuenumber
Present tense short summary (50 characters or less)
More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.
Description can have multiple paragraphs and you can use code examples inside:
``` ruby
class PostsController
def index
respond_with Post.limit(10)
end
end
```
Changes proposed in this pull request:
* 
* 
* 
@projecthydra/sufia-code-reviewers
> Updated version ID to 2.8.1 w/description in release notes.

- README.md
- docs/PULL_REQUEST_TEMPLATE.md
Fixes #53
Two files had merge conflicts. Master holds the correct contents, so I copied those two into here rather than make an ugly conflict fix directly in master.
> Fixed two admin docs for merge conflicts w/master branch.

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/conflictdetector/ConflictManager.java
- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/trajectory/TrajectoryExecutor.java
- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/trajectory/TrajectoryExecutorWorker.java
- carmajava/guidance_plugin_api/src/main/java/gov/dot/fhwa/saxton/carma/guidance/maneuvers/LongitudinalManeuver.java
- carmajava/launch/params/roscpp_log.config
- carmajava/message/src/main/java/gov/dot/fhwa/saxton/carma/message/MessageConsumer.java
- carmajava/roadway/src/main/java/gov/dot/fhwa/saxton/carma/roadway/EnvironmentWorker.java
- carmajava/route/src/main/java/gov/dot/fhwa/saxton/carma/route/RouteWorker.java
- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/ead/EadIntersectionManager.java
- pinpoint/src/pinpoint_application.cpp
Addresses enhancement #90 
Changes many high frequency log statements to debug to reduce hard disk access and increase system performance. Additionally, changes the sensor_fusion log level to INFO after it was accidentally changed to DEBUG in develop. 
#90 
Improve system performance by reducing hard disk access and improve log readability. 
Reviewing logs while testing the traffic signal plugin
> Convert repetitive logs to debug

- .circleci/config.yml
- carmajava/build.gradle
Generate HTML test reports for all JUnit tests and export them as test artifacts
Modified circle config and gradle config to output test reports and save them to be hosted in circle.
> Test generation of HTML

- carma_base/Dockerfile
Resolves issue #169 by adding updating docker file. 
> Update carma-base docker image

- .circleci/config.yml
Updates CI to use newest docker base image
> Update docker image version for ci

- carma_base/package.xml
Quick fix for development. Adds dependencies for ros camera drivers to package xml
> Add camera dependencies to carma_base

- carmajava/platooning/src/main/java/gov/dot/fhwa/saxton/carma/plugins/platooning/PlatoonManager.java
- carmajava/platooning/src/main/java/gov/dot/fhwa/saxton/carma/plugins/platooning/PlatooningPlugin.java
- carmajava/platooning/src/test/java/gov/dot/fhwa/saxton/carma/plugins/platooning/LeaderSelectionTest.java
- carmajava/platooning/src/test/java/gov/dot/fhwa/saxton/carma/plugins/platooning/PlatoonManagerTest.java
This PR fixes removeExpiredMember test case under PlatoonManagerTest unit test.
Using Java Clock interface to remove System time dependency from platoon manager.
#184 
Time sensitive unit test should not depend on system time.
Unit test passed on both local and CI.
> Fix Platoon Manager Unit Tests

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/GuidanceCommands.java
Hotfix for topic renaming needed for demo.
> Fix topic name error in guidance commands

- .circleci/config.yml
Hot fix for a bad path in sonar cloud develop analysis
> Sonarcloud hotfix

- .sonarqube/sonar-scanner.properties
- engineering_tools/code_coverage/make_with_coverage.bash
Hotfix for sonar cloud code coverage analysis. Corrects report and script paths.
> Fix sonarcloud coverage report

- Dockerfile
Properly adds arg to capture version string metadata for baking into CARMA image.
Closes #230 
Enables better configuration management and config reporting.
Image build locally and confirmed that expected behavior is produced as described in #203
> Correctly capture version string metadata in carma docker image

- engineering_tools/code_coverage/collect_gcovr.bash
- engineering_tools/code_coverage/make_with_coverage.bash
This is a hot fix which fixes c++ code coverage analysis on sonar cloud. The changes have already been implemented by updating the docker file used for CI. This PR just merges those changes into the repo. 
Running analysis on ci using new docker image
> Hotfix for c++ code coverage on sonar cloud

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/CarmaVersion.java
- carmajava/package.xml
- docs/Release_notes.md
Release notes describe all changes for 2.8.4 and 2.9.0.
Preparing for 2.9.0 release.
N/A
- [x ] My change requires a change to the documentation.
- [x ] I have read the **CONTRIBUTING** document.
> Updated release notes for v2.9.0

- .circleci/config.yml
- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/CarmaVersion.java
- carmajava/package.xml
- configurations/cadillac_srx_2013/docker-compose-background.yml
- configurations/cadillac_srx_2013/docker-compose.yml
Added some more files with ID references.
> Updated version ID references for 2.9.0 release.

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/CarmaVersion.java
- carmajava/package.xml
Updated version ID to reflect that we are now working on v3.0.0.
None.
Configuration control.
n/a
> Updated system version ID to 3.0.0.

- carma_build
- ndt_pose_tf_wrapper/package.xml
- pure_pursuit_wrapper/CMakeLists.txt
- pure_pursuit_wrapper/package.xml
This resolves issues #252 and #253 
There was a bad comment in the tf wrapper and a missing message dependency in the pure_pursuit_wrapper
Local build using carma_build script
> Fix Issues 252 and 253

- route_generator/CMakeLists.txt
- route_generator/include/route_generator.h
- route_generator/launch/route_generator.launch
- route_generator/package.xml
- route_generator/src/main.cpp
- route_generator/src/route_generator.cpp
- route_generator/test/test_route_generator.cpp
This node provides similar API as original CARMA2 route node. It can work with CARMA2 UI and let user pick the route file (waypoint csv file) to load at run time.
This node provides four services:
get_available_routes, set_active_route, start_active_route and abort_active_route.
Those are used by UI to select a route file. Internally, the selected route full path will be published in /selected_route_path topic, which will be read in by modified Autoware waypoint_loader node.
N/A
Enable user for selecting route at run time. Unit test the function to read file names.
Local integration tested with UI interface.
> Route Generator Node

- autoware_plugin/CMakeLists.txt
- autoware_plugin/config/parameters.yaml
- autoware_plugin/include/autoware_plugin.h
- autoware_plugin/launch/autoware_plugin.launch
- autoware_plugin/package.xml
- autoware_plugin/src/autoware_plugin.cpp
- autoware_plugin/src/main.cpp
- autoware_plugin/test/test_autoware_plugin.cpp
This is the initial implementation of Autoware plugin.
This plugin takes in a list of waypoints from Autoware and convert them into a list of evenly spaced trajectory points.
N/A
Adding new feature for Beta release
All unit tests passed.
> Autoware plugin mininal version

- carmajava/interfacemgr/src/main/java/gov/dot/fhwa/saxton/carma/interfacemgr/InterfaceMgr.java
- carmajava/launch/params/InterfaceMgrParams.yaml
Make the robot_status callback in interface manager configurable
> InterfaceMgr: Make controller timeout configurable

- carmajava/launch/ui.launch
> Update namespace in UI launch file

- autoware_plugin/test/test_autoware_plugin.cpp
- pure_pursuit_wrapper/test/pure_pursuit_wrapper_test.cpp
Fix issue #292 
Update unit tests to match what expected in the actual code.
#292
All unit tests should pass on the release branch.
Run unit tests in autoware_plugin and pure_pursuit_wrapper again and all tests passes.
> Fix unit tests in release RX7 branch

- carma_build
Resolves issue #302 by adding the waypoint_planner package to the carma_build script.
> Add missing package to build script

- carma_build
fix for carma_build script regarding autoware arguments
- [x ] I have added any new packages to the sonar-scanner.properties file
- [ x] I have read the **CONTRIBUTING** document.
> fix carma_build issue

- guidance/CMakeLists.txt
- guidance/test/test_guidance_state_machine.cpp
Fix for guidance node test cases
> update test cases for guidance node

- docs/ISSUE_TEMPLATE.md
Made 2 simple changes to the template for writing new issues.
1) changed checkboxes at top to not have a space between the brackets, since some people don't delete the space, and thus the checkboxes don't look right when rendered in html.
2) Added a field to record the software version that the ticket applies to.
None.
Allows us to more easily track trouble reports vs software version for better defect management.
I can't test it.  The template will apparently only become active once it is merged into develop.  If it doesn't work after that I can make quick fixes.
No code changes.
> Updated issue template.

- carmajava/rviz/carma_default.rviz
- docs/ISSUE_TEMPLATE.md
- engineering_tools/CARMA 3 Demo.desktop
Merge the latest develop changes into release/skyline. 
NA
Skyline release
Will be tested under release/skyline.
- [x ] I have read the **CONTRIBUTING** document.
> Merge Develop to Skyline

- autoware_plugin/package.xml
- bsm_generator/package.xml
- carma_transform_server/package.xml
- carmajava/package.xml
- gnss_ndt_selector/package.xml
- gnss_to_map_convertor/package.xml
- guidance/package.xml
- guidance_command_repeater/package.xml
- health_monitor/package.xml
- j2735_convertor/package.xml
- lib_asn1c/package.xml
- pure_pursuit_wrapper/package.xml
- route_generator/package.xml
- trajectory_executor/package.xml
> Update ros package version

- autoware_plugin/package.xml
- bsm_generator/package.xml
- carma_transform_server/package.xml
- carmajava/package.xml
- gnss_ndt_selector/package.xml
- gnss_to_map_convertor/package.xml
- guidance/package.xml
- guidance_command_repeater/package.xml
- health_monitor/package.xml
- j2735_convertor/package.xml
- lib_asn1c/package.xml
- pure_pursuit_wrapper/package.xml
- route_generator/package.xml
- trajectory_executor/package.xml
Reverts usdot-fhwa-stol/CARMAPlatform#395
> Revert "Update ros package version"

- autoware_plugin/package.xml
- carma_transform_server/package.xml
- carmajava/package.xml
- gnss_to_map_convertor/package.xml
- trajectory_executor/package.xml
> update package version

- .circleci/config.yml
- docker/checkout.sh
Update versions for skyline release
> Update version for config files

- .circleci/config.yml
- docker/checkout.sh
Resent resync with master changed the branch referenced in checkout.sh this corrects it to develop as a hotfix. 
> Correct referenced branches in checkout.sh

- Dockerfile
Updates the base image version used for docker images from autoware:3.1.0 to autoware:3.2.0
> Update docker base image version to autoware 3.2.0

- .circleci/config.yml
- Dockerfile
- carmajava/mock_drivers/build.gradle
Update the version of the Autoware image.
#416 
Make CARMA works with Autoware 1.12
Tested on Fusion
> Update autoware version

- engineering_tools/opendrive_lanelet2_converter/README.md
- engineering_tools/opendrive_lanelet2_converter/opendrive2lanelet2convertor.py
opendrive to lanelet2 convertor script.
#431
autoware does not support opendrive maps therefore it is needed to convert the maps to lanelet 2 format.
tested using TFHRC opendrive map. 
- [ `x` ] New feature (non-breaking change that adds functionality)
> add opendrive2lanelet2convertor.py

- autoware_plugin/src/autoware_plugin.cpp
Fix #437 by adding plugin type
#437
Bug fix
Integration tested locally.
> Add plugin type to autoware plugin discovery message

- arbitrator/include/arbitrator.hpp
- arbitrator/src/arbitrator.cpp
Use initialized flag to fix #439 
#439
Bug fix.
Tested Locally.
> Add initialized flag in arbitrator

- autoware_plugin/src/autoware_plugin.cpp
Fix #443 
#443 
Bug fix
Tested locally
> Add planner name in maneuver

- arbitrator/config/arbitrator_params.yaml
- arbitrator/include/capabilities_interface.tpp
- arbitrator/launch/arbitrator.launch
- arbitrator/src/arbitrator.cpp
- arbitrator/src/arbitrator_node.cpp
- arbitrator/src/capabilities_interface.cpp
Fix #436 and #446 
#436 
#446
Bug fix.
Tested Locally.
> Updates on arbitrator node

- autoware_plugin/src/autoware_plugin.cpp
Fix one line which was overwritten when I resolve a merge conflict.
N/A
Fix Bug
N/A
> Fix merge conflict error

- arbitrator/package.xml
- autoware_plugin/package.xml
- bsm_generator/package.xml
- carma_transform_server/package.xml
- carmajava/message/build.gradle
- carmajava/mock_drivers/build.gradle
- carmajava/package.xml
- carmajava/rosutils/build.gradle
- carmajava/template/build.gradle
- docker/checkout.sh
- gnss_ndt_selector/package.xml
- gnss_to_map_convertor/package.xml
- guidance/package.xml
- guidance_command_repeater/package.xml
- health_monitor/package.xml
- j2735_convertor/package.xml
- lib_asn1c/package.xml
- plan_delegator/package.xml
- pure_pursuit_wrapper/package.xml
- route_generator/package.xml
- trajectory_executor/package.xml
Version update for testarossa release
> Version update for testarossa release

- trajectory_executor/include/trajectory_executor/trajectory_executor.hpp
- trajectory_executor/src/trajectory_executor/trajectory_executor.cpp
Monitoring the guidance state to fix the end of the route issue in the middle of the route.
N/A
Testarossa Release
System Test
- [X ] Defect fix (non-breaking change that fixes an issue)
- [x ] I have updated the documentation accordingly.
> guidance state added

- engineering_tools/install-docker.sh
Refer to https://github.com/usdot-fhwa-stol/CARMAPlatform/issues/473 
This script can by developers to install docker instead of manually doing it themselves. Updated to ensure that the docker group id is 999 per the issue resolution above. 
https://github.com/usdot-fhwa-stol/CARMAPlatform/issues/473 
testarossa release fixes
Locally on my image
Will update the documenation with the release testarossa. 
- [] I have updated the documentation accordingly.
> Updated this script to enforce docker ID 999 when used

- docs/Release_notes.md
Changed release_note.md to reflect highlights, updates, and fixes in the Testarossa release
none
Needed as part of Testarossa release process.
n/a
- [ x] I have updated the documentation accordingly.
> added updated release notes for Testarossa release

- docs/Release_notes.md
Fix version and mispellings directly on master branch. Approval from Sudhakar to make the direct edits and sent followup email. 
This pull request is to update develop from the changes in master. 
@aswath1 cc'd JB and John here but you can approve and merge when you're ready. 
N/A
3.2.0 release
changes reviewed by Sudhakar. 
> Updated Release_notes.md

- autoware_plugin/src/autoware_plugin.cpp
- docker/checkout.sh
- health_monitor/config/params.yaml
- health_monitor/include/entry.h
- health_monitor/include/health_monitor.h
- health_monitor/include/plugin_manager.h
- health_monitor/src/driver_manager.cpp
- health_monitor/src/entry.cpp
- health_monitor/src/health_monitor.cpp
- health_monitor/src/plugin_manager.cpp
- health_monitor/test/test_entry_manager.cpp
- health_monitor/test/test_plugin_manager.cpp
Add get plugins by capability to plugin manager. User can request a capability and plugin manager will return a list of service name which has the required capability. This PR is not complete. Please do not merge.
#478 
Add new feature.
Not tested. Still building some unit tests.
> Capability Interface Implementation

- ATTRIBUTION.md
> Fixed name misspelling.

- carma_build
Fix the paths in the carma_build script to match the new autoware.ai repo layout. 
#506 
Local testing
> Correct build script for new autoware version

- carmajava/launch/guidance.launch
- health_monitor/config/params.yaml
Move required drivers param to CARMAConfig.
#498
Enhance health monitor flexibility for handling different vehicle config.
Not been tested yet.
> Move param to public

- carmajava/launch/carma_src.launch
- carmajava/launch/environment.launch
- engineering_tools/opendrive_lanelet2_converter/opendrive2lanelet2convertor.py
add vector_map_loader to the carma platform launch file
> update vector map launch

- autoware_plugin/src/autoware_plugin.cpp
- health_monitor/config/params.yaml
Sync develop branch with Urus
N/A
Adding missing commits to Urus.
Tested on red truck.
> Adding missing commits in develop to Urus

- carmajava/launch/localization.launch
This PR adds an initial integration of the Autoware EKF with CARMA. The Autoware EKF smooths out the localization fix by fusing ndt output with reported vehicle twist. 
The EKF node is placed between the NDT node and the NDT/GPS selector. This was the fastest way to integrate this component, however it is suggested that we move the filter for after NDT/GPS after making required code changes. 
#527
NDT localization performance is greatly reduced at aberdeen and on the heavy trucks. This node will help filter the localization performance by fusing ndt output with the reported vehicle twist. 
Confirmed operation on the red truck. Though that was done on a different branch with the changes copied to this branch. 
The EKF parameters have been tested in stock autoware 1.12 running on the red …
> Add autoware EKF to carma

- .circleci/config.yml
- Dockerfile
Update carma to use new autoware.ai:3.6.0 docker image as base to provide the ekf_localizer
#333 
> Update base autoware docker version to 3.6.0

- carmajava/launch/localization.launch
This PR removes the voxel grid filter (VGF) from the localization stack in an attempt to improve localization performance. The VGF was originally added to the localization stack to help reduce NDT matching time, however it was found that this causes reduced performance in areas with fewer features such as ATEF. In addition, since the HD maps are now always down sampled the efficiency bonus from using VGF has been reduced since the total number of points as also been reduced. Additionally, the incorporation of the EKF means that the system is more robust to spikes in NDT computation time. 
For the above reasons the VGS has been removed allowing the red truck to perform better at aberdeen. 
Helps work towards fixing #333
Improve NDT performance in feature sparse environments
On the red …
> Remove the voxel grid filter from the localization stack

- README.md
- docs/Release_notes.md
Updated release notes with issue 518 and removed asterisk, also updated date in README.md
> removed asterisk from release notes and updated date on README.md

- README.md
- docs/Release_notes.md
> updated dates on release notes and readme

- docker/checkout.sh
Updated the novatel version in the checkout.sh script
> fixed novatel version

- .sonarqube/sonar-scanner.properties
- route/test/test_route_generator.cpp
- route_following_plugin/CMakeLists.txt
- route_following_plugin/config/parameters.yaml
- route_following_plugin/include/route_following_plugin.h
- route_following_plugin/launch/route_following_plugin.launch
- route_following_plugin/package.xml
- route_following_plugin/src/main.cpp
- route_following_plugin/src/route_following_plugin.cpp
- route_following_plugin/test/test_route_following_plugin.cpp
To resolve #559, this is the initial implementation of route following plugin.
#559 
Adding a new feature.
All unit tests passed.
> Route Following Plugin

- arbitrator/src/arbitrator.cpp
- guidance/include/guidance/guidance_state_machine.hpp
- guidance/include/guidance/guidance_worker.hpp
- guidance/src/guidance/guidance_state_machine.cpp
- guidance/src/guidance/guidance_worker.cpp
- plan_delegator/include/plan_delegator.hpp
- plan_delegator/src/plan_delegator.cpp
- trajectory_executor/include/trajectory_executor/trajectory_executor.hpp
- trajectory_executor/src/trajectory_executor/trajectory_executor.cpp
Make updates to guidance and nodes in CARMA planning stack to resolve #566 
#566 
Develop a new feature.
Not able to perform integration test without the completion of this integration branch.
> Update guidance and planning stack

- .circleci/config.yml
- Dockerfile
updated autoware image version to 3.7.1 in circle config and dockerfile
#521 
Needed in order to resolve sonar failures in circleci
successful sonar scan via circleci: [https://app.circleci.com/jobs/github/usdot-fhwa-stol/autoware.ai/241](url)
> updated autoware.ai image versions

- docs/Roadmap.md
Removed date, per issue #580 
See description in the issue.
Looked at that branch in Github.
> Removed date per issue #580.

- carmajava/launch/guidance.launch
- carmajava/launch/localization.launch
- carmajava/launch/message.launch
- carmajava/message/build.gradle
- carmajava/mock_drivers/build.gradle
- carmajava/rosutils/build.gradle
- carmajava/template/build.gradle
- docker/checkout.sh
This PR modifies the localization stack by removing the ray_ground_filter and adding back in the voxel grid filter. This was determined to be the best course of action to help mitigate the issues identified in #588 after discussion with TierIV. In addition, this PR supports lidar to gps failover by moving the EKF after the gnss_ndt_selector as required by #600
Because of this the PR should be merged after usdot-fhwa-stol/autoware.ai#82
This PR also updates the cav_msgs version to match the most recent component release. 
See above
> Update localization to use voxel_grid_filter instead of ray_ground

- carmajava/launch/guidance.launch
Autoware's Twist Filter parameters are added to CARMA to adjust the vehicle's steering behavior.
#617 
This feature is added to prevent the vehicle from making sudden and sharp turns.
This change needs to be integration tested.
> add steer limiter to carma

- .circleci/config.yml
- Dockerfile
Updates the autoware.ai base version to 3.8.1
Should resolve #621
> Update autoware base image version to include bug fix 3.8.1

- README.md
Temporary readme update to announce name changes
> updated README.md for name change announcement

- README.md
Removing name change notice from README now that repo name has been changed.
> removed name change notice from README

- README.md
Updated readme for support info and consistent CARMA Platform naming
#386 
The CARMAPlatform repo's readme file needs to indicate how to contact the new Carma help desk (being operated under the Support Services TO).
> updated for support info and consistent naming

- docs/License.md
- engineering_tools/carma
This PR adds a new option to the carma script called exec
This option will create a new container from carma-platform or carma-messenger then allow you to run any command with full GUI support. 
For example
```
carma exec rviz
```
This will launch rvzi with hardware acceleration support (at least in my VM)
```
carma exec
```
This will open a new bash session that already has /opt/carma/install sourced so that the user could just immediately type the desired command.
#658
Better developer support and dependency management. 
Tested in local VM. But requires carma-base with these changes https://github.com/usdot-fhwa-stol/carma-base/pull/43
> Add carma exec option to carma script

- carma-platform.repos
This PR updates the carma-platform.repos file to place the repositories into a structure known to build properly. 
call vcs-import from top level carma_ws folder to get the following.
```
carma_ws/
- autoware.ai/
- carma/
-- src/
--- carma-platform/
--- carma-msgs
--- etc.
```
In addition this PR removes repos from this file that are currently not applicable to carma3 and would likely just cause user confusion such as the SRX controller driver. 
Make user documentation easier to write. 
Locally calling vcs import < carma-platform.repos 
> Update repos file to only have carma3 repos and use relative paths.

- arbitrator/CMakeLists.txt
- arbitrator/config/arbitrator_params.yaml
- arbitrator/include/arbitrator.hpp
- arbitrator/include/cost_function.hpp
- arbitrator/include/cost_system_cost_function.hpp
- arbitrator/include/planning_strategy.hpp
- arbitrator/include/tree_planner.hpp
- arbitrator/src/arbitrator_node.cpp
- arbitrator/src/cost_system_cost_function.cpp
- arbitrator/src/fixed_priority_cost_function.cpp
- arbitrator/src/tree_planner.cpp
- arbitrator/test/test_tree_planner.cpp
Add the CostSystemCostFunction class to the Arbitrator. This implementation of CostFunction uses a service call to the Cost Plugin System to determine the appropriate costs to assign to maneuver plans. 
Closes #694
This allows Arbitrator to more accurately evaluate maneuver plans on a broader range of criteria, as defined and configured by the cost plugin system.
As the vast majority of this update is simply integrating a ROS service call mechanism, this set of code has not been unit tested. It has been verified that this update does not break existing unit tests for the Arbitrator package.
- x ] I have read the **CONTRIBUTING** document.
> Implement Cost System Cost Function

- .sonarqube/sonar-scanner.properties
Added test directory to sonar properties to resolve low test coverage
none
Needed in order for Sonar to find truck_inspection_client tests
By running Sonar through CircleCI
> updated for truck inspection client tests

- Contributing.md
Updating link to our collaborator ingress form
none
Communications has a new form to get collaborator data, so this had to be updated
> updated google form link for collaborators

- platooning_tactical_plugin/src/platooning_tactical_plugin/platooning_tactical_plugin.cpp
adding an @ to the sonar exclusion tags
#732 
Change was required in order to get sonar to ignore ros code in platooning plugin
by running sonar scanner after fixing typo in tags
> fixed sonar block tag

- platooning_strategic/CMakeLists.txt
- platooning_strategic/package.xml
Add the missing cav_srvs dependency to the platooning_strategic plugin package. 
Resolves #758 
Keep develop buildable
Local docker build using build-image script and CI
> Add missing dependancies for cav_srvs

- arbitrator/package.xml
- autoware_plugin/package.xml
- bsm_generator/package.xml
- carma_transform_server/package.xml
- carma_wm/package.xml
- carma_wm_ctrl/package.xml
- carmajava/package.xml
- cost_plugin_system/package.xml
- gnss_ndt_selector/package.xml
- gnss_to_map_convertor/package.xml
- guidance/package.xml
- guidance_command_repeater/package.xml
- health_monitor/package.xml
- lightbar_manager/package.xml
- mock_drivers/mock_lightbar_driver/package.xml
- mpc_follower_wrapper/package.xml
- object_detection_tracking/package.xml
- plan_delegator/package.xml
- platooning_strategic/package.xml
- platooning_tactical_plugin/package.xml
- pure_pursuit_wrapper/package.xml
- roadway_objects/package.xml
- route_generator/package.xml
- trajectory_executor/package.xml
- truck_inspection_client/package.xml
PR for updating package.xml files.
Changed package.xml files for every package in this repository to format 3.
This change is required to move carma to newer software.
This has been tested by successfully building carma-platform.
> Updated package.xml files PR

- carma_wm/test/TrafficControlTest.cpp
- carma_wm_ctrl/include/carma_wm_ctrl/Geofence.h
- carma_wm_ctrl/include/carma_wm_ctrl/GeofenceSchedule.h
- carma_wm_ctrl/include/carma_wm_ctrl/GeofenceScheduler.h
- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
- carma_wm_ctrl/src/GeofenceSchedule.cpp
- carma_wm_ctrl/src/GeofenceScheduler.cpp
- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/test/GeofenceScheduleTest.cpp
- carma_wm_ctrl/test/GeofenceSchedulerTest.cpp
- carma_wm_ctrl/test/WMBroadcasterTest.cpp
- carmajava/launch/message.launch
- docker/checkout.bash
With new definition of geofence spec, carma-msgs, carma-messenger's j2735_converter, cpp_message node, and carma-platform's carma_wm_ctrl needed to be updated.
https://github.com/usdot-fhwa-stol/carma-platform/issues/790 : overall new geofence definition issue
https://github.com/usdot-fhwa-stol/carma-platform/issues/780 : enable cpp_message issue
See above.
Existing unit tests and integration tests pass
> Merge implementation for new geofence spec into develop

- .sonarqube/sonar-scanner.properties
- platooning_control/CMakeLists.txt
- platooning_control/config/parameters.yaml
- platooning_control/include/pid_controller.hpp
- platooning_control/include/platoon_control.hpp
- platooning_control/include/platoon_control_worker.hpp
- platooning_control/include/pure_pursuit.hpp
- platooning_control/launch/platoon_control.launch
- platooning_control/package.xml
- platooning_control/src/main.cpp
- platooning_control/src/pid_controller.cpp
- platooning_control/src/platoon_control.cpp
- platooning_control/src/platoon_control_worker.cpp
- platooning_control/src/pure_pursuit.cpp
- platooning_control/test/mynode.test
- platooning_control/test/test_control.cpp
- platooning_control/test/test_main.cpp
- platooning_control/test/test_mynode.cpp
- platooning_control/test/test_pid.cpp
- platooning_control/test/test_pure.cpp
- platooning_control/test/test_worker.cpp
Platoon Control Plugin is added that is responsible for maintaining platoon gap and also path tracking of the platoon follower vehicles.
#750 
Adding platoon control plugin enables CARMA vehicles to perform platooning behavior 
unit test
> Add Platoon Control Plugin

- README.md
Test PR for Jira integration with git commits
> CAR-3275 #Comment test jira integration with extra line in readme

- carma_wm/include/carma_wm/TrafficControl.h
- carma_wm/src/WMListenerWorker.cpp
- carma_wm/src/WMListenerWorker.h
- carma_wm_ctrl/include/carma_wm_ctrl/Geofence.h
- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/test/WMBroadcasterTest.cpp
This PR is adds logic to update passing control line regulatory elements (not geometry changes just passability of the line) in carma_wm_ctrl and support this update in carma_wm.
https://github.com/usdot-fhwa-stol/carma-platform/issues/803
In order to block lane change, PassingControlLine geofence support is needed.
Local integration tested and unit tested.
> CAR-1804: Feature/add pcl support

- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/test/WMBroadcasterTest.cpp
The UI needs a topic to report the distance to the next active geofence along the route in meters.  This PR is to add the necessary logic to carma_wm_ctrl to achieve this. The reported distance only considers geofences that are currently active and on the vehicle's route. This logic is supposed to be used in populating the ROS topic that UI needs, an another logic which is being developed currently, which is why it is in integration/report_current_geofences branch. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/813 Handles distance to the nearest geofence logic part
See above.
Unit tests pass and integration tested by cmd location publication and dummy publishers of its internal data
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contri …
> Distance to the nearest active geofence logic

- motion_computation/include/motion_computation_worker.h
- motion_computation/src/motion_computation_worker.cpp
Removed below includes from : (https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/motion_computation/include/motion_computation_worker.h
and https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/motion_computation/src/motion_computation_worker.cpp)
#include <autoware_msgs/DetectedObject.h>
#include <autoware_msgs/DetectedObjectArray.h>
https://github.com/usdot-fhwa-stol/carma-platform/issues/821
Built in source code without issue.
~/catkin_ws/build, install, devel folders are generated
> Develop branch: extraneous include statements prevent software build

- localization_manager/src/LocalizationManager.cpp
> Correct TF frame id

- carmajava/rviz/carma_default.rviz
Update the tool properties of the default rviz file to use the correct initialpose topic
Resolves #835
Better user experience
Local vm
> Update default initialpose topic for rviz config

- carmajava/launch/utility/carma_ndt_mapping.launch
- carmajava/launch/utility/save_pcd_map.bash
- carmajava/rviz/utility/carma_ndt_mapping.rviz
This PR adds three files to support map generation using carma. One is a launch file for the Autoware ndt_mapping node with re-mappings to match carma-platform topics. The second is a bash file to trigger the save action of a running ndt_mapping node. The third is an rviz configuration to view the resulting map. 
The instructions of their usage can be found here https://usdot-carma.atlassian.net/wiki/spaces/CAR/pages/842006535/Point+Cloud+Map+Generation
Resolves #838 
Make carma more versatile and allow for testing and test tracks on short notice (no maps available). 
It hasn't as a vehicle is needed. 
> Add utility files for performing ndt mapping

- carmajava/launch/guidance.launch
This PR moves the lateral acceleration and jerk limit parameters for the twist_filter node to the carma-config, so they can be more easily controlled between vehicle types, specifically trucks and cars. 
PR https://github.com/usdot-fhwa-stol/carma-config/pull/74 also needs to be merged.
Resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/520 as this change along with the previous mod was extensively tested to show the limit is in-fact applied. 
Limit steering command based on lateral jerk/acceleration to support ACE demo and basic safety. 
On the Silver Lexus. 
> Add lateral limits of twist filter to config

- mpc_follower_wrapper/launch/mpc_follower_wrapper.launch
MPC Follower parameters are updated to allow for smoother path tracking performance.
#603 
> update mpc parameters

- carmajava/launch/environment.launch
- carmajava/launch/guidance.launch
Individual instantiation of carma_wm's topics need to be remapped in components that are using them.
Part of integration test of routing branch
https://github.com/usdot-fhwa-stol/carma-platform/issues/859 
See above
Integration tested locally to see if the topics match
> fix wmlistener topic remap

- carmajava/launch/carma_src.launch
- carmajava/launch/guidance.launch
- mpc_follower_wrapper/launch/mpc_follower_wrapper.launch
MPC parameters are updated for medium-speed driving and are moved to vehicle calibration.
#603 
> add mpc parameters to vehicle calibration

- inlanecruising_plugin/include/inlanecruising_plugin.h
- inlanecruising_plugin/include/third_party_library/spline.h
- inlanecruising_plugin/src/inlanecruising_plugin.cpp
- inlanecruising_plugin/test/test_inlanecruising_plugin.cpp
Fit a spline to each trajectory and calculate points orientation and curvature.
> calc orientation and curvature

- truck_inspection_client/src/truck_inspection_client.cpp
https://github.com/usdot-fhwa-stol/carma-platform/pull/882
Revert the shorter keys and update it with original longer keys.
https://github.com/usdot-fhwa-stol/carma-platform/issues/877
C++
> Revert the shorter keys and update it with original longer keys

- inlanecruising_plugin/config/parameters.yaml
- inlanecruising_plugin/include/inlanecruising_plugin.h
- inlanecruising_plugin/src/inlanecruising_plugin.cpp
Enable smooth speed changes in trajectory
> smooth trajectory

- health_monitor/CMakeLists.txt
- health_monitor/include/health_monitor.h
- health_monitor/src/health_monitor.cpp
- health_monitor/test/test_health_monitor.cpp
Recreation of https://github.com/usdot-fhwa-stol/carma-platform/pull/940 targeted at release/Wanderer see that PR for details. 
> Rebase health monitor changes

- truck_inspection_client/launch/truck_inspection_client.launch
This is to fix the issue with the parameter.yaml being referenced in truck inspection plugin under carma-platform. It needs to be configurable under carma-config to allow the user to update the values as needed. 
For Wanderer release. 
Per JB, there isn't currently a way to build a wanderer branch/image manually via build-image.sh. Unable to do so at this time. 
> Fix the param file location to be configurable in vehicle calibration

- trajectory_visualizer/src/trajectory_visualizer.cpp
Seems the trajectory can sometimes contain invalid times. This is itself an issue, however, an exception being through from inside the trajectory_visualizer is making it hard to track down. This PR adds guards in that node to prevent it from throwing an exception and continuing to operate even with bad data. 
> Fix exception from visualization code

- .sonarqube/sonar-scanner.properties
Removed autoware_plugin.
https://github.com/usdot-fhwa-stol/carma-platform/issues/966
CI failing.
NA
> fix sonar - remove autoware_plugin

- docker/checkout.bash
- engineering_tools/opt_carma_setup.bash
- route/test/test_route_generator.cpp
This fixes branch names from integration/routing.
Follow up on https://github.com/usdot-fhwa-stol/carma-platform/pull/947
8 months standing Integration/routing branch has been finally merged into develop.
Locally
> Fix remainders from integration routing

- Contributing.md
This PR adds some tweaks to our contributing docs to better point contributors to our ingress form, and add a note about not accepting untested code.
n/a
n/a
Document updates
> Updated for collaborator info and testing

- docker/checkout.bash
- docs/Release_notes.md
This PR is to update carma-platform for the new carma-messenger hotfix release
[#948](https://github.com/usdot-fhwa-stol/carma-platform/issues/948)
Needed in order to update the system to point to the latest carma-messenger
> carma-system-3.4.3 / carma-platform-3.4.2

- .circleci/config.yml
- truck_inspection_client/CMakeLists.txt
This PR attempts to speed up the CI build time by enabling 2 simultaneous cmake build jobs. 
As described here that limit should equal the number of cores of the host machine
http://wiki.ros.org/ROS/EnvironmentVariables#ROS_PARALLEL_JOBS
Investigation here shows that circle ci is providing us with 2 cores since we use the docker-medium instance. 
https://circleci.com/docs/2.0/configuration-reference/#resource_class
In addition, this PR also resolves a build error in truck_inspection_plugin that could appear from a missmapped dependency when built in parallel. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1041
More efficient development
CI on this PR. So far results are not showing notable improvement, but there does not appear to be a slowdown either.  …
> Evaluate impact of job count on CI

- carma/launch/environment.launch
Adds the ray_ground_filter into the environment.launch file after it seems to have been accidently removed. Also retargets the /localization/ray_ground_filter/points_no_ground topic to be /environment/ray_ground_filter/points_no_ground
Resolves #1047 
Required node for the object perception stack
Local docker build and launch testing 
> Add ray_ground_filter to environment launch file

- .sonarqube/sonar-scanner.properties
This is a temporary fix for the sonar cloud Java issue. This fix will only work till Feb15th. I have been able to update the hava version in carma-base, but am still unable to get sonar cloud to recognize it, so this is the stop gap fix till we can assign tasking for this. 
I am only applying this to carma-platform for the time being since its just a stopgap. 
#715
> Temporary solution for sonar cloud issues

- carma_wm_ctrl/test/MapToolsTest.cpp
This PR updates the split_lanes unit test in MapTestTools to use the lanelet2 routing system instead of a custom method to determine which lanelets will be split on a loop. This makes the result more robust to intersecting lanelets (though these are still ignored). 
This was needed to split the primary loop of the most recent summit point map. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1110
Support vanden-plas verification testing at summit point
Tested on most recent summit point map. 
> Refactored MapToolsTest

- yield_plugin/CMakeLists.txt
Updated Yield cmake list file to allow it to build
> add enable testing to yield

- motion_computation/launch/motion_computation.launch
There is extra space in remapping, which is preventing from starting carma on develop.
https://github.com/usdot-fhwa-stol/carma-platform/pull/1099
See above.
locally regression tested
- [X ] I have read the **CONTRIBUTING** document.
> Fix remapping of motion_computation

- route/src/route_generator_worker.cpp
This is a PR to finish leftover implementation of https://github.com/usdot-fhwa-stol/carma-platform/pull/1123
https://github.com/usdot-fhwa-stol/carma-platform/issues/1061
See above link.
not tested yet. will be tested at summit point
> route length to count route end point

- trajectory_executor/include/trajectory_executor/trajectory_executor.hpp
- trajectory_executor/src/trajectory_executor/trajectory_executor.cpp
Last minute bug fix for https://github.com/usdot-fhwa-stol/carma-platform/pull/1135
> fix build error in traj exec

- pure_pursuit_wrapper/launch/pure_pursuit_wrapper.launch
Hotfix for this PR https://github.com/usdot-fhwa-stol/carma-platform/pull/1131
> Fix launch file

- object_detection_tracking/config/parameters.yaml
Hot fix for runtime error from https://github.com/usdot-fhwa-stol/carma-platform/pull/1145
See that PR for details of change set
> fix typo in object params file

- carma-platform.repos
Updating the repos file for consistency, no code changes just changing the URL from HTTPS to SSH
Consistency so a single authentication method can be used to clone all repos using the carma-platform.repos file
Verified locally with vcstool
> Lidar Lite repo set to use ssh

- traffic_incident_parser/include/traffic_incident_parser_worker.h
- traffic_incident_parser/src/traffic_incident_parser_worker.cpp
- traffic_incident_parser/test/test_traffic_parser.cpp
Update the Traffic Incident Parser node with the Speed advisory
Traffic Incident Management : CARMA Platform - Update Speed advisory
Unit Tested
> speed_advisory

- cooperative_lanechange/config/parameters.yaml
- cooperative_lanechange/include/cooperative_lanechange.h
- cooperative_lanechange/src/cooperative_lanechange.cpp
- cooperative_lanechange/test/test_cooperative_lanechange.cpp
This pr adds lane change status to the cooperative lane change plugin for displaying progress in the UI.
> adding lane change status

- unobstructed_lanechange/CMakeLists.txt
- unobstructed_lanechange/config/parameters.yaml
- unobstructed_lanechange/include/unobstructed_lanechange.h
- unobstructed_lanechange/src/unobstructed_lanechange.cpp
- unobstructed_lanechange/test/helper.cpp
- unobstructed_lanechange/test/rostest_ulc.cpp
- unobstructed_lanechange/test/test_unobstructed_lanechange_plugin.cpp
- unobstructed_lanechange/test/ulc_plugin.test
Communication with Yield plugin is added to the un-obstructed lane change plugin, so the lane change trajectory can be modified for object avoidance purposes.
#1089 
Originally, the lane change trajectory is generated assuming there are no surrounding vehicles. With this chage, the lane change trajectory is modified to avoid and yield to objects or vehicles in its path.
unit tested and ros tested
> add communication with yield to lanechange

- object_detection_tracking/src/object_detection_tracking_worker.cpp
Modified the object_detection_tracking node to accurately relay the object id for classification
https://github.com/usdot-fhwa-stol/carma-platform/issues/1163
All detected objects on roadway_objects topic are classified as pedestrians.
This prevents some downstream components like carma_wm from correctly interpreting what such an object could do. It also impacts the motion model used to predict the motion of that vehicle.
This has been tested in the Black Chrysler Pacifica.
> Commit fix to object detection worker

- carma/launch/environment.launch
- carma/rviz/carma_default.rviz
- object_detection_tracking/src/object_detection_tracking_worker.cpp
- route_following_plugin/src/route_following_plugin.cpp
- stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
- trajectory_executor/include/trajectory_executor/trajectory_executor.hpp
- trajectory_executor/src/trajectory_executor/trajectory_executor.cpp
This PR combines the PRs below. They have been verified at summit point on this branch. 
#1180 
#1188 
#1185 
#1187
https://github.com/usdot-fhwa-stol/carma-platform/pull/1184
https://github.com/usdot-fhwa-stol/carma-platform/issues/1173
> Hotfix/candidate 3.5.3

- traffic_incident_parser/include/traffic_incident_parser_worker.h
- traffic_incident_parser/src/traffic_incident_parser_node.cpp
- traffic_incident_parser/src/traffic_incident_parser_worker.cpp
- traffic_incident_parser/test/test_traffic_parser.cpp
Traffic Incident Management : CARMA Platform - Traffic Incident Data Parser Node UI Support Publisher
https://github.com/usdot-fhwa-stol/carma-platform/issues/1037
Traffic Incident Management : CARMA Platform
> event_type

- carma/launch/guidance.launch
Guidance launch file is not correct.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1200
See above issue link
Local integration tested.
- [X ] I have updated the documentation accordingly.
> Fix guidance launch

- engineering_tools/process_traj_logs.py
- inlanecruising_plugin/CMakeLists.txt
- inlanecruising_plugin/include/inlanecruising_plugin/inlanecruising_config.h
- inlanecruising_plugin/include/inlanecruising_plugin/inlanecruising_plugin.h
- inlanecruising_plugin/include/inlanecruising_plugin/inlanecruising_plugin_node.h
- inlanecruising_plugin/package.xml
- inlanecruising_plugin/src/inlanecruising_plugin.cpp
This PR adds a debug topic to in-lanecruising to improve the data analysis experience. The debug publishing will only occur if the log level of inlane-cruising is set to DEBUG before the node is launched. The changes use the new carma_debug_msgs package found in this PR https://github.com/usdot-fhwa-stol/carma-msgs/pull/101 which must be merged first. 
See linked PR
Better ability for controls analysis
Runs at summit point
> Add debug publisher

- carma/launch/environment.launch
remap /message/incoming_mobility_operation to /incoming_mobility_operation for traffic_incident_parser node. 
N/A
Traffic Incident use case
Vehicle testing
> Traffic_incident_parser topic remapping

- docker/checkout.bash
- unobstructed_lanechange/CMakeLists.txt
Following error occurred while building develop
`---
Finished <<< platoon_strategic [2min 21s]
--- stderr: cooperative_lanechange
CMake Error at /home/carma/carma_ws/install/unobstructed_lanechange/share/unobstructed_lanechange/cmake/unobstructed_lanechangeConfig.cmake:110 (message):
Project 'unobstructed_lanechange' specifies 'include' as an include dir,
which is not found.  It does not exist in
'/home/carma/carma_ws/install/unobstructed_lanechange/include'.  Report the
problem to the maintainer 'carma <CARMA@dot.gov>' and request to fix the
problem.
Call Stack (most recent call first):
/opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
CMakeLists.txt:41 (find_package)
---`
See above
Integration tested on Fusion …
> Unobstructed lane change build error CMake

- carma_wm_ctrl/src/WMBroadcaster.cpp
- traffic_incident_parser/src/traffic_incident_parser_worker.cpp
Incident Use Map 
Incident Use Map 
> prof_populate

- carma/launch/environment.launch
traffic incident parser node georeference remap to /map_param_loader/georeference
N/A
Traffic Incident use case
> georeference remap

- yield_plugin/config/parameters.yaml
- yield_plugin/include/yield_plugin/yield_config.h
- yield_plugin/include/yield_plugin/yield_plugin.h
- yield_plugin/include/yield_plugin/yield_plugin_node.h
- yield_plugin/src/yield_plugin.cpp
- yield_plugin/test/test_cooperative_yield.cpp
- yield_plugin/test/test_yield.cpp
- yield_plugin/test/test_yield_plugin.cpp
Add lane change status publisher to Yield plugin constructor to ensure the topic is published properly.
to publish cooperative lane change status for UI
> update lanechange status publisher

- route_following_plugin/config/parameters.yaml
- route_following_plugin/include/route_following_plugin.h
- route_following_plugin/src/route_following_plugin.cpp
This pr adds a ros parameter for choosing the tactical plugin to be used for lane changing.
> adding lane change  tactical plugin as param

- inlanecruising_plugin/include/inlanecruising_plugin/inlanecruising_plugin_node.h
Add the enable_object_avoidance flag
> add config param to node

- plan_delegator/src/plan_delegator.cpp
A 'TODO' block that was included in plan_delegator()'s planTrajectory() function for the Vanden-Plas release was initially removed as a part of PR #1220 (the TODO block was rendered unnecessary after lines 193-198 were added). PR #1230 re-introduced this block of code, and the block is being removed again by this PR. 
While this was already integration tested for PR #1220, integration testing was conducted again against the Zephyr release branches on the Blue Lexus.
> Remove 'todo' block from plan_delegator

- motion_computation/src/motion_computation_worker.cpp
- yield_plugin/config/parameters.yaml
- yield_plugin/include/yield_plugin/yield_plugin_node.h
- yield_plugin/src/yield_plugin.cpp
@saina-ramyar @itabrl @adev4a Please verify change set for yield fixes
> changes to yield

- carma_wm_ctrl/src/WMBroadcasterNode.cpp
Somehow this change was lot in the previous PR. Now added back
> Add missing file

- carma/launch/environment.launch
- carma_wm_ctrl/launch/carma_wm_broadcaster.launch
- traffic_incident_parser/launch/traffic_incident_parser.launch
> Commit remappings

- inlanecruising_plugin/config/parameters.yaml
Disabled Object Avoidance
it is required for inlanecruising on lanechanging cars (not the one yielding).
Fusion
> Disable object avoidance

- carma_wm_ctrl/test/WMBroadcasterTest.cpp
This PR adds a unit test to carma_wm_ctrl in order to test the updated checkActiveGeofenceLogic() function, which was updated as part of PR #1275.
Unit test passes.
> Add unit tests for WMBroadcaster checkActiveGeofenceLogic() updates made in PR #1275

- route/src/route_generator_worker.cpp
Route markers now overlap on top of the lanelet's blue lines on rviz.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1288
See above
locally tested
> fix route viz

- carma/rviz/carma_default.rviz
- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcasterNode.h
- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/src/WMBroadcasterNode.cpp
Create marker topic to visualize above nodes in TCM in Rviz similar to how we visualize our route
https://github.com/usdot-fhwa-stol/carma-platform/issues/1295
> tcm_visualizer

- carma/launch/guidance.launch
- port_drayage_plugin/CMakeLists.txt
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_plugin.h
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_worker.h
- port_drayage_plugin/src/port_drayage_plugin.cpp
- port_drayage_plugin/src/port_drayage_worker.cpp
- port_drayage_plugin/test/test_port_drayage_plugin.cpp
This PR includes all of the original updates from #1252, which were removed from the develop branch after a revert commit on June 11th, 2021. 
Verified that package builds and that all unit tests still pass.
> Re-add updates from PR #1252 to Port Drayage package

- motion_computation/config/parameters.yaml
> fix mobility path param

- .circleci/config.yml
- Dockerfile
- docker/build-image.sh
- docker/checkout.bash
- docker/install.sh
- hooks/pre_build
This PR updates the docker image tags to properly reference noetic/develop when building with the -d argument. 
Local docker build testing
> Updated noetic/develop tags

- platooning_control/src/platoon_control_worker.cpp
Smooth speed change when the control plugin first changes to platooning control.
> smooth platoon speed change

- docker/checkout.bash
Updating release branch to use develop branch as baseline for checkout (to be updated to yenko candidates using pre_build hooks)
N/a
N/a
N/a
> Revert carma-msgs to develop branch status

- guidance_command_repeater/launch/guidance_command_repeater.launch
- mpc_follower_wrapper/launch/mpc_follower_wrapper.launch
- platooning_tactical_plugin/launch/platooning_tactical_plugin.launch
- pure_pursuit_wrapper/launch/pure_pursuit_wrapper.launch
- route/launch/route.launch
- trajectory_visualizer/launch/trajectory_visualizer.launch
This PR fixes an issue with the launch files associated with several plugins from PR #1019. For some files, the copyright comment block was added above the `<?xml version="1.0"?>` line. This 'xml version' line is required to be at the top of the launch file, otherwise an error will occur at startup and carma-platform will shutdown.
Built and launched without errors on the Black Pacifica.
> Move 'xml version' to the top of the launch file for several plugins

- .sonarqube/sonar-scanner.properties
removed pure_pursuit_jerk_wrapper from sonar.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1383
See above.
NA
> removed jerk_wrapper from sonar

- carma/launch/environment.launch
- carma/launch/guidance.launch
- carma_wm/src/CARMAWorldModel.cpp
- carma_wm/src/WMListenerWorker.cpp
- carma_wm_ctrl/src/WMBroadcaster.cpp
https://github.com/usdot-fhwa-stol/carma-platform/issues/1388
See the issue.
Integration tested on Ford Fusion at TFHRC
> Integration test workzone communication

- bsm_generator/include/bsm_generator.h
- bsm_generator/src/bsm_generator.cpp
The /hardware_interface/velocity_accel_cov topic has been planned to replace the /hardware_interface/velocity_accel topic in the bsm_generator node. Because of this, all references to the previous message type have been switched out in favor of the VelocityAccelCov message.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1207
The bsm_generator is subscribed to the /hardware_interface/velocity_accel topic which was removed in later versions of the SSC and replaced with /hardware_interface/velocity_accel_cov, so the BSMs broadcast by carma will not contain velocity or acceleration data.
At the moment this has minimal impact on the development team since BSMs are not needed for most of our use cases, but could impact other users. …
> Commit changes to bsm_generator

- sci_strategic_plugin/include/sci_strategic_plugin.h
- sci_strategic_plugin/include/sci_strategic_plugin_config.h
- sci_strategic_plugin/src/main.cpp
- sci_strategic_plugin/src/sci_strategic_plugin.cpp
Broadcast Vehicle Status And Intent (Class C and Class D)
As CARMA Platform on a vehicle entering an unsignalized intersection, vehicle broadcast status as an Entering Vehicle so that other vehicles can estimate and plan their stopping trajectories.
> Add broadcast

- inlanecruising_plugin/CMakeLists.txt
PR #1460 removed basic_autonomy as a dependency from inlanecruising_plugin; however, inlanecruising_plugin still includes some calls to methods within the basic_autonomy package. As a result, a build error would occur while attempting to build CARMA. This PR adds basic_autonomy as a dependency within inlanecruising_plugin's CMakeLists file.
Built inlanecruising_plugin package successfully.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [] All new and existing tests passed.
> Add basic_autonomy to inlanecruising_plugin's CMakeLists

- carma_wm/include/carma_wm/CARMAWorldModel.h
- carma_wm/include/carma_wm/TrafficControl.h
- carma_wm/include/carma_wm/WMTestLibForGuidance.h
- carma_wm/include/carma_wm/WorldModel.h
- carma_wm/src/CARMAWorldModel.cpp
- carma_wm/src/WMListenerWorker.cpp
- carma_wm/test/CARMAWorldModelTest.cpp
- carma_wm_ctrl/src/WMBroadcaster.cpp
- wz_strategic_plugin/include/wz_strategic_plugin/wz_strategic_plugin.h
- wz_strategic_plugin/src/wz_strategic_plugin.cpp
- wz_strategic_plugin/test/test_strategic_plugin_helpers.cpp
Upon client's request, the CarmaTrafficLight naming should be changed to CarmaTrafficSignal for better terminology.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1529
See above.
Smoke tested on lanelet2_extension, and carma_wm packages
- [X I have updated the documentation accordingly.
> Rename TrafficLight to TrafficSignal

- .circleci/config.yml
- .sonarqube/sonar-scanner.properties
- light_controlled_intersection_tactical_plugin/include/light_controlled_intersection_plugin.h
- light_controlled_intersection_tactical_plugin/include/light_controlled_intersection_plugin_node.h
- light_controlled_intersection_tactical_plugin/package.xml
- light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin.cpp
- light_controlled_intersection_tactical_plugin/test/test_lci_tactical_plugin.cpp
As CARMA Platform operating on vehicle approaching a fixed-time traffic signal, I want to follow Trajectory Case 2 specified in CRMTFC-257: Trajectory Plan: Case Determination (UC#2 - All Classes)DONE to plan a trajectory such that the ego vehicle does not have to stop prior to the light turning green so that traffic flow behind the vehicle does not suffer a shockwave.    
This case will assume that the target departure time is soon enough (but not sooner than what is required for CASE 1) based on the vehicle’s present location and speed, so that the vehicle should first accelerate and then decelerate to leave the intersection at the target speed. In this case, the trajectory profile include two sections: acceleration and deceleration (with respect to the order).
please refer to the …
> case_1_2_unit

- basic_autonomy/src/basic_autonomy.cpp
- carma-platform.repos
- carma/launch/guidance.launch
- docker/build-image.sh
- docker/checkout.bash
- docs/Release_notes.md
- engineering_tools/opt_carma_setup.bash
- hooks/pre_build
- localization_manager/config/parameters.yaml
- localization_manager/include/localization_manager/LocalizationManagerConfig.h
- localization_manager/include/localization_manager/LocalizationTypes.h
- localization_manager/src/LocalizationManager.cpp
- localization_manager/src/LocalizationTransitionTable.cpp
- localization_manager/src/LocalizationTypes.cpp
- localization_manager/src/localizer_node.cpp
- localization_manager/test/TestLocalizationManager.cpp
- port_drayage_plugin/config/params.yml
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_plugin.h
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_state_machine.h
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_worker.h
- port_drayage_plugin/src/port_drayage_plugin.cpp
- port_drayage_plugin/src/port_drayage_state_machine.cpp
- port_drayage_plugin/src/port_drayage_worker.cpp
- port_drayage_plugin/test/test_port_drayage_plugin.cpp
- route/src/route_generator_worker.cpp
- sci_strategic_plugin/src/sci_strategic_plugin.cpp
This PR syncs the Elise release with the changes from 3.9.0
Supports elise milestone https://github.com/usdot-fhwa-stol/carma-platform/milestone/5
Testing will occur on release branch after merge
> Sync elise with master

- carma_wm/CMakeLists.txt
- carma_wm/include/carma_wm/CARMAWorldModel.h
- carma_wm/include/carma_wm/SignalizedIntersectionManager.h
- carma_wm/include/carma_wm/TrafficControl.h
- carma_wm/include/carma_wm/WMTestLibForGuidance.h
- carma_wm/include/carma_wm/WorldModelUtils.h
- carma_wm/src/SignalizedIntersectionManager.cpp
- carma_wm/src/WMListenerWorker.cpp
- carma_wm/src/WMListenerWorker.h
- carma_wm/src/WorldModelUtils.cpp
- carma_wm/test/CARMAWorldModelTest.cpp
- carma_wm/test/SignalizedIntersectionManagerTest.cpp
- carma_wm_ctrl/include/carma_wm_ctrl/Geofence.h
- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/test/WMBroadcasterTest.cpp
- wz_strategic_plugin/src/wz_strategic_plugin.cpp
This PR implements the signalized intersection manager in carma_wm package to be used by wm instances and carma_wm_ctrl.
- Generally, functions of the manager gets the map as the input and can extract necessary information to create traffic control signals and signalized intersections. However, the map is only edited in carma_wm_ctrl. WMBroadcaster then proceeds to send this map_update over the same logic used for sending geofence with instant trigger schedule.
- When the map update is being sent, each new intersection and traffic_signal regulatory elements are sent over individual map_update just how other updates used to be sent in other use cases.
- Previous workzone related id and state management has been left unchanged until next PR when handling rest of World Model interface and …
> Signalized Intersection Manager

- bsm_generator/include/bsm_generator.h
- bsm_generator/launch/bsm_generator.launch
- bsm_generator/src/bsm_generator.cpp
- sci_strategic_plugin/config/parameters.yaml
- sci_strategic_plugin/src/sci_strategic_plugin.cpp
- stop_and_wait_plugin/config/parameters.yaml
- stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
This pr fixes issues seen with stopping while testing tsmo use case 1. 
Updates were made to parameters and logic was added to stop_and_wait plugin to prevent acceleration when the vehicle was trying to slow down.
> Fix stopping issue - Noetic

- README.md
This PR updates the README to include links to the driver contributions from the Virginia Tech - Autonomous Systems and Intelligent Machines lab. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1574
Encourage external collaboration by making it easier to find 3rd party drivers. 
N/A
> Update README to include external drivers added in #1574

- object_detection_tracking/src/object_detection_tracking_node.cpp
- subsystem_controllers/include/subsystem_controllers/base_subsystem_controller/base_subsystem_controller_config.hpp
- subsystem_controllers/src/base_subsystem_controller/base_subsystem_controller.cpp
- template_package/src/template_package_node.cpp
This PR updates the template package and existing ros2 packages to properly declare their parameters prior to loading. The method we had been using where we only declared them meant that configure() could only be called once per node as calling declare parameter twice on the same parameter results in an exception. This breaks the lifecycle state machine. Declaring the parameters in the constructor then loading them on on_configure results in the correct behavior. 
Supports https://github.com/usdot-fhwa-stol/carma-platform/issues/1557
carma nodes are meant to be lifecycle compatible per the ROS2 architecture
Local build/run testing
> Fix parameter loading in template_package and object_detection_tracking

- carma/launch/environment.launch.py
- object_detection_tracking/CMakeLists.txt
This PR adds a transformer node into the lidar pointcloud pipeline to make the output data conform to the required frame for the ray_ground_filter node. In addition, it resolves some incorrect topic mappings in other nodes and an installation error in the object_detection_tracking worker class library. 
Supports https://github.com/usdot-fhwa-stol/carma-platform/issues/1557
Functional object detection and tracking in ROS2
Local integration testing of topic connections 
> Topic connection fixes

- sci_strategic_plugin/src/sci_strategic_plugin.cpp
- stop_and_wait_plugin/config/parameters.yaml
- stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
This pr fixes issues seen with stopping while testing tsmo use case 1.
Updates were made to parameters and logic was added to stop_and_wait plugin to prevent acceleration when the vehicle was trying to slow down.
> fix stopping issue

- arbitrator/config/arbitrator_params.yaml
- sci_strategic_plugin/config/parameters.yaml
- sci_strategic_plugin/src/sci_strategic_plugin.cpp
- stop_and_wait_plugin/config/parameters.yaml
- stop_controlled_intersection_tactical_plugin/config/parameters.yaml
During verification of Fiesta release, it was noticed that the deceleration of the vehicle to stop at the intersection is very jerky. The parameters of involved plugins are tuned to minimize jerkiness and also ensure the vehicle stops.
The changes are tested on Blue Lexus and Ford Fusion.
> Improve Stopping behavior for Fiesta release

- light_controlled_intersection_tactical_plugin/CMakeLists.txt
- mobilitypath_publisher/src/mobilitypath_publisher.cpp
- ns-3_adapter/package.xml
Build fixes following https://github.com/usdot-fhwa-stol/carma-platform/pull/1610
Supports https://github.com/usdot-fhwa-stol/carma-platform/issues/1609
Mainline ROS2 code
Local build testing
> Fix build errors

- platooning_strategic_IHP/CMakeLists.txt
- platooning_strategic_IHP/config/parameters.yaml
- platooning_strategic_IHP/include/platoon_config_ihp.h
- platooning_strategic_IHP/include/platoon_manager_ihp.h
- platooning_strategic_IHP/include/platoon_strategic_ihp.h
- platooning_strategic_IHP/include/platoon_strategic_plugin_node_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
- platooning_strategic_IHP/test/test_platoon_manager.cpp
- platooning_strategic_IHP/test/test_platoon_manager_front_join.cpp
This is UCLA team's commit of the IHP2 platoon plugin which includes the function of cut-in front join.
There is no related issues.
This is the development for IHP2 project.
It adds necessary functions to cut-in join from front.
- Add unit test to test additional state transitions.
- Compile and ran on UCLA's vehicle platform (single vehicle only).
> The new commit to feature cut-in-front. Code difference is updated.

- platooning_strategic_IHP/include/platoon_config_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Two variables were still being used in platoon_strategic_IHP code that no longer exist.  Made changes to accommodate their removal.
PR #1626 
IHP code would not build.
Not yet tested.
> Fixed some overlooked variables that were to be changed during merge.

- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/test/WMBroadcasterTest.cpp
This PR includes an update to WMBroadcaster to process a received TCM with a restricted lane, and to add a RegionAccessRule to the affected lanelets in order to restrict the vehicle classes identified in the TCM from using those lanelets for routing.
Unit tested and integration tested on Silver Lexus at TFHRC using a manually-published TCM with the restricted lane type.
> Update WMBroadcaster to process received TCM with a restricted lane

- .circleci/config.yml
This PR is to update the resource class to xlarge and ros parallel Jobs to -j4
> update resource class and ross parallel jobs to 4

- platooning_strategic/include/platoon_strategic.h
- platooning_strategic/src/platoon_strategic.cpp
- platooning_strategic/test/test_platoon_manager.cpp
In this PR, the platooning strategic plugin plans a left lane change to move to the adjacent left lane to be able to join the platoon.
https://github.com/usdot-fhwa-stol/carma-platform/pull/1594
An initial platoon cannot be formed in the rightmost lane when there are multiple lanes of the current travel direction. This change enables the platooning plugin to plan a lane change maneuver after the communication of a target lane index between two vehicles forming a platoon occurred.
Unit tested.
> add left lanechange to platoon

- carma_wm/src/WMListener.cpp
- carma_wm/src/WMListenerWorker.cpp
- carma_wm/test/WMListenerWorkerTest.cpp
- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
- carma_wm_ctrl/src/WMBroadcaster.cpp
Corresponding changes for https://github.com/usdot-fhwa-stol/autoware.ai/pull/211 in carma-platform.
> replace header.seq with seq_id for autoware_lanelet2_msgs

- cooperative_lanechange/include/cooperative_lanechange.h
- cooperative_lanechange/src/cooperative_lanechange.cpp
This PR includes updates to cooperative_lanechange that result in the vehicle maintaining its lane change entrance speed throughout the full duration of the lane change. At the first occurrence of the vehicle's downtrack being equal to or beyond the starting downtrack of the lane change, the current vehicle speed is stored, and this vehicle speed becomes the target speed for the duration of the lane change. 
This PR also cleans up some comments from PR #1685 
Fixes issue with speed decreasing during lane changes in Issue #1340 
Tested on multiple runs with left and right lane changes on the Silver Truck at Suntrax.
> Update CLC to maintain initial lane change speed throughout lane change

- carma_wm/src/WMListener.cpp
- carma_wm/src/WMListenerWorker.cpp
- carma_wm/test/WMListenerWorkerTest.cpp
- platooning_strategic_IHP/CMakeLists.txt
- platooning_strategic_IHP/package.xml
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Update Platooning Strategic IHP Plugin to be compatible with recent develop changes in caram platform and msgs.
> ihp develop merge strategic ihp plugin

- carma/launch/hardware_interface.launch
This PR adds a topic relay to create a subscription and topic name change the ssc velocity data. The subscription is needed to get the data to bridge and the name change is also needed to account for the namespace change in the ros2 ssc. 
Resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1698
All necessary data is available for data analysis in this release
Successfully tested in silver lexus which has the same behavior of the referenced issue as blue lexus
> Get accel data into rosbag

- platooning_strategic/include/platoon_config.h
- platooning_strategic/include/platoon_manager.h
- platooning_strategic/src/platoon_manager.cpp
- platooning_strategic/src/platoon_strategic.cpp
- platooning_strategic/test/test_platoon_manager.cpp
The gap calculation in Platooning Strategic Plugin is updated to be able to handle platoons with more than two vehicles.
#1433 
Unit test
> Gap calculation for multi-vehicle platoon

- .sonarqube/sonar-scanner.properties
- carma/launch/guidance.launch
- platooning_control_ihp/CMakeLists.txt
- platooning_control_ihp/config/parameters.yaml
- platooning_control_ihp/include/pid_controller.h
- platooning_control_ihp/include/platoon_control_ihp.h
- platooning_control_ihp/include/platoon_control_ihp_config.h
- platooning_control_ihp/include/platoon_control_ihp_worker.h
- platooning_control_ihp/include/pure_pursuit.h
- platooning_control_ihp/launch/platoon_control_ihp.launch
- platooning_control_ihp/package.xml
- platooning_control_ihp/src/main.cpp
- platooning_control_ihp/src/pid_controller.cpp
- platooning_control_ihp/src/platoon_control_ihp.cpp
- platooning_control_ihp/src/platoon_control_ihp_worker.cpp
- platooning_control_ihp/src/pure_pursuit.cpp
- platooning_control_ihp/test/mynode.test
- platooning_control_ihp/test/test_control.cpp
- platooning_control_ihp/test/test_main.cpp
- platooning_control_ihp/test/test_mynode.cpp
- platooning_control_ihp/test/test_pid.cpp
- platooning_control_ihp/test/test_pure.cpp
- platooning_control_ihp/test/test_worker.cpp
- platooning_strategic_IHP/config/parameters.yaml
- platooning_strategic_IHP/include/platoon_config_ihp.h
- platooning_strategic_IHP/include/platoon_manager_ihp.h
- platooning_strategic_IHP/include/platoon_strategic_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
> resolve merge conflicts platoon_id and cutin join

- platooning_control_ihp/src/platoon_control_ihp.cpp
- platooning_strategic_IHP/config/parameters.yaml
- platooning_strategic_IHP/include/platoon_manager_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
In this PR, platoon identification logic, as well as some logging are added to enable front and rear joins.
Integration tested at TFHRC
> rear and front join tweaks

- carma/launch/localization.launch
This pr removes gnss to map convertor from localization.launch since that package was moved to ros2 and is being launch from localization.launch.py
> fix ros1 localization launch

- route/CMakeLists.txt
- route/include/route_generator_worker.h
- route/package.xml
Updates the dependency list for route package to point to wgs84_utils_ros1, which is the ros1 version of the package.
> update wgs84_utils dep to ros1

- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
There were several compiler warnings in platooning ihp strategic and tactical plugins that have been fixed.  Also lots of logging statements have been accumulating that are no longer needed.  I have removed some of them to reduce clutter and make log reading a little easier.
None
Reduce clutter in build output and runtime logs to make debugging easier.
Build packages locally.
> Fixed compiler warnings & removed some unneeded logging

- Dockerfile
- docker/build-image.sh
- docker/checkout.bash
- docker/install.sh
- plan_delegator/src/plan_delegator.cpp
- platooning_control/config/parameters.yaml
- platooning_control/include/platoon_control_config.h
- platooning_control/src/platoon_control.cpp
- platooning_control/src/pure_pursuit.cpp
- platooning_strategic_IHP/config/parameters.yaml
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
> Updates to IHP develop merge branch

- platooning_strategic_IHP/include/platoon_manager_ihp.h
- platooning_strategic_IHP/include/platoon_strategic_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Fixed a) incorrect cleanup of platoon data when a request is NACKed; b) added delay in mob_req_cb_leaderwaiting() to prevent race condition that double-counts a new member.
a) if a candidate joiner is rejected then it sometimes was still being counted as a member, which screws up member indexing
b) without the new delay before starting to send status messages from a candidate joiner, the joiner could be double-counted in the leader's platoon record.
Ready for integration testing.
> Fixes for platoon member counting & indexing

- platooning_strategic_IHP/include/platoon_strategic_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
The logic for generating the lane change maneuver is modified based on the platoon start and end positions.
Temporarily some safety checks disables
> modify the logic for calling lanechange

- platooning_strategic_IHP/config/parameters.yaml
- platooning_strategic_IHP/include/platoon_config_ihp.h
- platooning_strategic_IHP/include/platoon_manager_ihp.h
- platooning_strategic_IHP/include/platoon_strategic_plugin_node_ihp.h
- platooning_strategic_IHP/src/main_ihp.cpp
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Primarily fixes to logic running on the leader when deciding whether to accept a cutin join request.
First cutin test on 5/26/22 (rear cutin) logs showed lots of communication problems.
> Several changes to fix logic for front & rear cut-in joins

- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Communications for cut-in merge are simplified and updated.
> cut-in merge communications updates

- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
This is a small piece of changes that may be needed to fix join decision problems or to help debug them.
> Added some log stmts and a couple changes for initiating a cut-in join.

- .circleci/config.yml
- Dockerfile
- docker/checkout.bash
Updates version numbers to 4.1.0 for caram-system 4.1.0 release.
> Update version numbers for carma-system-4.1.0 release

- platooning_strategic_IHP/include/platoon_manager_ihp.h
- platooning_strategic_IHP/include/platoon_strategic_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Several small fixes & clean-ups based on walk-through of logic flow & message exchanges.  Note that this does not attempt to fix known problems with the joining vehicle needing to know the structure of the target platoon, which it currently does not.
IHP2 integration testing problems with cut-in join.
None. Requires integration testing soon.
> Several fixes for rear cut-in join

- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Adding logs and removing unused code.
> ihp cutin lanechange logs

- docker/install.sh
- platooning_control_ihp/CMakeLists.txt
- platooning_control_ihp/package.xml
IHP Control plugin cmake file is updated to be compatible with carma platform's docker build process.
Package build is tested locally.
> Fix ihp control build

- .circleci/config.yml
- Dockerfile
- platooning_strategic/src/platoon_strategic.cpp
This PR applies a fix within the platooning strategic plugin, which enables a host vehicle to set its Platoon Manager's current_plan.peerId to the potential leader vehicle's Vehicle ID. Prior to this fix, the current_plan.peerId was incorrectly set to the host vehicle's Vehicle ID.
Resolves Issue #1804 
See Issue #1804 
> Update platooning strategic plugin to set platoon manager's peerId to the target leader's Vehicle ID

- carma/launch/environment.launch.py
- carma_wm_ros2/src/CARMAWorldModel.cpp
- motion_computation/src/motion_computation_node.cpp
- roadway_objects/include/roadway_objects/roadway_objects_node.hpp
- roadway_objects/src/roadway_objects_node.cpp
- traffic_incident_parser/include/traffic_incident_parser/traffic_incident_parser_node.hpp
- traffic_incident_parser/src/traffic_incident_parser_node.cpp
This PR resolves the two linked issues. It resolves a crashing issue in roadway_objects and traffic_incident_parser to a missing required parameter which caused a silent seg fault (now elevated to exception) and parameter provided. Additionally, the dynamic parameter setting in motion_computation was not working because the worker was set set. This has now been resolved. 
Finally the usage of this in the constructor or roadway_objects and traffic_incident_parser was refactored into configure() function to avoid unsafe this calls in constructor. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1846
https://github.com/usdot-fhwa-stol/carma-platform/issues/1847
Working object detection in release cabin.
Tested in black pacifica at suntrax …
> resolve issue with object detection

- carma/launch/environment.launch.py
- carma_wm_ros2/src/CARMAWorldModel.cpp
- motion_computation/src/motion_computation_node.cpp
- platooning_control/config/parameters.yaml
- platooning_control/include/platoon_control_config.h
- platooning_control/include/pure_pursuit.h
- platooning_control/src/platoon_control.cpp
- platooning_control/src/pure_pursuit.cpp
- platooning_strategic_IHP/config/parameters.yaml
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
- roadway_objects/include/roadway_objects/roadway_objects_node.hpp
- roadway_objects/src/roadway_objects_node.cpp
- traffic_incident_parser/include/traffic_incident_parser/traffic_incident_parser_node.hpp
- traffic_incident_parser/src/traffic_incident_parser_node.cpp
Sync release/cabin with develop to get some much needed fixes into the mainline.
Non-platooning fixes are from this PR
https://github.com/usdot-fhwa-stol/carma-platform/pull/1848
Stable develop branch
> Sync release/cabin

- basic_autonomy/src/basic_autonomy.cpp
- plan_delegator/src/plan_delegator.cpp
- platooning_strategic_IHP/config/parameters.yaml
- platooning_strategic_IHP/include/platoon_strategic_ihp.h
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Platooning plugin is updated to generate maneuvers for an adjacent lane join, based on the type of lanelets involved.
If the starting and end lanelets have a boundary with a left/right relation, a lane change maneuver is composed.
If the starting and end lanelets form a merge lane where lanelets overlap and there is no clear boundary, a lane follow maneuver is composed.
Moreover, basic autonomy is updated to use the lanelet ids included in the maneuver msg for trajectory generation, rather than generating a list based on shortest path.
#1862 
Vehicle should be able to complete driving on the merge lane and join the platoon on the adjacent lane
During verification of release/cabin
> Fixes for platoon lane change in parallel and merge lanes

- .circleci/config.yml
- Dockerfile
- docker/checkout.bash
This PR is to update release/branch with new version
> udpated docker fiels with new version

- carma/CMakeLists.txt
- carma/launch/ui.launch.py
This PR fixes two errors in the 'carma' package were restricting ui.launch.py from running successfully:
- A couple non-closed brackets were fixed within ui.launch.py 
- The CMakeLists.txt was fixed to enable /ui/config/CommandAPIParams.yaml to be built into the 'carma' ROS2 package.
Issue #1891
The ui.launch.py script must run properly to enable usage of the CARMA Web UI with the CARMA System.
Package built and ui.launch.py script was run successfully
> Fixes to enable ui.launch.py to run successfully

- carma/launch/plugins.launch.py
This is a fix for the remapping in strategic_plugin ROS2 port happened here https://github.com/usdot-fhwa-stol/carma-platform/pull/1907
https://github.com/usdot-fhwa-stol/carma-platform/issues/1906
see above
local integration tested
> remapping fix for sci_strategic_plugin

- carma/launch/guidance.launch.py
- trajectory_visualizer/src/trajectory_visualizer.cpp
Fixed an issue where trajectory visualizer was crashing soon after carma was engaged.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1909
See above.
Tested on Black Pacifica
> Fix trajectory visualizer

- docker/checkout.bash
- light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin.cpp
platform_ros2 | [carma_component_container_mt-17] 1670528425.558134162 | ERROR | on_error:120 | Uncaught Exception from node: light_controlled_intersection_tactical_plugin exception: cannot store a negative time point in rclcpp::Time while in ACTIVE state.
platform_ros2 | [carma_component_container_mt-17] 1670528425.559358903 | ERROR | on_error:134 | Sent on_error system alert
https://github.com/usdot-fhwa-stol/carma-platform/issues/1986
UC3 
Integration Tested.
> negative_time_fix

- carma/launch/message.launch.py
- carma_cloud_client/launch/carma_cloud_client_launch.py
The path for carma cloud key file was set incorrectly, causing carma platform to crash because the file could not be found. This path is fixed.
> update path for cloud key file

- light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin.cpp
- light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin_node.cpp
During UC3 integration testing, it was found that the lci tactical plugin's logging was not working as the logger logic is incorrect. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1957
UC3 integration testing
locally tested
> Fix LCI tactical plugin log

- platooning_control/README.md
- platooning_control_ihp/README.md
- platooning_strategic_IHP/README.md
- platooning_tactical_plugin/README.md
The platooning plugins readme files are updated to include a new link for the use case overview
> update platooning plugins readme link for overview

- lci_strategic_plugin/src/lci_strategic_plugin.cpp
Add execution timer for lci strategic plugin
> add execution timer for lci

- docs/Release_notes.md
Updated release notes with latest release verions 4.3.0
> Finalize release notes for 4.3.0

- carma/launch/guidance.launch.py
This PR includes a couple fixes to guidance.launch.py for launching the twist_gate node. Specifically, it fixes the remapping of the node's "vehicle_cmd" topic, and removes a remapping of the "/ctrl_cmd" topic, since the node is already properly launched with the intended "ctrl_cmd" topic. 
[Issue #2067](https://github.com/usdot-fhwa-stol/carma-platform/issues/2067)
This fix is required to enable the twist_gate node to publish to the /hardware_interface/vehicle_cmd topic, which is a critical step in the process of sending commands to the vehicle's low level controller.
Tested on the Silver Truck at Suntrax.
> Fix topic remappings for twist_gate

- basic_autonomy/src/basic_autonomy.cpp
- basic_autonomy_ros2/src/basic_autonomy.cpp
This PR includes a small update to basic_autonomy_ros2 to improve the speed of lane change trajectory generation. 
Originally there was a sequence of steps in `create_lanechange_geometry()` in which (1) two separate vectors of lane centerline points were each fit to separate spline curves, and then (2) the spline curves were constrained to the starting and ending downtracks of the provided lane change maneuver. Since the spline fit computation takes longer when provided with more lane centerline points, this sequence of steps was optimized by reversing the order: now (1) the two separate vectors of lane centerline points are constrained to the starting and ending downtracks of the provided lane change maneuver, and then (2) the constrained vectors of lane centerline points are each fit to …
> Update to basic_autonomy_ros2 to improve the speed of lane change trajectory generation

- stop_and_dwell_strategic_plugin/CMakeLists.txt
- stop_and_dwell_strategic_plugin/config/parameters.yaml
- stop_and_dwell_strategic_plugin/include/stop_and_dwell_strategic_plugin.hpp
- stop_and_dwell_strategic_plugin/include/stop_and_dwell_strategic_plugin_config.hpp
- stop_and_dwell_strategic_plugin/launch/sci_strategic_plugin.launch.py
- stop_and_dwell_strategic_plugin/launch/stop_and_dwell_strategic_plugin.launch.py
- stop_and_dwell_strategic_plugin/package.xml
- stop_and_dwell_strategic_plugin/src/main.cpp
- stop_and_dwell_strategic_plugin/src/stop_and_dwell_strategic_plugin.cpp
- stop_and_dwell_strategic_plugin/test/test_main.cpp
- stop_and_dwell_strategic_plugin/test/test_stop_and_dwell_strategic_plugin.cpp
- stop_and_dwell_strategic_plugin/test/test_strategic_plugin.cpp
https://usdot-carma.atlassian.net/wiki/spaces/CRMSIM/pages/2460680214/High-level+Design+of+Random+Dwell+Time+at+stops+i.e+Bus+Stop+with+XIL?atlOrigin=eyJpIjoiYmMzMGI3YTA4NTRiNDRlNWExMzEwZjVjYjYwY2U3MTIiLCJwIjoiYyJ9
https://usdot-carma.atlassian.net/wiki/spaces/CRMPLT/pages/2465824769/Detailed+Design+-+Stop+and+Dwell+Strategic+Plugin
For CARMA Proof-of-Concept TSMO Transit Signal Priority (TSP) Use Case testing in CARMA XIL co-simulation tool, CDA-enabled transit vehicles equipped with CARMA Platform must be capable of stopping at bus stops for a random / software-configurable amount of time.
The stop_and_dwell strategic plugin should plan for a stopping maneuver as a CDA-enabled transit vehicle approaches a bus stop, command the transit vehicle to stop for a random / software configurable …
> stop_and_dwell_plugin

- engineering_tools/carma_script_extensions/cloud-sim
Fix sed regex in cloudscript, previously only filtered the first instance of each pattern matched.
Fixes issues for account names with multiple .'s or @'s.
Validated the new regex in bash.
> Update cloud-sim stack-name regex

- carma/launch/plugins.launch.py
This PR updates the a topic remapping in plugins.launch.py so that the approaching_emergency_vehicle_plugin publishes hazard lights commands to the /hardware_interface/hazard_light_status topic rather than the /guidance/hazard_light_status topic. This change is required because the carma ssc wrapper node subscribes to the /hardware_interface/hazard_light_status topic.
Issue #2099 
Integration tested on White Truck at Suntrax.
> Fix topic remapping for approaching_emergency_vehicle_plugin's publication of hazard lights status 

- docs/Release_notes.md
This PR is to update release notes for hotfix 4.4.1 and 4.4.2
> Hotfix releasenotes 

- carma/launch/localization.launch
- carma/launch/localization.launch.py
Port dead reckoner ros2
https://github.com/usdot-fhwa-stol/carma-platform/issues/2116
local integration tested
> port dead reckoner ros2

- carma/launch/localization.launch
- carma/launch/localization.launch.py
Porting random filter and voxel grid filter points downsampled to ROS2
This also fixes a bug where wrong node name is being used for deadreckoner. Attached an issue for the record.
https://github.com/usdot-fhwa-stol/carma-platform/issues/2122
https://github.com/usdot-fhwa-stol/carma-platform/issues/2120
ROS2 migration of localization stack. 
Local integration test in progress
> lidar stack

- docs/Release_notes.md
This PR is to update release notes with new version carma-system-4.4.3 (XIL Release)
> Update Release_notes.md XIL Release (carma-system-4.4.3)

- engineering_tools/carma_script_extensions/cloud-sim
This PR fixes an issue with creating a new user in the cloud sim stack. Currently the script attempts to calculate an increment from the last octet of the IP, when it should be using the second from last octet.
This change fixes the deployment to update the correct octet in the subnet for the new user.
> fix subnet increment

- carma_cooperative_perception/include/carma_cooperative_perception/msg_conversion.hpp
- carma_cooperative_perception/src/msg_conversion.cpp
- carma_cooperative_perception/test/test_msg_conversion.cpp
This PR adds true heading calculation for an external object.
[CDAR-252](https://usdot-carma.atlassian.net/browse/CDAR-252)
[CDAR-252]: https://usdot-carma.atlassian.net/browse/CDAR-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add obj true heading calc

- carma_cooperative_perception/CMakeLists.txt
- carma_cooperative_perception/CPPLINT.cfg
- carma_cooperative_perception/config/params.yaml
- carma_cooperative_perception/dependencies.cmake
- carma_cooperative_perception/docs/multiple_object_tracker_node.md
- carma_cooperative_perception/docs/package_design.md
- carma_cooperative_perception/include/carma_cooperative_perception/multiple_object_tracker_component.hpp
- carma_cooperative_perception/launch/cooperative_perception_launch.py
- carma_cooperative_perception/package.xml
- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
- carma_cooperative_perception/src/multiple_object_tracker_node.cpp
- carma_cooperative_perception/test/data/detection_list_duplicates.yaml
- carma_cooperative_perception/test/data/detection_list_static.yaml
- carma_cooperative_perception/test/multiple_object_tracker_duplicates_launch_test.py
- carma_cooperative_perception/test/multiple_object_tracker_static_obstacle_launch_test.py
- docker/checkout.bash
Closes #2164 
[CDAR-97](https://usdot-carma.atlassian.net/browse/CDAR-97)
[CDAR-97]: https://usdot-carma.atlassian.net/browse/CDAR-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Add multiple object tracker node

- .circleci/config.yml
- carma/launch/carma_src.launch.py
- docker/checkout.bash
- docker/install.sh
This PR integrates ros2_tracing into carma-platform and updates carma_src.launch.py to enable a user to launch a ROS 2 Tracing session with CARMA Platform. 
Related carma-base PR: [#183](https://github.com/usdot-fhwa-stol/carma-base/pull/183)
Related carma-config PR: [#282](https://github.com/usdot-fhwa-stol/carma-config/pull/282)
Additionally, a small unrelated update was made as part of this PR to add the `novatel_oem7_driver` package to COLCON_IGNORE since the package does not need to be built in carma-platform. A previous PR [(carma-platform PR @2133)](https://github.com/usdot-fhwa-stol/carma-platform/pull/2133) updated the `checkout.bash` script to checkout a repository containing two packages (`novatel_oem7_driver` and `novatel_oem7_msgs`), and only the `novatel_oem7_msgs` package …
> Integrate ros2_tracing into carma-platform

- carma/launch/carma_src.launch.py
- carma/launch/drivers.launch.py
- carma/launch/environment.launch.py
- carma/launch/guidance.launch.py
- carma/launch/localization.launch.py
- carma/launch/message.launch.py
- carma/launch/plugins.launch.py
- carma/launch/ros2_rosbag.launch.py
- carma/launch/transforms.launch.py
- carma/rviz/carma_default.rviz
Enables use_sim_time parameter for all nodes.
Supporting PR: https://github.com/usdot-fhwa-stol/carma-config/pull/296
https://github.com/usdot-fhwa-stol/carma-platform/issues/2224
CDAR-613
https://usdot-carma.atlassian.net/browse/CDAR-613
integration testing CDAR VRU use case
Shown to start multiple times reliably and checked their nodes' time on simulation 1 PC.
> use_sim_time for all nodes

- motion_computation/config/parameters.yaml
Increasing predicton period so that yield_plugin has enough data for VRU crossing pedestrian. 
Walking pedestrian is on average 1.3 m/s and 2 lane road is on average 8 meters. So it needs minimum 6.15 seconds for pedestrian's prediction to cover the crosswalk. I am adding extra for buffer but reduced the prection step so that it doesn't create too many unnecessary predictions
> increase prediction period

- trajectory_visualizer/src/trajectory_visualizer.cpp
This PR is to add gray option for trajectory visualization. Currently the stopping trajectory is visualizer as green which could be still significant speed. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/2251
CDAR-648
https://usdot-carma.atlassian.net/browse/CDAR-648
CDASim PC1
> Visualizer stopping trajectory better

- object_visualizer/config/parameters.yaml
- object_visualizer/include/object_visualizer/object_visualizer_config.hpp
- object_visualizer/src/object_visualizer_node.cpp
Adds sphere and cylinder options for the object visualization. 
This also checks in case the size is not available and assigns it. It looks like this now:
https://github.com/usdot-fhwa-stol/carma-platform/issues/2256
CDAR-568
https://usdot-carma.atlassian.net/browse/CDAR-568
Integration testing VRU Use case 1
> Add different marker options

- carma_cooperative_perception/src/msg_conversion.cpp
This PR fixes an issue when converting Track IDs (from the CP stack) to ExternalObject ID. The Track ID to ExternalObject ID conversion (string to int) now handles cases where the mapping is not one-to-one.
Closes #2278 
Closes [CDAR-720](https://usdot-carma.atlassian.net/browse/CDAR-720)
Bug fix
[CDAR-720]: https://usdot-carma.atlassian.net/browse/CDAR-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add string to int ID conversion

- carma_wm_ctrl/src/WMBroadcasterNode.cpp
This PR updates the subscriber for incoming_geofence_control to be of type transient_local.
This change is required to keep the publisher and subscriber for the /incoming_geofence_control topic to be of a consistent QoS. 
Details about the QoS settings can be seen here, https://docs.ros.org/en/foxy/Concepts/About-Quality-of-Service-Settings.html
https://github.com/usdot-fhwa-stol/carma-platform/issues/2290
> Update geofence control sub to transient_local

- carma/config/rosbag2_qos_overrides.yaml
- carma/launch/ros2_rosbag.launch.py
This PR updates the storage format for rosbag2 to mcap.
mcap rosbag2 files are recorded with message definitions of the recorded messages, making it possible to read the rosbag in an environment where the messages have not been built. 
Further the mcap format is directly usable with the rosbag2 python API to parse messages without defining custom messages again and is also supported by analysis tools like Foxglove.
https://usdot-carma.atlassian.net/browse/WFD-474
Locally integration Tested
> Update rosbag2 recording format to mcap

- carma_cooperative_perception/src/msg_conversion.cpp
This PR fixes a bug when calculating SDSMs' detected objects' positions in the map frame. The SDSM conversion function was assuming position offsets were in the ENU frame, but they are actually in the NED frame. This PR adds a conversion function function.
Closes [CDAR-752](https://usdot-carma.atlassian.net/browse/CDAR-752)
The position offsets were making the wrong coordinate frame assumption.
[CDAR-752]: https://usdot-carma.atlassian.net/browse/CDAR-752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Convert SDSM position offsets from NED to ENU

- route/CMakeLists.txt
- route/test/test_route_generator.cpp
This package fixes several unit tests in the `route` package that were failing. 
These unit tests were failing due to the provided lanelet2 osm map files not being found. By installing the `resource` folder as part of `ament_auto_package()`, unit tests can now access the lanelet2 osm files contained in the package's `resource` folder.
With this update, all `route` package unit tests now pass.
#2300 
[CAR-6006](https://usdot-carma.atlassian.net/browse/CAR-6006)
Packages should not have failing unit tests. This will also help our CI process, which fails when encountering failing unit tests.
Unit tested locally.
[CAR-6006]: https://usdot-carma.atlassian.net/browse/CAR-6006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix failing unit tests in 'route' package

- carma_cooperative_perception/CMakeLists.txt
See title
Closes [CDAR-767](https://usdot-carma.atlassian.net/browse/CDAR-767)
Needed for using component in component manager
[CDAR-767]: https://usdot-carma.atlassian.net/browse/CDAR-767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CDAR-767 Register DetectionListVizNode

- engineering_tools/carma_script_extensions/cloud-sim
Fixes an issue in the cloud-sim startup script which was preventing more than 2 stacks to be launched together
https://github.com/usdot-fhwa-stol/carma-platform/issues/2309
https://usdot-carma.atlassian.net/browse/CAR-6010
Integration tested with 4 cloud-sim stacks created on AWS.
> Fix cloud-sim launch script for multiple users

- route_following_plugin/test/test_route_following_plugin.cpp
This PR updates a unit test in `route_following_plugin` to use `ament_index_cpp::get_package_share_directory()` to access a lanelet2 osm map file from the package's share directory. This fixes the unit test (which was failing previously). 
#2302 
[CAR-5822](https://usdot-carma.atlassian.net/browse/CAR-5822)
Packages should not have failing unit tests. This will also help our CI process, which fails when encountering failing unit tests.
All unit tests now pass locally.
[CAR-5822]: https://usdot-carma.atlassian.net/browse/CAR-5822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix failing unit test in 'route_following_plugin' package

- approaching_emergency_vehicle_plugin/test/test_approaching_erv.cpp
This PR updates a unit test in `approaching_emergency_vehicle_plugin` to use `ament_index_cpp::get_package_share_directory()` to access a lanelet2 osm map file from the package's share directory. This fixes the unit test (which was failing previously). 
#2321 
CF-784
Packages should not have failing unit tests. This will also help our CI process, which fails when encountering failing unit tests.
Re-ran unit tests locally and they all pass.
> Fix failing unit tests in 'approaching_emergency_vehicle_plugin' package

- basic_autonomy/src/basic_autonomy.cpp
Basic_autonomy sometimes extends trajectory using last two points if maneuever target distance is not reached.
However, due to map error, last 2 points in the trajectory could be duplicates.
This makes the extension logic to run indefinitely since it is "extending 0 distance" due to the duplicate points.
Therefore, this PR makes the extension logic to iterate back to find a distinct point other than the current one to do the extension.
https://github.com/usdot-fhwa-stol/carma-platform/issues/2327
https://usdot-carma.atlassian.net/browse/CDAR-817
vru verification testing prep
sim pc 1
> Fix traj extension edge case

- yield_plugin/src/yield_plugin.cpp
This PR fixes the goal position used in the yield_plugin to plan for stop. This goal position is not accounting for vehicle length to plan for stopping. In other words, if safety gap is 5 meters away and the vehicle length is 4 meters, it is really aiming for 1 meter between the vehicle's front bumper and the pedestrian. See the measurement picture below:
Before fix pic, where the measurement from planned stopping distance and collision distance shows 5.47 meters. However, please notice that the trajectory is planned from the back axle, and "vehicle front" would be close call with the vru. 
After fix pic, where I took a measurement when the platform started slowing down. The measurement at this time between "vehicle front" and vru was 6.54 which is more than 5.0 meters, so the fix worked: …
>  Safety gap calculation in yield_plugin to include vehicle length

- yield_plugin/config/parameters.yaml
- yield_plugin/include/yield_plugin/yield_config.hpp
- yield_plugin/include/yield_plugin/yield_plugin.hpp
- yield_plugin/src/yield_plugin.cpp
- yield_plugin/src/yield_plugin_node.cpp
- yield_plugin/test/test_yield.cpp
This PR adds consecutive_clearance_counter feature where platform doesn't accidentally detect that the vehicle would be passing the pedestrian. The functionality to detect whether if pedestrian was passed was first introduced so that the vehicle doesn't stop indefinitely if a pedestrian was within collision radius, but behind the vehicle. However, it is also making yield_plugin to ignore close calls and collisions if vehicle is predicted to barely miss the pedestrian. So the counter now should check consecutive 20 (which amounts to 2 sec approximately) to confirm if the vehicle is passed the pedestrian, otherwise err on the safer side and yield.
NOTE: it doesn't completely fix all occasions please see this issue. https://github.com/usdot-fhwa-stol/carma-platform/issues/2326
Following …
> Fix platform speeding up briefly while speeding up

- carma/launch/environment.launch.py
- carma/rviz/carma_default.rviz
By default we want to enable visualization for fused objects. Object visualizer is not publishing to fused objects viz topic by default. 
N/A
vru verification testing prep
sim pc 1
> Enable fused object visualization by default

- docker/checkout.bash
- system_controller/src/system_controller_node.cpp
TODO
Related carma-utils PR: [PR #223](https://github.com/usdot-fhwa-stol/carma-utils/pull/223)
[carma-platform GitHub Issue #2287](https://github.com/usdot-fhwa-stol/carma-platform/issues/2287)
[CAR-6018](https://usdot-carma.atlassian.net/browse/CAR-6019)
Tested in Ford Fusion on release/lavida. Verified that CARMA Web UI receives 'Drivers Ready' system alert even if the Web UI starts up long after the message is initially published by `drivers_controller`
[CAR-6018]: https://usdot-carma.atlassian.net/browse/CAR-6018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Configure /system_alert publisher in system_controller to have 'transient local' quality of service (QoS)

- .circleci/config.yml
- .github/workflows/dockerhub.yml
- Dockerfile
- docker/checkout.bash
> Update version to 4.5.0

- docker/checkout.bash
> Fix rosbag2 branch clone

- .github/workflows/dockerhub.yml
> Add trigger for carma-system tag to build dockerhub

- carma_cloud_client/src/carma_cloud_client_node.cpp
- carma_cloud_client/test/node_test.cpp
It was found that carma_cloud_client is not able to parse the type of geofences (such as taperright, openleft) correctly. And it was preventing signalized workzone to work on newer releases with cellular connection to CARMA Cloud.
#2297 
https://usdot-carma.atlassian.net/browse/CDAD-40
Ensure carma platform is backward compatible and is able to process all types of TCMs through cellular communication.
Unit test and Integration test on Blue Lexus
> CDAD-40 Fix cloud client parsing TCMs

- docs/Release_notes.md
Update Release notes title to CARMA System
> Update Release notes title to CARMA System 

- .github/workflows/Ci.yml
- Dockerfile
I re-ordered the GIT_BRANCH variable and the build works fine now with incremental builds - you can see the GIT_BRANCH set to carma-system-4.5.0 is being correctly used
Please see the jira ticket for the original issue description.
```
12:15:28 carma@stol-MS-7D91 ~/carma_ws/src/carma-platform/docker (develop) $ ./build-image.sh --ros2 yield_plugin
Performing incremental build of image to rebuild packages: ROS1>>  ROS2>>  yield_plugin...
Updating Dockerfile references to use most recent image as base image
Using SNAPSHOT b84380248b99 18 minutes ago as base for partial build...
Building docker image for carma-platform version: SNAPSHOT
Final image name: local/carma-platform:SNAPSHOT
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
BuildKit is currently …
```
> carma-platform is not buildable locally due to Dockerfile bug

- engineering_tools/msgIntersect.py
Adding message intersect script for parsing payload from V2X Hub and sending to CARMA Messenger.
Tested using V2X Hub 7.6.0 and CARMA Messenger 4.5.0. Messages received by CARMA Messenger were successfully decoded.
> 	new file:   engineering_tools/msgIntersect.py

- .github/workflows/Ci.yml
- Dockerfile
Related to this is the CI.yml where it is not using the dynamic branch selection we introduced and is hardcoded to run on autoware.ai:develop as well as its checkout script is using hardcoded BRANCH=develop line in checkout.sh script that is meant for failsafe.
Please see the original Ticket for more details:
[CAR-6034](https://usdot-carma.atlassian.net/browse/CAR-6034)
NA
[CAR-6034](https://usdot-carma.atlassian.net/browse/CAR-6034)
CI is using hardcoded branches and images after master release of 4.5.0
tested on the PR itself and 
https://github.com/usdot-fhwa-stol/carma-platform/pull/2382 OR
https://github.com/usdot-fhwa-stol/carma-platform/actions/runs/9021704219
where I tested against release/lavida (which shows failed due to some branches not existing anymore, but the correct branch …
> carma-platform is not using dynamic dependency in its CI

- approaching_emergency_vehicle_plugin/test/test_approaching_erv.cpp
Disables intermittently failing unit test in order to allow CI to run through new packages. The unit test commented out seems to be passing locally but fails on CI at times possibly due to issues related to time taken by the service call.
Time dependency within unit causes this check in approaching_emeergency_response_vehicle_plugin to intermittently fail on CI.
https://github.com/usdot-fhwa-stol/carma-platform/issues/2335
[CAR-6045](https://usdot-carma.atlassian.net/browse/CAR-6045)
[CAR-6045]: https://usdot-carma.atlassian.net/browse/CAR-6045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> disable unit test for CI

- motion_computation/config/parameters.yaml
- motion_computation/include/motion_computation/motion_computation_config.hpp
- motion_computation/include/motion_computation/motion_computation_worker.hpp
- motion_computation/src/motion_computation_node.cpp
- motion_computation/src/motion_computation_worker.cpp
Utility function to make motion models in motion computation configurable to easily test
https://github.com/usdot-fhwa-stol/carma-platform/issues/2398
https://usdot-carma.atlassian.net/browse/CAR-6057
See above link
sim pc tested
> Make motion models in motion comp configurable

- docs/Release_notes.md
This PR is to update miura release notes with new version carma-system-4.6.0
> Update Release_notes.md for miura release 

- carma/launch/plugins.launch.py
update trajectory follower params directory in launch file.
[
](https://usdot-carma.atlassian.net/browse/ARC-79)
Directory name is more clear.
Integration tested on Blue Lexus
> update trajectory follower params directory

- docs/Release_notes.md
Update Release_notes.md for Release Neon
> Update Release_notes.md for Release Neon

- .github/workflows/Ci.yml
This PR updates the runner size to 16 cores in our current CI workflow to reduce reruns by the development team when builds or tests fail, which consumes more resource minutes.
> Update GitHub Actions Runner size 

- docs/Release_notes.md
> Update Release_notes.md for Hotfix- 4.6.1(Miura)

- docker/checkout.bash
This PR: https://github.com/usdot-fhwa-stol/carma-platform/pull/2437
merged custom branch into develop, which should be reverted
NA
Resolves error introduced as part of ARC-146
See above.
Not required.
> Fix checkout.bash

- README.md
This PR includes an update to the repository's README that includes a short write-up to explain that the CARMA Platform system has a mixture of ROS 1 Noetic and ROS 2 Foxy content, and that this is a repository with some of the remaining ROS 1 Noetic content. It points to more detailed documentation contained within the carma-config repository.
ARC-147
Testing not necessary; only an update to the repository's README is included.
> ARC-147: Add documentation regarding mixture of ROS 1 and ROS 2 packages in this repository

- docs/Release_notes.md
Updated Release_notes.md with Neon Hotfix Releases (4.7.1, 4.7.2, 4.7.3)
> Update Release_notes.md with Neon Hotfix Releases

- carma/config/rosbag2_qos_overrides.yaml
- carma/launch/ros2_rosbag.launch.py
This PR adds additional topics to the qos profile overrides to ensure transient_local messages are recorded to the rosbag. 
Since these topics are not publishing frequently it is likely that messages from them can be missed if the rosbag recording process starts late. Specifying the QoS with the history parameter specifying the messages to keep will ensure we are able to record the topic up to the required history.
https://usdot-carma.atlassian.net/browse/ARC-231
> Arc 231 fix ros2 bag record

- engineering_tools/msgIntersect.py
Updated script to remove sleep/delay. This was mistakenly kept in and introduces unneeded delays in message forwarding. 
Found there were unexpected latencies in some messages I was receiving while using this script.
> 	modified:   engineering_tools/msgIntersect.py

- .github/workflows/Ci.yml
- Dockerfile
- carma_cloud_client/package.xml
- docker/build-image.sh
- docker/checkout.bash
- docker/install.sh
This PR includes final changes needed for CARMA Platform to build in ROS 2 Humble as well as changes that prevent all dependencies from reinstalling when making code edits.
Related PR: https://github.com/usdot-fhwa-stol/carma-base/pull/223
NA
[ARC-259](https://usdot-carma.atlassian.net/browse/ARC-259)
Needed as part of the ROS 2 Humble migration efforts.
Confirmed that all packages in platform build with ROS2 Humble.
[ARC-259]: https://usdot-carma.atlassian.net/browse/ARC-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Arc 259 to humble and beyond

- .github/workflows/dockerhub.yml
> Fix manual trigger

- .github/workflows/dockerhub.yml
> Fix dockerhub manual trigger for develop-humble

- README.md
- carma-platform.repos
- docs/mainpage.md
- engineering_tools/msgIntersect.py
This PR updates references to the carma-cohda-dsrc-driver with v2x-ros-driver.
https://usdot-carma.atlassian.net/browse/ARPA-16
> Rename references to carma-cohda-dsrc-driver

- docs/Release_notes.md
This PR includes updates to release_notes.md with prowler release changes
> Update Release_notes.md with Prowler Release

- .github/workflows/Ci.yml
- .github/workflows/dockerhub.yml
- docker/checkout.bash
- docker/install.sh
ROS2 analysis scripts needed some ROS1 controller topics to be recorded, so adding their support.
NA
ARC-254
Control improvement analysis scripts
Locally tested whether if msgs are being published and received
> Add ROS2 version of the controller msgs to record mcap

- .github/workflows/auto-merge-workflow.yml
- README.md
- carma-platform.repos
- carma/config/rosbag2_qos_overrides.yaml
- carma/launch/carma_src.launch.py
- carma/rviz/carma_default.rviz
- carma/rviz/carma_default_ros2.rviz
- carma_wm/include/carma_wm/SignalizedIntersectionManager.hpp
- carma_wm/src/SignalizedIntersectionManager.cpp
- carma_wm_ctrl/include/carma_wm_ctrl/Geofence.hpp
- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.hpp
- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcasterNode.hpp
- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/src/WMBroadcasterNode.cpp
- docker/checkout.bash
- docs/Release_notes.md
- docs/System_description.md
- docs/mainpage.md
- engineering_tools/monitor-ros-cpu.py
- engineering_tools/msgIntersect.py
- lci_strategic_plugin/test/test_strategic_plugin_helpers.cpp
- subsystem_controllers/config/v2x_controller_config.yaml
> Merge develop

- carma/rviz/carma_default_ros2.rviz
> Fix rviz2 config

- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/src/WMBroadcasterNode.cpp
Sync https://github.com/usdot-fhwa-stol/carma-platform/pull/2497
> Sync develop

- docker/checkout.bash
This PR removes the rosbridge websuite from being installed in carma-platform, since the humble version for the packages in this are already being installed in carma-base  https://github.com/usdot-fhwa-stol/carma-base/blob/f7e81cb418a0b61292bf155f83ae834ecc4a07b8/humble/ros_packages.txt#L29.
> Remove checkout for rosbridge suite

- docker/checkout.bash
There was some dependency missing in humble for ros2 trace tools: 
https://github.com/usdot-fhwa-stol/carma-base/pull/239
And it also seems that at least the `tracetools` package still needs to be built from source despite being installed from debian in the guide:
https://docs.ros.org/en/humble/How-To-Guides/Building-ROS-2-with-Tracing-Instrumentation.html
Only after following the guide and building at least `tracetools` made it work.
Otherwise, the folder was being created but not the recording. 
NA
ARC-179
ROS2 Humble
In sim PC 1
> Fix trace tools

- yield_plugin/include/yield_plugin/yield_plugin.hpp
- yield_plugin/src/yield_plugin.cpp
During testing of TM/TSP with background vehicles, sometimes the vehicle is shutting down due to 2 exceptions. 
This PR makes the service call safer so that it doesn't let it shut down unnecessarily for the time being. 
This is because currently there are 2 open issues (see below) that is blocking any normal testing of carma-platform in Town05 simulation. If the exception is safely ignored for now, vehicle resumes normal operation and finishes the route. 
These are the 2 issues notices:
Not sure why but yield is generating negative time sometimes: https://github.com/usdot-fhwa-stol/carma-platform/issues/2501
Due to not safely handling osm map issue, sometimes trajectory generation can fail due to erroneous spline: https://github.com/usdot-fhwa-stol/carma-platform/issues/2503
Currently it …
> Improve yield_plugin to remove exceptions and shut downs

- carma/launch/carma_src.launch.py
- carma/launch/guidance.launch.py
- carma_wm/include/carma_wm/CARMAWorldModel.hpp
- carma_wm/src/CARMAWorldModel.cpp
- carma_wm/src/WMListener.cpp
- carma_wm/src/WMListenerWorker.cpp
- carma_wm/src/WMListenerWorker.hpp
This PR renames the flag to treat spat time as based on wall clock. This is required for voices where carma-platform is running in simulation but the spat messages coming in are based on a wall clock.
The default value for the flag is also updated to False - to mean that this is not an expected default condition. We expect incoming spat in simulation environment to be based on sim clock. Since this parameter is always used in conjunction with is_sim flag it does not change behavior for physical vehicles.
> Update default value SPAT is wall clock flag

- basic_autonomy/include/basic_autonomy/basic_autonomy.hpp
- basic_autonomy/include/basic_autonomy/impl/basic_autonomy.tpp
- basic_autonomy/src/basic_autonomy.cpp
- basic_autonomy/test/test_waypoint_generation.cpp
Some maps, especially the simulation maps in TownX, have many duplicate points. In below picture, all the duplicate points are moved away from its initial location to clearly illustrate how many points can be located in one spot. See below picture:
This will result in an random, invalid trajectory like issue:
This fails the spline fit function because it doesn't expect duplicate points. Although carma downsaples the points, it is not based on distance, but only index of a vector (take every n-th points). This means that if there are more than n duplicate points, carma could create bad spline fit. Indeed, Town04 for example had more than 18 duplicate points as printed by DEBUG (I just toggled it to ERROR temporarily) logs:
https://github.com/usdot-fhwa-stol/carma-platform/issues/2503 …
> Fix for removing duplicate lane centerline points during trajectory generation

- carma/rviz/carma_default_ros2.rviz
Following humble update the tcm visualizer marker in rviz was found to be broken. This PR updates the topic subscription in rviz to listen to volatile since the publisher is defined without a reliability specified and defaults to volatile.
Link to carma_wm_ctrl where the publisher is defined:
https://github.com/usdot-fhwa-stol/carma-platform/blob/7e1bb62512cc11b393dd9e6ab6568d5df3295c3b/carma_wm_ctrl/src/WMBroadcasterNode.cpp#L140
https://usdot-carma.atlassian.net/browse/ARC-339
> fix tcm visualizer QoS

- yield_plugin/config/parameters.yaml
- yield_plugin/include/yield_plugin/yield_plugin.hpp
- yield_plugin/src/yield_plugin.cpp
- yield_plugin/test/test_yield.cpp
Previously we ignored the initial condition especially acceleration in JMT algorithm - it always assumed 0 m/s^2 acceleration initial condition. 
This will make the trajectory try to plan a brand new minimum jerk trajectory from the beginning which would eventually run out of time to have a perfect speed profile shape. By adjusting the initial condition and accounting for the fact that the JMT algorithm is already on the way, we should successfully achieve the desired speed profile shape theoretically.
This is a speed profile pic from before (doesn't slow down as quite as fast compared to after pic):
After (more consistent deceleration, instead of "continuously under-decelerate then decelerate fast toward the end):
JMT algorithm should show aggressive deceleration in the middle and small …
> Fx initial conditions in JMT algorithm in yield plugin

- lci_strategic_plugin/config/parameters.yaml
Some of these parameters were used to test the UC2, which might be useful as default for quick demo setup.
Simulations use slightly different parameters, which have their own separate file, so they won't be affected by this.
Since last time these parameters were used, the controls improved a bit, which is why they need a different values.
NA
NA
ROS2 Humble regression testing and demo on 4/24/2025
Black Pacifica
> New parameters for UC2 lci_strategic_plugin

- carma/rviz/carma_default_ros2.rviz
- localization_manager/config/parameters.yaml
- Turns off visualization of external object predictions (/environment/motion_computation_visualize topic) in rviz. Prediction is still activated in CARMA Platform, but we're just not showing it in rviz
- Uses file for URDF so that we can visualize the vehicle: https://github.com/usdot-fhwa-stol/carma-vehicle-calibration/pull/134
- Makes the localization mode to 5 by default
> Disable motion prediction visualization & use fixed offset

- cooperative_lanechange/config/parameters.yaml
- object_visualizer/config/parameters.yaml
Reduces pedestrian icon size and increases starting downtrack range
> Config Updates

- localization_manager/config/parameters.yaml
This PR changes the default localization mode of CARMA platform to use GNSS only with a fixed offset.
[CAR-6121](https://usdot-carma.atlassian.net/browse/CAR-6121)
For the past 2+ years, the team has opted localize with CARMA Platform using “GNSS Only with Fixed Offset” in CARMA Platform (see localization_mode parameter in the localization_manager package: [here](https://github.com/usdot-fhwa-stol/carma-platform/blob/e656bacec697ec01a32a60025efdf8d62e6a963b/localization_manager/config/parameters.yaml#L43)). The team has had to manually update CARMA Platform to do so, since the default localization method has been “GNSS only with NDT initialization”.
Tested locally to confirm the `localization_mode` parameter is set correctly.
[CAR-6121]: …
> CAR 6121 GPS + Fixed-Offset Localization

- engineering_tools/vector_map_scripts/osm_transform.py
A script is created to transform a vector map to a new coordinate.
This script relocates and optionally rotates an OpenStreetMap (OSM) file that uses a custom geoReference. It's useful when you want to:
- Move a local map to a new geographic location.
- Preserve geometry, scale, and layout.
- Rotate the map around its origin (for alignment or testing).
https://usdot-carma.atlassian.net/browse/CDAD-101
This script allows us to relocate a vector map to a different geographic location without the need to recreate it from scratch.
Tested on Blue Lexus by transforming Suntrax to TFHRC
> added osm map transform script

- engineering_tools/vector_map_scripts/osm_transform.py
OSM map transform script is updated to allow the user to rotate the OSM map around an arbitrary point. Previously, the script was rotating the map around its centroid, which made it difficult to position vector map on a specific location after transform.
https://usdot-carma.atlassian.net/browse/CDAD-110
TO be able to use a projected map easier.
> update map script to rotate around arbitrary point

- object_visualizer/config/parameters.yaml
Update object visualizer config to enable pedestrian icon.
> enable pedestrian icon
