usdot-fhwa-stol/carma-platform

- j2735_convertor/CMakeLists.txt
Removed an unecessary "install" directive in the CMakeLists.txt that was preventing proper installation via `catkin_make install`.
> Remove install command for empty directory

- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/ead/trajectorytree/CoarsePathNeighbors.java
- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/ead/trajectorytree/FinePathNeighbors.java
This resolves the clipping of the max speed profile in the course plan, by having the fine plan add an additional node whenever it will reach the top speed.
> Alternative fix for speed clipping in course plan

- carmajava/launch/params/GuidanceParams.yaml
- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/TrafficSignalManeuverInputs.java
- carmajava/signal_plugin/src/main/java/gov/dot/fhwa/saxton/carma/signal_plugin/TrafficSignalPlugin.java
This PR undoes the changes to GuidanceParams previously required for TrafficSignalPlugin to work properly. It replaces these changes with a wrapper class around the base ManeuverInputs implementation. This allows the response lag and max acceleration to be injected by the plugin for maneuver planning.
> Remove need for GuidanceParams changes in Traffic Signal Plugin

- carmajava/launch/cadillac_config/drivers.launch
- srx_controller/launch/srx_controller.launch
Resolves issue #70 by allowing PID parameters to be set via launch file or command line arguments to a launch file. 
srx_controller/launch/srx_controller.launch file is modified to allow PID parameters to be injected at launch as arguments. 
cadillac_config/drivers.launch is updated to inject current best choice PID values based on tuning and experimentation. 
The high speed PID values come from tuning at Aberdeen Proving Grounds while the low speed values were tuned at Turner Fairbank High Research Center. 
#70 
At low speed the hard coded srx speed controller PID parameters do not demonstrate sufficient rise time. This makes planning based applications like the TrafficSignalPlugin have poor performance. See the related issue above. 
PID parameters were tuned using these modifications by …
> Make srx controller PID values configurable as launch file arguments

- carmajava/guidance_plugin_api/src/main/java/gov/dot/fhwa/saxton/carma/guidance/maneuvers/BasicAccStrategy.java
- carmajava/guidance_plugin_api/src/main/java/gov/dot/fhwa/saxton/carma/guidance/maneuvers/IAccStrategy.java
Resolves Issue #86. 
Issue number 86 was caused by the standoff distance being applied twice in the evaluateAccTriggerConditions function. This made it possible to both trigger ACC and exit ACC in a single iteration of  computeAccOverrideSpeed. This change removes the extra application of standoff distance to the calculated timegap
#86 
Improve ACC performance to help improve Traffic Signal Plugin NCV handling behavior
Ran the Traffic Signal Plugin with the change behind and NCV as described by the issue reproduction instructions. After change was applied, the incorrect behavior was no longer observed. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] I have read the **CONTRIBUTING** document.
> Fix duplicate application of standoff distance when calculating ACC gap

- sensor_fusion/CMakeLists.txt
- sensor_fusion/src/sensor_fusion.cpp
- sensor_fusion/src/sensor_fusion.h
- sensor_fusion/src/transform_maintainer.cpp
- sensor_fusion/src/transform_maintainer.h
- sensor_fusion/src/wgs84_utils.cpp
- sensor_fusion/src/wgs84_utils.h
- sensor_fusion/tests/transform_maintainer_test.cpp
Resolves Issue #88 
Prevents a race condition between sensor fusion and roadway described in the referenced issue. TF publication is moved to sensor fusion. The code is a direct port of the TransformMaintainer.java class from the roadway package into C++. This code was previously in the fix/sensor_fusion_lat_lon_conv branch of the pre-release repo, but was never merged in due to it being a lower priority issue. After having difficulties with detecting NCVs while testing the Traffic Signal Plugin one day, I moved the port. I have not observed an issues resulting from this change in the week or so since performing the port.
If this is merged in the documentation for roadway/sensor fusion will need to be updated. I will add a Jira ticket for that.  
#88 
Improve object detection and sensor …
> Convert transform math to C++ and move from Roadway to Sensor Fusion

- carmajava/build.gradle
- carmajava/rosjava_bootstrap.gradle
This resolves issue #101 by creating a local copy of the rosjava bootstrap gradle build file which removes the new google() line. 
#101 
Allows code in develop to build.
Built code
> Fix build error by adding local copy of bootstrap file to repo

- srx_controller/include/srx_controller/srx_dbw_controller.h
- srx_controller/launch/srx_controller.launch
- srx_controller/src/srx_dbw_controller.cpp
Allows the light bar to be controlled even when the vehicle is not under automated control.
A parameter was added to allow for this feature to be turned on and off.
#103 
We want the light bar on when the vehicle is off for demonstration at TRB
Yes on the silver cadillac. Used when only the electronics were powered. 
> Allow lights when disengaged

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/plugins/PluginLifecycleHandler.java
- carmajava/guidance/src/test/java/gov/dot/fhwa/saxton/carma/guidance/plugins/PluginLifecycleHandlerTest.java
- carmajava/guidance/src/test/java/gov/dot/fhwa/saxton/carma/guidance/trajectory/LocalSpeedLimitConstraintTest.java
Two fixes are in this PR. One is for fixing PluginLifecycleHandler race condition. The other is to fix a NPE in LocalSpeedLimitConstraintTest.
For PluginLifecycleHandler, the ```doTerminate()``` function interrupts the PluginLifecycleHandlerWorker thread before it give the TerminatePluginTask task to PluginLifecycleHandlerWorker. So there is a race condition where the PluginLifecycleHandlerWorker stops looping before it executes TerminatePluginTask job.
#175 
Fix #175 
Passed 5 times locally and twice on CI build.
> Fix guidance unit tests

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/GuidanceCommands.java
- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/GuidanceStateHandler.java
- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/Tracking.java
- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/lightbar/LightBarManager.java
- carmajava/launch/saxton_cav_src.launch
- carmajava/message/src/main/java/gov/dot/fhwa/saxton/carma/message/MessageConsumer.java
- carmajava/mock_drivers/src/main/java/gov/dot/fhwa/saxton/carma/mock_drivers/MockCANDriver.java
- carmajava/mock_drivers/src/main/java/gov/dot/fhwa/saxton/carma/mock_drivers/MockDSRCDriver.java
- carmajava/mock_drivers/src/main/java/gov/dot/fhwa/saxton/carma/mock_drivers/MockPinPointDriver.java
- carmajava/mock_drivers/src/main/java/gov/dot/fhwa/saxton/carma/mock_drivers/MockRadarDriver.java
- carmajava/mock_drivers/src/main/java/gov/dot/fhwa/saxton/carma/mock_drivers/MockSRXControllerDriver.java
- carmajava/mock_drivers/src/main/java/gov/dot/fhwa/saxton/carma/mock_drivers/MockTruckControllerDriver.java
- carmajava/platooning/src/main/java/gov/dot/fhwa/saxton/carma/plugins/platooning/PlatooningPlugin.java
Modify legacy CARMA consumer nodes to use the launch file mapping instead of using Interface Manager for driver discovery.
Originally, the CARMA consumer nodes used Interface Manager to connect to different drivers. However, this feature is removed from CARMA3 design document. This PR is about removing driver discovery service call from consumer nodes. There will be a follow-up PR for modifying Interface Manager.
The interactions are removed from: GuidanceCommands, GuidanceStateHandler, LightBarManager, MessageConsumer and Platooning Plugin. The launch file is modified for mapping to correct topic names.
#177
Update CARMA legacy code to match new API requirement.
N/A
> Remove interactions with interface mgr

- configurations/cadillac_srx_2013_platooning_demo/.dockerignore
- configurations/cadillac_srx_2013_platooning_demo/Dockerfile
- configurations/cadillac_srx_2013_platooning_demo/HostVehicleParams.yaml
- configurations/cadillac_srx_2013_platooning_demo/build-image.sh
- configurations/cadillac_srx_2013_platooning_demo/carma.config.js
- configurations/cadillac_srx_2013_platooning_demo/docker-compose-background.yml
- configurations/cadillac_srx_2013_platooning_demo/docker-compose.yml
- configurations/cadillac_srx_2013_platooning_demo/drivers.launch
- configurations/cadillac_srx_2013_platooning_demo/saxton_cav.launch
- configurations/cadillac_srx_2013_platooning_demo/saxton_cav.urdf
This adds a platooning demo configuration to the configurations folder for use on the colonial farm road demo run. It modifies the docker compose file to set the pid parameters to the old high speed values see line 87 in compose file and drivers.launch comment to confirm values. 
> Add platooning demo configuration

- engineering_tools/carma
Missing "bash" command at end causes edit and inspect command to do nothing.
Quick hotfix to correct error introduced by revisions of carma-base that require explicit invocation of bash to spawn a shell inside the CARMA base container.
> Fix edit command

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/CarmaVersion.java
- carmajava/mock_drivers/src/main/java/gov/dot/fhwa/saxton/carma/mock_drivers/MockSRXControllerDriver.java
- engineering_tools/remote_install.bash
This is an enhancement for Sprint 7 to include the light bar status on the UI. This entails having a topic from SRXController to publish the light bar status. 
During development, there are 2 lightbars back and rear. But since you can only set both at this time, we based the topic on the front lightbar status.
NA
Tested the initial topic published by carma. See pic attached. 
- [x ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](Contributing.md) 
- [ x] I have added tests to cover my changes.
> Added mock topic for light bar status and updated remote_install script

- carmajava/launch/saxton_cav_src.launch
This removes received_messages and sent_messages topics from rosbags by default
On current vehicles they match to this
```   
/saxton_cav/drivers/can0/received_messages                                      
/saxton_cav/drivers/can1/received_messages                                            
/saxton_cav/drivers/can1/sent_messages                                 
/saxton_cav/drivers/can2/received_messages
```
It is necessary to remove raw CAN data from default rosbag recording to ensure generated bags do not contain sensitive vehicle manufacturer information. 
Tested using the updated rosbag command on a subset of normal carma topics
> Add raw can data to rosbag exclusion list

- carmajava/guidance/src/main/java/gov/dot/fhwa/saxton/carma/guidance/util/GuidanceRouteService.java
- carmajava/platooning/src/main/java/gov/dot/fhwa/saxton/carma/plugins/platooning/CandidateFollowerState.java
Fix for Issue #200 
Still needs to be tested on the vehicle, but put up for review since it seems pretty clear cut. 
The getSpeedLimitAtLocation function in GuidanceRouteService was returning the incorrect limit when the speed limit value dropped below the current downtrack distance value. 
Additionally, the platooning plugin was inadvertently modifying the speed limits on the route. 
#200 
No exceptions should be thrown during normal operation
Java tests pass on CircleCi
Still needs to be tested on vehicle
> Fix issue #200

- carmajava/cooperativemerge/src/main/java/gov/dot/fhwa/saxton/carma/plugins/cooperativemerge/ExecutionState.java
- carmajava/cooperativemerge/src/main/java/gov/dot/fhwa/saxton/carma/plugins/cooperativemerge/StandbyState.java
- carmajava/rsumetering/src/main/java/gov/dot/fhwa/saxton/carma/rsumetering/CommandingState.java
- carmajava/rsumetering/src/main/java/gov/dot/fhwa/saxton/carma/rsumetering/HoldingState.java
- carmajava/rsumetering/src/main/java/gov/dot/fhwa/saxton/carma/rsumetering/RSUMeterWorker.java
The idea is to do some level of input validation on values coming in from mobility message strategy strings before using those values as a way to enhance system security.  The strategy string is initially parsed to pull out key/value pairs that match expected key strings. But the values could be anything that an attacker could inject into the message. A bogus value could have unhappy consequences for the vehicle's actions, so we need to check that they are reasonable.  This is a simple first step - more sophistication could be added in the future to narrow the range of acceptable values pertinent to the current situation.
#202
Desire is to add a bit more security to the system.
Unable to test at this time, but performed personal code review. …
> Sanity checks for strategy strings received in mobility messages

- carmajava/route/src/main/java/gov/dot/fhwa/saxton/carma/route/RouteWaypoint.java
Fixes issues #213 by removing old references to a former concept of maneuvers that is now being surfaced due to changes in `cav_msgs/Maneuver.msg`.
By modifying `cav_msgs/Maneuver.msg` this old (apparently unused and unneeded) code was broken. The removed code referenced a deep copy of a set of required maneuvers which was never used and never even stored inside the object that was doing the copy. As such this code has been removed. It may be worth considering removing this field from `cav_msgs/RouteWaypoint.msg` entirely in the near future, as the concept of required maneuvers given a route waypoint doesn't make a ton of sense under our current design.
Closes #213 
Resolved the compilation issue described in #213 
Resolution of the compilation error was verified by compiling locally. …
> Remove obsolete references to deprecated maneuver messages

- ndt_pose_tf_wrapper/CMakeLists.txt
- ndt_pose_tf_wrapper/launch/ndt_pose_tf_wrapper.launch
- ndt_pose_tf_wrapper/package.xml
- ndt_pose_tf_wrapper/src/ndt_wrapper_node.cpp
This PR contains a node to integrate NDT matching node from Autoware.
This node takes the current pose info from ndt_matching and republishes it as a transform between map frame and baselink for the usage of CARMA plarform.
N/A
CARMA platform takes in localization information by tf2 transform tree. This node makes sure that ndt_matching node outputs is the compatible to CARMA.
Build and test locally.
> NDT Wrapper node

- pure_pursuit_wrapper/CMakeLists.txt
- pure_pursuit_wrapper/include/pure_pursuit_wrapper/pure_pursuit_wrapper.hpp
- pure_pursuit_wrapper/include/pure_pursuit_wrapper/pure_pursuit_wrapper_worker.hpp
- pure_pursuit_wrapper/launch/TrajectoryPlan.message
- pure_pursuit_wrapper/launch/pure_pursuit_wrapper.launch
- pure_pursuit_wrapper/package.xml
- pure_pursuit_wrapper/src/pure_pursuit_wrapper.cpp
- pure_pursuit_wrapper/src/pure_pursuit_wrapper_node.cpp
- pure_pursuit_wrapper/src/pure_pursuit_wrapper_worker.cpp
- pure_pursuit_wrapper/test/pure_pursuit_wrapper_test.cpp
Add pure_pursuit_wrapper node.
The legacy Autoware pure_pursuit node will become a Carma control plugin.  Therefore, it needs to either be modified directly (in the Autoware fork) or a wrapper node needs to be built to interface between it and Carma Guidance so that it looks like a standard control plugin.  In either case, the existing interfaces between pure_pursuit and other Autoware plugins need to be severed.
This feature enables Carma Guidance to communicate with Autoware  pure_pursuit node
- [ X] New feature (non-breaking change that adds functionality)
- [`x`] My change requires a change to the documentation.
- [`x` ] I have updated the documentation accordingly.
- [`x`] I have read the **CONTRIBUTING** document. …
> Add pure_pursuit_wrapper node

- carma_utils/CMakeLists.txt
- carma_utils/include/carma_utils/CARMANodeHandle.h
- carma_utils/include/carma_utils/CARMAUtils.h
- carma_utils/package.xml
- carma_utils/src/carma_utils/CARMANodeHandle.cpp
- carma_utils/src/carma_utils/CARMAUtils.cpp
- carma_utils/test/carma_utils/CARMANodeHandle.test
- carma_utils/test/carma_utils/CARMANodeHandleTest.cpp
- carma_utils/test/carma_utils/CallRecorder.h
This PR adds a carma_utils package containing CARMANodeHandle.h/.cpp files. The CARMANodeHandle extends the roscpp NodeHandle and wraps all callbacks (sub, pub, srvs, timers) in exception handling logic. Users of this class will still interact with these functions as normal. However, to support the exception handling additional functionality is provided. 
By default a static subscription to "system_alert" is created when the first CARMANodeHandle() is created. This means users do not need to setup this subscriber themselves. However, they can still provide a callback for this subscription and publish to that topic using the provided setSystemAlertCallback and publishSystemAlert functions. 
In addition the user can add callbacks for exceptions and shutdown requests. 
There is a spin() …
> Add CARMANodeHandle to provide exception handling

- sensor_fusion/test/transform_maintainer_test.cpp
Add a script (actually an unit test) to find out the transform between MAP and ECEF based on current lat/lon and pose in MAP frame.
N/A
N/A
Save this script to find out the transform between MAP and ECEF for any map file.
Visualized on Google Map and compared with the actual origin of the map.
> find map to ecef tf

- trajectory_executor/config/roscpp_log.config
- trajectory_executor/src/test/test_utils.h
- trajectory_executor/src/trajectory_executor/trajectory_executor.cpp
Fixed leftover bugs in trajectory executor:
1. Exceptions were throw with the expectation that CARMANodeHandle would catch them and publish SystemAlert, but that only applies if you're using a specific callback from CARMANodeHandle. Since we're just using spin itself, we want to use `publishSystemAlert`.
2. Fix misc compilation issues that went undetected because I was re-running the already built unit tests by accident.
3. Fix unit test topic names broken by shifting to using a private node handle
Unit tests built clean and re-run locally.
> Fix usage of CARMANodeHandle exceptions and compilation errors

- sensor_fusion/test/transform_maintainer_test.cpp
The unit test for computing map to ECEF transforms was incorrectly accessing quaternion data. This resolves the access method. In addition it increases the print precision. 
> Fix ecef unit test quaternion usage

- route_generator/launch/route_generator.launch
Fix namespace issue for route generator parameters in launch file.
Change param namespace from public to private.
N/A
N/A
Tested locally.
> Fix route generator param

- carmajava/launch/guidance.launch
Remap autoware state topic to avoid conflict with CARMA guidance state topic.
Based on Kyle's input, some autoware component listen to a topic named "state". When we put those component into Guidance namespace, it becomes the same topic name as CARMA guidance state machine topic: guidance/state. To avoid conflict, we remap the Autoware state topic into "autoware_state" in the guidance launch file.
N/A
N/A
N/A
> Update Autoware state topic name

- carmajava/launch/ui.launch
Now that the UI is using static topics instead of going through the interface manager this PR properly remaps those topics to their actual location.
Tested locally by running `carma_src.launch` and verifying that the remapped topics appear to operate as expected.
> Remap new static topics in ui.launch

- carma_build
- carmajava/launch/localization.launch
Fixes topic re-mappings for the voxel grid filter after the ray_ground_filter was added. Also adds the ssc_interface (as package) into the carma_build script. 
> Fix voxel grid remappings and add missing autoware run dependancies

- bsm_generator/CMakeLists.txt
- bsm_generator/config/parameters.yaml
- bsm_generator/include/bsm_generator.h
- bsm_generator/include/bsm_generator_worker.h
- bsm_generator/launch/bsm_generator.launch
- bsm_generator/package.xml
- bsm_generator/src/bsm_generator.cpp
- bsm_generator/src/bsm_generator_worker.cpp
- bsm_generator/src/main.cpp
- bsm_generator/test/test_bsm_generator_worker.cpp
- carmajava/launch/message.launch
- sensor_fusion/src/wgs84_utils/wgs84_utils.cpp
BSM Generator Node generates BSM messages at 10Hz by collecting data from the rest of CARMAPlatform.
BSM Generator node is a standalone ROS node in the CARMA 3 platform. It collects data from multiple sources (e.g., positioning from localization node, speed from CAN driver) and composes basic safety messages (BSMs) for the host vehicle. Generated BSMs will send to the Message package for reformatting and broadcasting.
N/A
Enable BSM capability for connected vehicles.
Unit test passed
> BSM Generator

- carmajava/launch/carma_src.launch
- carmajava/launch/drivers.launch
- carmajava/launch/guidance.launch
- carmajava/launch/localization.launch
- gnss_to_map_convertor/include/gnss_to_map_convertor/GNSSToMapConvertor.h
- gnss_to_map_convertor/include/gnss_to_map_convertor/GNSSToMapNode.h
- gnss_to_map_convertor/src/gnss_to_map_convertor/GNSSToMapConvertor.cpp
- gnss_to_map_convertor/src/gnss_to_map_convertor/GNSSToMapNode.cpp
- gnss_to_map_convertor/test/gnss_to_map_convertor/GNSSToMapConvertorTest.cpp
Update the gnss_to_map_convertor to use the new GNSS driver api which relies on gps_common/GPSFix messages instead of sensor_msgs/NavSatFix as this message type contains more complete information. This should allow the system to operate without the HEADINGOFFSET being applied to the novatel device which is the source of the GPS issues on the vehicles. 
#275
Unit tests. Working on integration tests now
> Update gnss_to_map_convertor to use new gps api

- autoware_plugin/CMakeLists.txt
- bsm_generator/CMakeLists.txt
- carma_transform_server/CMakeLists.txt
- gnss_ndt_selector/CMakeLists.txt
- gnss_to_map_convertor/CMakeLists.txt
- guidance/CMakeLists.txt
- guidance_command_repeater/CMakeLists.txt
- j2735_convertor/CMakeLists.txt
- pure_pursuit_wrapper/CMakeLists.txt
- route_generator/CMakeLists.txt
- trajectory_executor/CMakeLists.txt
Sets the -Wall flag on CMakeLists so that all warnings are at least printed to console during build.
Catkin sometimes suppresses warnings that are indicative of a potential software defect. This change ensures that those errors are output to the terminal during build. 
Ensured all of the CARMA platform repos can build together locally after modifying the CMakeLists.txt
> Add enhanced warning flag output to catkin build process

- carma-platform.repos
Resolves #344 by removing the deleted CARMAPacmod3CanDriverWrapper repo from the .repos file.
Successfully ran
```
vcs import < carma-platform.repos
```
> Remove deprecated repo from repos file

- guidance/src/guidance/guidance_worker.cpp
Due to a typo, the index in for loop is used without initialization.
#356 
Fix #356 
N/A
> Fix uninitialized index

- .circleci/config.yml
Resolves Issue #358 by running an apt-get update before using rosdep in the circle ci config. 
#358 
CI
> Update config.yml to run apt-get update before using rosdep

- carma-platform.repos
part of the Jira task CAR 1059, updated the .repos file to represent all the existing repos in the CARMA Platform.
The Garmin Lidar driver is added.
The repos file is tested with the vcs tool.
> added gramin driver to repos file

- plan_delegator/src/plan_delegator.cpp
Pure pursuit wrapper contains a message filter which use the timestamp of ROS messages to sync the pose, velocity and trajectory message. Without timestamp populate in the trajectory message, the trajectory message will be dropped by pure pursuit wrapper. This PR fixes #452 
#452 
Bug Fix.
Tested on Ford Fusion.
> Add timestamp in trajectory plan

- autoware_plugin/src/autoware_plugin.cpp
Update Autoware plugin capability tag in autoware_plugin.cpp to match the strategic plan capability as defined by the Arbitrator's capability interface in capabilities_interface.cpp:23: "strategic_plan/plan_maneuvers".
This resolves an issue whereby the Arbitrator wasn't able to find any plugins to query to generate strategic plans. Closes #511.
> Assign Autoware plugin correct capability tag

- carmajava/rviz/carma_default.rviz
The RVIZ profile needs to be updated to add the marker for the lanelet2 to display the vector map lanes. 
After this has been merged, please manually update the /opt/carma/rviz/ to have this new profile and use it. 
https://github.com/usdot-fhwa-stol/CARMAPlatform/issues/517
Urus Release and need to update the /opt/carma/rviz with this new profile. 
On blue lexus. 
- [ x I have added any new packages to the sonar-scanner.properties file
> updated rviz to include lanelet2 vizualization

- pure_pursuit_wrapper/launch/pure_pursuit_wrapper.launch
The pure pursuit node has a parameter which is not exposed by the launch file that is used to configure the wheel base of the vehicle. It is pointed at a non-private parameter, which does not match what carma expects. This PR adds a parameter remapping to correct this issue. 
To verify this change. Try running carma in the pacifica without the change, then try running in the pacifica with the change. You should see improved waypoint following performance. 
#333
#500 
Make CARMA waypoint following perform similar to autoware. 
On the red truck this change improved waypoint following performance. 
> Remap pure_pursuit wheel base parameter to global value

- route_generator/CMakeLists.txt
- route_generator/src/route_generator.cpp
- route_generator/test/test_route_generator.cpp
As mentioned in #549 the waypoint_loader does not work with files containing spaces in their file name. This PR adds a log statement to warn the user of this to prevent silent failure. 
Helps make the resolution of #407 more robust
Additionally, it fixes a file path in route generator unit tests that prevented them be run on any machine. 
Prevent silent failure of route loading
On local VM
> Log error on spaces in route name

- carma_wm/CMakeLists.txt
- carma_wm/include/carma_wm/WorldModel.h
- carma_wm/src/CARMAWorldModel.cpp
- carma_wm/src/CARMAWorldModel.h
- carma_wm/test/CARMAWorldModleTest.cpp
This adds a get traffic rules function to the world model which will return a CARMATrafficRules object. This is a port of functionality added in this closed PR #570 which apparently never made it back into the repo. 
#441
> Add get traffic rules to world model

- carmajava/launch/carma_src.launch
- carmajava/launch/guidance.launch
- carmajava/launch/mock_drivers.launch
Health monitor is tagged as "required" for the carma platform launch file, so upon receiving a shutdown system alert message, it will shutdown the entire carma nodes.
#460 
It will solve the problem of nodes running after the shutdown message is published.
This change has been tested on local pc with mock drivers.
> make health monitor required for carma launch

- engineering_tools/ssh_key_gen.bash
This PR adds a script ssh_key_gen.bash that will help the user setup an ssh key. It will prompt the user for a passphrase then open a browser with instructions for setting the key on github. 
This is meant to make user setup documentation a bit easier to write. 
> Added script to setup an ssh key for git

- carmajava/launch/carma_src.launch
- health_monitor/config/params.yaml
- health_monitor/launch/health_monitor.launch
- health_monitor/src/driver_manager.cpp
- health_monitor/src/entry_manager.cpp
- health_monitor/src/health_monitor.cpp
This PR is to fix health_monitor publishing incorrect state to `/system_alert` due to the bug in `carma_src.launch` and `health_monitor.launch` files. The node was directly invoked from the `carma_src.launch` file, bypassing its own health_monitor.launch file, and needed remapping of its 4 global parameters loaded from `carma-config/<vehicle-type>/VehicleConfigParams.yaml`. 
Furthermore, upon this fix, driver_timeout_ value is found to be too short that carma was incorrectly detecting operational drivers to be faulty. System alert was frequently changing from one state to another (operational, fatal, degraded etc). Therefore, its value is increase to 50000 ms as of now. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/668
This was a fix to recently added changes to health_monitor …
> Fix health_monitor cannot read correct args

- engineering_tools/carma
This change improves the robustness of the carma exec command by using a custom entrypoint and separating the behavior of the version with and without user input. 
support #658 
Allow a larger variety of commands to be run 
Tested with the following commands
```
carma exec rviz
carma exec
carma roscd cav_msgs && ls
carma exec -i usdotfhwastoldev/carma-platform:develop ls /usr/bin
```
> Update carma exec command to use more robust command resoltion

- health_monitor/src/driver_manager.cpp
- health_monitor/test/test_driver_manager.cpp
The Health monitor in develop is missing the logic or not evaluating the "s_1_l1_1_l2_1_g_0" which denotes GPS failure only.
https://github.com/usdot-fhwa-stol/carma-platform/issues/675
Unit tested
- [x ] Defect fix (non-breaking change that fixes an issue)
- [x ] I have updated the documentation accordingly.
[CARMA Contributing Guide](Contributing.md) 
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
> gps_failure

- .circleci/config.yml
- Dockerfile
- docker/checkout.sh
- docs/PULL_REQUEST_TEMPLATE.md
CI updates to allow circle to read errors from our CI scripts, and fixed link to Contributing.md in PULL_REQUEST_TEMPLATE.md
[#369](https://github.com/usdot-fhwa-stol/carma-platform/issues/369)
CircleCI is has been running successfully in spite of test failures. This was due to errors in our code coverage scripts not being passed to the CircleCI shell. This issue has been addressed by carma-base-3.7.1 release, which this PR is designed to incorporate into this repo.
Tested by breaking the test suite and confirming that Circle fails as expected.
> updated for autoware.ai-3.8.2 release and carma-base-3.7.1

- .circleci/config.yml
This PR changes the base image for CI to the dev images so that the continuous integration system will not require component releases for autoware ai repo. 
#723 
Better CI system
Passes on CI
> Change CI to use develop images

- carma_wm/src/WMListenerWorker.cpp
- carma_wm/test/WMListenerWorkerTest.cpp
- docker/checkout.bash
Fix checkout.bash script on the integration/routing branch to target correct carma-msgs branch. In addition, resolves a seg fault which was occurring in the carma_wm unit tests routeCallback test. 
Supports
https://github.com/usdot-fhwa-stol/carma-platform/issues/566
Stable integration/routing branch
CI
> Fix checkout.bash for integration/routing branch

- carmajava/launch/localization.launch
- docker/install.sh
The linked issue has many details which should be reviewed first. 
This PR improves the performance of the localization stack in CARMA Platform by utilizing the random_filter node from autoware.ai to cap the number of input points to NDT matching to a value that demonstrates a reasonable performance in terms of computation time and reliability. The current input point count is set to 700 points which is roughly 3 times what was used in 3.2.0 and about 10% of what was used in 3.3.0. While the drop from 3.3.0 is not ideal, I believe this will be mitigated by the inclusion of ground points back into the lidar scan which are used for estimating the vertical position and will likely be more useful in Aberdeen where there are fewer vertical features. The fix cap on the number of points should …
> Update localization stack to use random filter to cap NDT input

- mpc_follower_wrapper/src/mpc_follower_wrapper.cpp
The topic "trajectory_plan" in the mpc_follower_wrapper has no publisher. The trajectory executor publishes "/guidance/mpc_follower/trajectory".This is a topic mismatch. Changes the subscribed topic from "trajectory_plan" to "mpc_follower/trajectory".
#820 
The trajectory executor is publishing "mpc_follower/trajectory", not "trajectory_plan". The mismatch causes no vehicle commands.
This is been tested in the CEE simulation.
> Change trajectory_plan to mpc_follower/trajectory

- waypoint_generator/src/waypoint_generator/waypoint_generator.cpp
- waypoint_generator/test/test_waypoint_generator.cpp
Fixes errors in lane_array and get speed limt function errors in waypoint generator
and added unit tests
the main testing branch is expected to be merged into integration/routing
https://github.com/usdot-fhwa-stol/carma-platform/issues/859
during integration testing, there were numerous errors that could be caught by unit tests
unit tests pass
> add unit test for lane_array, getspeedlimits

- .sonarqube/sonar-scanner.properties
- waypoint_generator/include/waypoint_generator/waypoint_generator.hpp
- waypoint_generator/src/waypoint_generator/waypoint_generator.cpp
- waypoint_generator/test/test_route_callback.cpp
Added logic to find and eliminate adjacent lanelets in shortest path.
> add logic for successing lanelets

- carma_wm/test/WMTestLibForGuidanceTest.cpp
Two of the test cases from WMTestLibForGuidanceTest.cpp had failed after the feature/validate_speed_limits branch had been merged into develop. Unnecessary logic needed to be removed from the test cases to ensure that all unit tests pass. Specifically,  lines 256 and 279 were to be taken out to account for the changes in MapConformer.cpp
https://github.com/usdot-fhwa-stol/carma-platform/issues/902
This change is required to ensure that there are no failed test cases for any of the files on the develop branch
This has been tested using gtest/gmock.
> Commit Unit Test Fixes to WMTestLibForGuidanceTest.cpp

- carmajava/launch/guidance.launch
This PR adds parameter longitudinal limits remappings for the autoware.ai Twist Filter node to point it at the parameters loaded from the VehicleConfigParams.yaml file. 
#950 
Safer and more comfortable vehicle operation
Needs testing
> Remap twist filter longitudinal limits

- engineering_tools/carma
This script adds a new internal function to the carma script that reads the currently set carma-config to determine the best image to use. This is how the carma exec command was working and should help avoid the mismatch and redundant code to support different organizations. At the moment the change is only applied to carma config edit and carma exec. 
Supports https://github.com/usdot-fhwa-stol/carma-platform/issues/999
Make it easier to test and deploy candidate images
Locally in a VM. It is advised the peer reviewer also conduct some testing. 
> Add more maintainable image determination for carma script

- Dockerfile
rosbridge is failing because it cannot find builtin package as rosbridge was updated to require that (when we updated VTK).
https://github.com/RobotWebTools/rosbridge_suite/issues/544 (rosbridge issue)
https://github.com/usdot-fhwa-stol/carma-platform/issues/1002
rosbridge crashing at start (1-2m after start)
regression tested on pacifica
> Fix rosbridge issue

- .circleci/config.yml
- Dockerfile
- docker/checkout.bash
- docs/Release_notes.md
- gnss_ndt_selector/config/parameters.yaml
Addresses issue https://github.com/usdot-fhwa-stol/carma-platform/issues/1005 by setting the default localization mode to NDT instead of AUTO
https://github.com/usdot-fhwa-stol/carma-platform/issues/1005
More predictable localization behavior and a stable ACE demo
Mapping the parameter using docker-compose
> Default operation mode is NDT only

- route/src/route_generator_worker.cpp
Allow users to reselect the same route on the UI after getting a LEFT ROUTE event.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1057
release/vanden-plas
Local integration testing
will be tested in vehicle
> Cannot restart same route after getting LEFT ROUTE event 

- motion_computation/include/motion_computation_node.h
- motion_computation/src/motion_computation_node.cpp
See below.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1087
This PR adds back the tf2_listener missing as well as follow the instructions shown in the tf2 error message regarding lookupTransform
`Do not call canTransform or lookupTransform with a timeout unless you are using another thread for populating data. Without a dedicated thread it will always timeout. If you have a seperate thread servicing tf messages, call setUsingDedicatedThread(true) on your Buffer instance.`
Local integration tested
> Fix transform lookup develop

- hooks/pre_build
This change includes regex updates in the hooks/pre_build file in order to ensure that necessary release images are pulled and necessary repo release branches are cloned during the release image auto-build process on Docker Hub when a branch beginning with 'release/' is updated. 
This change ensures that the proper release base image(s) are pulled and the necessary repo release branches are cloned during the release image auto-build process on Docker Hub. 
This has been tested by verifying that the release/autobuild_test branch resulted in a successfully built image within the usdotfhwastolcandidate/carma-platform repository on Docker Hub. The build log associated with the auto build was checked to verify that proper release base images were pulled and necessary repo release branches were …
> Regex updates for release image auto build process.

- trajectory_executor/src/trajectory_executor/trajectory_executor.cpp
Guidance state updates were being checked against == INACTIVE which may miss some cases in which the trajectory should not be consumed. This has been fixed to check against != ENGAGED. A redundant callback (unused) that contained this logic has been removed and the correct callback has been updated with this logic.
Implements a fix in guidance state processing logic inside of the trajectory executor. Previously trajectory processing was stopped only on transition to INACTIVE. Now it is stopped on transition to any state other than ENGAGED to ensure that transitions occurring during the end of route restart process don't trigger trajectory processing (with no data) thus causing an exception to be thrown.
Potentially closes #1028
Should ensure that trajectories are not consumed outside of …
> Fix state check in guidance state callback

- localization_manager/config/parameters.yaml
This reduces the seq_timesteps required to localize from 10 to 5
> change localization parameter

- carma_wm/src/CARMAWorldModel.cpp
This pr adds a fix in getLaneletsBetween (carma_wm) which sorts the order of the output from the function, according to the shortest path.
This fix is required to correctly generate lane change paths.
> fix output order from getLaneletsBetween

- arbitrator/src/arbitrator.cpp
Adds clean shutdown handling logic for Arbitrator node to remove exception thrown in logs as part of normal shutdown procedure.
Closes #509 
Reduces confusion over state machine shutdown exception thrown during normal CARMA shutdown procedure after publication of `cav_msgs/SystemAlert` with value `FATAL`.
This has been tested to work using local CARMA development docker configuration with manual publication of `SystemAlert` messages to force a shutdown.
> Add cleaner handling for shutdown case in arbitrator

- arbitrator/src/arbitrator.cpp
Reduces CPU usage of Arbitrator prior to CARMA enable state
#1228 
Built locally and run through existing unit tests
> Add sleep to inner loop in initial state

- carma/launch/guidance.launch
There were two yield plugin launches in guidance.launch causing the launch file to fail. This removes the unused one. 
> Remove duplicate yield call

- traffic_incident_parser/include/traffic_incident_parser_worker.h
- traffic_incident_parser/src/traffic_incident_parser_worker.cpp
This PR updates the traffic incident parser node so that it will have a buffer on the position reported by the Tahoe and only forward new messages if there as been an change in the parameters or a position change of greater than 5m. 
Message processing is more robust to GPS errors
Tested in black pacifica at tfhrc
> Make new message check more robust to GPS noise

- carma/launch/guidance.launch
- port_drayage_plugin/CMakeLists.txt
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_plugin.h
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_worker.h
- port_drayage_plugin/launch/port_drayage_plugin.launch
- port_drayage_plugin/src/port_drayage_plugin.cpp
- port_drayage_plugin/src/port_drayage_worker.cpp
- port_drayage_plugin/test/test_port_drayage_plugin.cpp
This PR adds logic to port_drayage_plugin to enable it to process incoming MobilityOperation messages with strategy "carma/port_drayage". When a new MobilityOperation message of this type is received by a carma vehicle, PortDrayageWorker will check that the cmv_id within the message matches the ego vehicle's cmv_id. If the cmv_id values match, the contents of the MobilityOperation message's strategy_params field are stored in PortDrayageWorker.
This PR also applies fixes to enable the port_drayage_plugin node to launch properly and fixes some topic remapping issues.
Related PR in carma-messenger repository: [Replace encoded quotation marks in received MobilityOperation message's strategy_params field](https://github.com/usdot-fhwa-stol/carma-messenger/pull/91)
This step (receiving and …
> Add incoming MobilityOperation message processing to Port Drayage Plugin

- carma_wm/src/WMListenerWorker.cpp
- carma_wm_ctrl/src/WMBroadcaster.cpp
- route_following_plugin/src/route_following_plugin.cpp
- traffic_incident_parser/include/traffic_incident_parser_worker.h
- traffic_incident_parser/src/traffic_incident_parser_node.cpp
- traffic_incident_parser/src/traffic_incident_parser_worker.cpp
As described in the linked issue, while testing the TIM use case, the new speed advisory was not being respected. This was because the participant list from the traffic control message was not being used to populate the new geofence. Instead a more specific value was used which resulted in the new regulation not appearing to apply to the vehicle. In addition, the traffic_incident_parser was duplicating some of the control messages for the lanelet nearest the tahoe. This PR resolves both issues with the following changes.
- The participantsChecker() method in carma_wm_ctrl is used to set the participant list for speed advisory geofences. 
- The duplicated push line in traffic_incident_parser was removed
- The traffic_incident_parser was updated to have a map update queue for new …
> Resolve geofence speed limit not respected

- docker/checkout.bash
- route_following_plugin/CMakeLists.txt
- route_following_plugin/config/parameters.yaml
- route_following_plugin/include/route_following_plugin.h
- route_following_plugin/src/route_following_plugin.cpp
- route_following_plugin/test/test_route_following_plugin.cpp
This PR refactors the route following plugin to be more simplistic is forming maneuver plans.
In this implementation the maneuver planning is done as a call back when the route is set. Following that the maneuvers are added to the response when a request is sent. 
The time, starting distance and starting speed values are updated each time the plan is added to the response.
This change is needed to allow lane change maneuvers to be formed correctly in between lane following maneuvers.
The code was unit tested.
> refactor route following

- Dockerfile
- route/src/route_generator_worker.cpp
A minor update is made to the logic in RouteGeneratorWorker's spin_callback() method in order to assign a name to the route_name field of the cav_msgs/Route.msg message that is published after successful rerouting due to a route invalidation. By assigning a route name, the `if(route_msg_.route_name != "")` downstream check  will be successful, which will enable messages to continue to be published to the /guidance/route_state topic.
Issue #1306: /guidance/route_state stops publishing after a carma3/Incident_Use_Case MobilityOperation message is received and processed. 
With this fix, after successful rerouting due to route invalidation, messages will continue to be published to /guidance/route_state.
Integration tested on Blue Lexus with zephyr release. …
> Assign route_name field to route message published after rerouting due to route invalidation

- carma-platform.repos
Personal repositories were used during the port to ROS Noetic.
> Remove references to personal repos now that code has been integrated

- cooperative_lanechange/package.xml
- lightbar_manager/package.xml
- mock_drivers/mock_lightbar_driver/package.xml
- mock_drivers/rosbag_mock_drivers/package.xml
- platooning_control/package.xml
- port_drayage_plugin/package.xml
- pure_pursuit_jerk_wrapper/package.xml
- route_following_plugin/package.xml
Update remaining packages that had package format version 2 to version 3 and address any xmllint issues when testing against the package format v3 schema (typically just reordering items).
> Update to package format 3 and run xmllint

- guidance/src/guidance/guidance_state_machine.cpp
- guidance/test/test_guidance_state_machine.cpp
The lanelet2 upgrade required upgrading some parts of the autoware_msgs. These changes reflect this change in message definitions.
Changed how the guidance nodes and tests reference the gear.
Needed to complete the lanelet2 upgrade.
Ran the unit tests for the guidance package. All tests passed.
> Update carma packages to use newer version of autoware_msgs

- inlanecruising_plugin/src/inlanecruising_plugin.cpp
- route_following_plugin/src/route_following_plugin.cpp
This PR fixes bugs in route_following_plugin and inlanecruising_plugin which gives above error in title. It was found during platooning test. route_following_plugin's bug was introduced in recent lane_change PR, and inlanecruising_plugin is needed as without it, buffer_ending_downtrack would not do anything.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1347
See above.
integration tested at ACM
> Fix ILC "no points to fit in time span" exception

- docker/checkout.bash
This PR updates the checkout.bash script to by default point at noetic/develop to support CI usage. 
The need for this change does point to a fundamental flaw in the checkout.bash script since it effectively renders the -d argument meaningless. 
Working CI on noetic branch
Running ci here
> Update checkout.bash to work with CI properly

- docker/checkout.bash
Resets the carma-msgs dependency to reference the develop version now that the platooning branches are being merged.
N/a
Procedural change now that branches are being merged back into develop
N/a
> Revert carma-msgs to develop branch status

- platooning_control/include/platoon_control_worker.hpp
- platooning_control/src/platoon_control_worker.cpp
Platoonin last control command initialized as current speed, so enable speed transition and gap control more smooth.
integration tested in Black Pacifica
> fix for accurate platoon gap control

- intersection_transit_maneuvering/src/intersection_transit_maneuvering.cpp
- platooning_strategic/src/platoon_strategic.cpp
- platooning_tactical_plugin/src/platooning_tactical_plugin.cpp
- platooning_tactical_plugin/test/test_platooning_tactical_plugin_planning.cpp
- port_drayage_plugin/src/port_drayage_plugin.cpp
- route_following_plugin/src/route_following_plugin.cpp
- route_following_plugin/test/test_route_following_plugin.cpp
- stop_and_wait_plugin/test/test_stopandwait_plugin.cpp
There is a typo in both carma-platform and carma-msgs where the ManeuverParameters.msg value "negotiation_type" is incorrectly spelled as "neogition_type" in multiple files.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1371
This change is to ensure that msg file values are correctly listed to avoid confusion.
> Fix typo in intersection_transit_maneuvering.cpp

- pose_to_tf/config/parameters.yaml
This PR fixes the string values for the frame IDs used in the `pose_to_tf` package. The previous string values contained extra characters that, when parsed, would result in incorrect frame IDs. The `base_link` frame ID would be parsed as `= "base_link";`, and the `map` frame would be `= "map";`.
Fixes #1387 for the `develop` branch.
The incorrect syntax would create unique, but incorrect, frame IDs and prevent the transform from being broadcast to the expected IDs.
The proposed changes have been tested on the C1T vehicle.
> Fix parameter strings for `pose_to_tf` parameter file (`develop`)

- docker/install.sh
- platooning_strategic/CMakeLists.txt
- platooning_strategic/include/platoon_manager.h
- platooning_strategic/include/platoon_strategic.h
- traffic_incident_parser/CMakeLists.txt
- truck_inspection_client/CMakeLists.txt
- truck_inspection_client/include/truck_inspection_client.h
Recent sync with 3.7 seems to have introduced some build errors in noetic/develop. This PR resolves them. 
The root cause was incorrectly imported Boost deps that were hidden by catkin_make. 
Local Build testing
> Fix invalid build errors

- cooperative_lanechange/src/cooperative_lanechange.cpp
- docs/Release_notes.md
At the end of lanechange (made by cooperative lanechange) the car makes a slightly random steering before going into route following mode. 
It appeared as if the pure pursuit was dropping carma_final_points although they are visualized on rviz by trajectory_points topic. This was due to the fact that there was a duplicate point (very close) at the end of the cooperative lanechange which was resulting in almost 0 time_diff which the pure pursuit was rejecting as a duplicate point. 
Resolves https://github.com/usdot-fhwa-stol/carma-platform/issues/1428
See above.
Tested on black pacifica at ACM
> Incorrect steering at the end of cooperative lanechange

- arbitrator/config/arbitrator_params.yaml
- arbitrator/src/fixed_priority_cost_function.cpp
- carma/launch/guidance.launch
- carma_wm/include/carma_wm/IndexedDistanceMap.h
- carma_wm/src/CARMAWorldModel.cpp
- carma_wm/src/IndexedDistanceMap.cpp
- docker/checkout.bash
- inlanecruising_plugin/src/inlanecruising_plugin.cpp
- mobilitypath_visualizer/src/mobilitypath_visualizer.cpp
- platooning_control/src/platoon_control.cpp
- stop_and_wait_plugin/src/stop_and_wait_plugin.cpp
- wz_strategic_plugin/src/wz_strategic_plugin.cpp
Fixes encountered duing a1 verification testing, which includes:
- mobilitypath_visualizer no longer runs into race condition where it fails before map is available
- stop_and_wait_plugin no longer creates "steering right" trajectory due to bug in the way points were being sampled from route. it was comparing traveled downtrack bs lanelet's downtrack percentage to get the nearest point, which is incorrect. It directly compares downtrack using binary search now.
- inlanecruising_plugin as plugin name field
- platooning stack no longer crashes during workzone test run.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1444
See above.
Integration tested on Blue Lexus
> a1 release verification testing fixes

- platooning_strategic/src/platoon_strategic.cpp
During workzone testing, platooning plugin received new type of maneuver other than lane_follow, which resulted in the plugin crashing. This is fixed by return empty trajectory if not supported as it is not used.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1451 Definitely related to this.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1456 Most likely will fix this as well, the exact issue was not reproducible
See above
At TFHRC using Fusion
> Fix for platoon shutdown during workzone run

- basic_autonomy/CMakeLists.txt
- basic_autonomy/include/basic_autonomy/helper_functions.h
- basic_autonomy/include/basic_autonomy/log/log.h
- basic_autonomy/include/basic_autonomy/smoothing/BSpline.h
- basic_autonomy/include/basic_autonomy/smoothing/filters.h
- basic_autonomy/src/basic_autonomy.cpp
- basic_autonomy/src/log/log.cpp
- basic_autonomy/src/smoothing/BSpline.cpp
- basic_autonomy/src/smoothing/filters.cpp
- inlanecruising_plugin/CMakeLists.txt
- inlanecruising_plugin/include/inlanecruising_plugin/inlanecruising_config.h
- inlanecruising_plugin/include/inlanecruising_plugin/inlanecruising_plugin.h
- inlanecruising_plugin/include/inlanecruising_plugin/inlanecruising_plugin_node.h
- inlanecruising_plugin/include/inlanecruising_plugin/log/log.h
- inlanecruising_plugin/include/inlanecruising_plugin/smoothing/BSpline.h
- inlanecruising_plugin/include/inlanecruising_plugin/smoothing/SplineI.h
- inlanecruising_plugin/include/inlanecruising_plugin/smoothing/filters.h
- inlanecruising_plugin/launch/inlanecruising_plugin.launch
- inlanecruising_plugin/package.xml
- inlanecruising_plugin/src/inlanecruising_plugin.cpp
- inlanecruising_plugin/src/main.cpp
- inlanecruising_plugin/src/smoothing/BSpline.cpp
- inlanecruising_plugin/test/test_inlanecruising_plugin.cpp
- inlanecruising_plugin/test/test_inlanecruising_plugin_planning.cpp
This PR reverts inlanecruising_plugin to the version from 3.7.2 after it was found the basic_autonomy refactor for that component introduced numerous bugs. Additionally, this PR fixes numerous linker errors in basic_autonomy caused by non-inline free functions in header files which resulted in duplicate compilation unit declarations on linkage to that library. 
https://github.com/usdot-fhwa-stol/carma-platform/issues/1461
Functional workzone use case
Black Pacifica at TFHRC both east and west bound WZ use case. 
> Revert inlanecruising to 3.7.2 and fix build errors from basic_autonomy

- sci_strategic_plugin/config/parameters.yaml
- sci_strategic_plugin/include/sci_strategic_plugin.h
- sci_strategic_plugin/include/sci_strategic_plugin_config.h
- sci_strategic_plugin/src/main.cpp
- sci_strategic_plugin/src/sci_strategic_plugin.cpp
- sci_strategic_plugin/test/test_sci_strategic_plugin.cpp
- sci_strategic_plugin/test/test_strategic_plugin.cpp
Add intersection departure logic to the stop-controlled intersection strategic plugin. The scheduled times for entering and departing the intersection are received from CARMA Streets and maneuvers are composed according to those times, as well as specifications of the intersection such as speed limit and stop line position.
> add intersection departure logic

- basic_autonomy/src/basic_autonomy.cpp
Fix for input vector is empty exception thrown at the end of a lanechange.
The method proposed adds centerline points from the lanelet following the last lanelet in lane change.
Issue #1507
> add additional centerline points for lc buffer

- port_drayage_plugin/config/params.yml
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_worker.h
- port_drayage_plugin/src/port_drayage_plugin.cpp
- port_drayage_plugin/src/port_drayage_worker.cpp
- port_drayage_plugin/test/test_port_drayage_plugin.cpp
This PR update port_drayage_plugin to set its cmv_id using the 'vehicle_id' global parameter, which includes the vehicle's license plate information. As part of this update, cmv_id within port_drayage_plugin has been changed from an unsigned long to a string. Similarly, V2XHub expects cmv_id to be a string value.
Built and tested locally with development config; also unit tested.
> Set cmv_id in port_drayage_plugin to vehicle_id parameter

- basic_autonomy/src/basic_autonomy.cpp
It seems that when the route end stopping maneuver is shorter than the buffer distance used by inlane-cruising the buffer could be cut short due to a check in basic_autonomy's add_lanefollow_buffer method. This check appears to be unnecessary and has been removed to hopefully prevent exceptions related to lack of points occuring. 
Hopefully will fix https://github.com/usdot-fhwa-stol/carma-platform/issues/1539
More stable lane following and successful Battista release and testing. 
It has not been. TEST ON TRUCKS
> Allow buffered points to extend beyond the end of the route

- platooning_strategic_IHP/include/platoon_strategic_ihp.h
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Several small changes to platooning IHP strategic plugin:
* Fixed mob_op_cb_leader() to properly use target platoon's rear location to determine if target platoon is in front of host (was using front vehicle DTD)
* mob_op_cb_leader() was trying to use pm_ info to get target platoon rear, but pm_ refers to the host, not the target platoon.
* Fixed run_leader() to only publish INFO messages if vehicle is in motion.
* Fixed mob_op_cb() and mob_req_cb() to ignore any incoming messages if vehicle is not in motion.  This will prevent generation of mob_req or mob_resp messages or anything else to begin forming a platoon while stopped.
* Fixed mob_op_cb() and mob_req_cb() to ignore any incoming messages that aren't tagged with the platooning strategy.  Testing on 12/22 was occurring while another …
> IHP2 integration test improvements from 12/22 final run

- carma/launch/carma_src.launch.py
- carma/launch/message.launch.py
This PR adds a skeleton launch file for v2x subsystem nodes for ROS2
Supports https://github.com/usdot-fhwa-stol/carma-platform/issues/1580
Consistent launch structure
Runs locally
> Add message.launch.py to carma ros2 launch

- sci_strategic_plugin/config/parameters.yaml
Acc/Dec multipliers and stopping buffer are tuned for smooth and reliable stopping.
Integration tested on Black Pacifica, White Fusion and Blue Lexus.
> tuned param for stopping

- route/src/route.cpp
This PR fixes a mis-match between the 'cte_max_count' parameter in the Route package's configuration file, and the parameter name used to access it in the package's route.cpp file. With this change, the Route package now uses the config file parameter value, rather than the value of an uninitialized integer.
Issue #1608 
Tested on the Red Truck at ATEF.
> Fix name for Route package's 'cte_max_count' parameter

- plan_delegator/src/plan_delegator.cpp
This PR includes an update to plan_delegator by updating the starting and ending downtracks of each maneuver in a received maneuver plan only once (at the moment the maneuver plan is received). Previously, the starting and ending downtracks of each maneuver were being updated with each spin/tick of plan_delegator, causing the starting and ending downtracks of each maneuver to be repeatedly decreased. 
Prior to this fix, the CARMA System came to a stop too early at the end of its route, and steering was jerky in curves.
Tested on the White Truck at ATEF.
> Fix applied update to maneuver downtracks

- platooning_control/include/platoon_control.h
- platooning_control/include/platoon_control_config.h
- platooning_control/src/platoon_control.cpp
Enhanced the platooning control plugin to cooperate with other control plugins to accommodate the fact that all control plugins publish their output on a common ros topic, and this topic is only intended to carry data from a single controller at a time.  When trajectory executor switches from one control plugin to another, we want the old one to stop publishing.  However, it needs to wait some amount of time since it is spinning faster than the producer of its input trajectory data. Since this input data is not guaranteed to arrive at a precise interval, the control plugin needs to wait for a conservative timeout period before deciding that the input stream has dried up.
Note: architecture documentation is to be updated at a later time.
PR #1647 
Ensures a control plugin stops publishing …
> Platooning control plugin handles control switchover

- platooning_control/include/platoon_control.h
- platooning_control/src/platoon_control.cpp
After modifications to the Platooning Control Plugin to publish control signals at 30 hz, we noticed the vehicle doesn't move because the timer callback is never called. So some fixed and additional logs are added to this plugin.
PR #1647
> Update platooning control plugin control timer

- carma_wm_ctrl/include/carma_wm_ctrl/WMBroadcaster.h
- carma_wm_ctrl/src/WMBroadcaster.cpp
- carma_wm_ctrl/src/WMBroadcasterNode.cpp
The UI should be subscribing to a topic that provides the SPAT messages in order to showcase the phase and timing of the traffic signals at TFHRC.
CARMA Web UI - Traffic signal phase and timing display not working
NA
> CARMA Web UI - Traffic signal phase and timing display not working

- basic_autonomy/src/basic_autonomy.cpp
- cooperative_lanechange/include/cooperative_lanechange.h
- cooperative_lanechange/src/cooperative_lanechange.cpp
This PR includes two fixes in cooperative_lanechange and basic_autonomy to address issues with lane change trajectories:
- Fixes in basic_autonomy constrain the first trajectory plan point to use the received vehicle state (position, longitudinal speed, and orientation). This ensures that a proper target_time is assigned to the first lane change trajectory plan point in order to match the intended vehicle speed.
- Fixes in cooperative_lanechange enable CooperativeLaneChangePlugin to store the original start_dist and starting_lane_id of each received lane change maneuver. Each time a trajectory is planned for a lane change maneuver, it's original start_dist and starting_lane_id is now used. Prior to this fix, the start_dist and the starting_lane_id could change mid-lanechange for lane …
> Lane change trajectory fixes

- carma_wm_ctrl/CMakeLists.txt
- carma_wm_ctrl/config/parameters.yaml
- carma_wm_ctrl/launch/carma_wm_broadcaster.launch
Add configuration parameters.yaml file.
Update the current configuration params to get the values from the parameters.yaml file
remap topic outgoing_geofence_ack to outgoing_mobility_operation message
NA
Freight testing
NA
> Configure the acknowledgement of geofence updates for CMV's

- cooperative_lanechange/src/cooperative_lanechange.cpp
This PR includes an update to cooperative_lanechange in which the trajectory plan request's vehicle_state.longitudinal_vel value is only updated to the vehicle initial lane change velocity if the vehicle has started the specific lane change. Prior to this fix, the vehicle_state.longitudinal_vel for lane change trajectory requests that had not yet been started were being updated to a value of 0. 
Built and tested on the Silver Truck at Suntrax.
> Only update a lane change trajectory request's vehicle state speed after vehicle has started the lane change

- lci_strategic_plugin/config/parameters.yaml
- lci_strategic_plugin/src/lci_strategic_plugin.cpp
- lci_strategic_plugin/src/lci_strategic_plugin_algo.cpp
When vehicle starts from STOPPING range, it hasn't saved the intersection variables so it throws exception. 
Also if condition still had python syntax which gives wrong results
TSMO UC2 testing
not yet
> fix py eq and inters var

- lci_strategic_plugin/src/lci_strategic_plugin.cpp
- light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin.cpp
- pure_pursuit_wrapper/src/pure_pursuit_wrapper.cpp
1)
Whenever we are checking limits of the resulting applied speeds in each points, it checks min or max of algo_min and algo_max or speed_limits in general.
When providing the speed_limit, current code has artifact from previous version where it uses wrong speed_limit. 
speed_limit is extracted from lanelet and saves as an internal variable.
Bug seen was in LCI_Tactical, there was line "applied speed: -nan", which can only say that if p.speed was -nan from the logs as algo_min and algo_max were valid numbers. 
2)
When the vehicle is able to calculate 1-7 case, but not able to make it due to green buffer, vehicle should be defaulting to case8 (currently in our test cases) but when it is doing that, it is using previous 1-7 case params when executing that scenario. This is fixed now by …
> fix nan in lci_tactical_plugin and lci_strat edge case

- lci_strategic_plugin/src/lci_strategic_plugin_algo.cpp
There was an issue of "Duration is out of 32bit" when testing "Long 8 case" as we internally call it. Essentially there is a bug in the equation that gives negative time numbers.
TSMO UC2
Not yet
> added logic fix

- system_controller/include/system_controller/system_controller_node.hpp
- system_controller/src/system_controller_node.cpp
This PR updates the system_controller to publish a SHUTDOWN system alert on subsystem failure such that the ROS1 nodes will shutdown if the ros2 system shutsdown. 
Supports resolution of https://github.com/usdot-fhwa-stol/carma-platform/issues/1702
Reliable shutdown behavior
Tested on silver lexus with lidar to gps failover
> Update system_controller to publish alert for ROS1 nodes

- light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin.cpp
This pr updates a call to the basic_autonomy library for creating a lanefollow trajectory. The function in basic_autonomy was updated to not require the ending_state_before_buffer, because it was never being used in the function.
So this update shouldn't change the logic here either.
Unit tests still pass
> fix basic_autonomy function call

- gnss_to_map_convertor/include/gnss_to_map_convertor/gnss_to_map_convertor_node.hpp
- gnss_to_map_convertor/src/gnss_to_map_convertor_node.cpp
Fixes an issue where the gnss_to_map_convertor crashes because its worker class goes out of scope while subscribing to topics.
Locally launched the node and published a topic that this node subscribes to. The node doesn't crash with this change set.
> create shared_ptr to worker

- carma/launch/environment.launch.py
- motion_computation/config/parameters.yaml
- motion_computation/src/motion_computation_worker.cpp
Fixes an error in motion computation that caused external object lists to reference uninitialized indices. And adds topic remaps for incoming message topics.
Locally integration tested
> fix list sync and add remaps motion_computation

- platooning_strategic_IHP/include/platoon_manager_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Fleshed out logic where aborts are needed to better clean up the records of platooning info (e.g. the roster of members).
Aborted platoon attempts leave the records in an untidy state and make it unclear what is happening.
Local build of package.
> Added a few cleanups where logic needs to abort.

- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
Platooning strategic IHP plugin is updated so that when a front joiner vehicle rejects a follower join request, it should return to leader state as a solo vehicle. 
> front joiner state change

- object_visualizer/src/object_visualizer_node.cpp
This PR fixes issue #1765 
The fix here is to delete all external object markers before publishing a new list of external objects to rviz.
> clear markers before publishing new ones

- lci_strategic_plugin/config/parameters.yaml
This PR removes an extra indent in the configuration file for lci strategic plugin that causes carma-platform to crash.
> remove extra indent

- platooning_strategic_IHP/config/parameters.yaml
- platooning_strategic_IHP/include/platoon_config_ihp.h
- platooning_strategic_IHP/include/platoon_manager_ihp.h
- platooning_strategic_IHP/include/platoon_strategic_plugin_node_ihp.h
- platooning_strategic_IHP/src/platoon_manager_ihp.cpp
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
IHP strategic plugin is updated to calculate the gap with dynamic leader, in case there are multiple vehcles are in between.
> Update IHP platoon gap calculation with multiple vehciles in between

- docker/checkout.bash
- platooning_control/include/platoon_control.h
- platooning_control/include/platoon_control_worker.h
- platooning_control/src/platoon_control.cpp
- platooning_control/src/platoon_control_worker.cpp
- platooning_control/test/test_worker.cpp
- platooning_strategic/include/platoon_strategic.h
- platooning_strategic/src/platoon_strategic.cpp
**NOTE**: This is a PR for the test/master_voices carma-platform branch, which is branched off of CARMA System 3.11.0
For a CARMA Platform vehicle to perform properly in a CARLA Simulation, the control commands published to /guidance/ctrl_raw must include an acceleration command (in addition to a speed and a steering command). Prior to this PR, the platooning_control guidance plugin only outputted speed and steering commands to this topic.
In addition to this, a small bug fix was applied to platoon_strategic.cpp in order to correctly set the host vehicle's current downtrack distance in the class' platoon_manager object. 
All new and existing unit tests pass; carma-platform image integration tested successfully with full run-through of three-vehicle platoon as part of VOICES test with …
> Add logic to platooning_control for outputting acceleration commands

- carma/CMakeLists.txt
This PR fixes an error within the carma package, which causes a build failure. The 'ui' directory within carma was recently removed, but it is still referenced in the package's CMakeLists. This PR removes those references.
Issue #1900 
carma package was successfully built locally with these updates
> Fix carma package build error

- basic_autonomy/src/basic_autonomy.cpp
- basic_autonomy_ros2/src/basic_autonomy.cpp
This PR is a fix for issue #1908 where some tactical plugins take longer to generate a trajectory, causing the service request from plan_delegator to time out without any response.
This was caused because sometimes the number of points used to calculate a spline fit is large, which contributes to the delay. Therefore, the number of points used to calculate the spline is limited to a reasonable value that is large enough to include most of the points, but small enough that the spline calculations are done in time. 
#1908 
Integration tested on Blue Lexus
> optimize tactical plugin trajectory generation

- .sonarqube/sonar-scanner.properties
- carma_cloud_client/CMakeLists.txt
- carma_cloud_client/README.md
- carma_cloud_client/config/parameters.yaml
- carma_cloud_client/include/carma_cloud_client/carma_cloud_client_config.hpp
- carma_cloud_client/include/carma_cloud_client/carma_cloud_client_node.hpp
- carma_cloud_client/launch/carma_cloud_client_launch.py
- carma_cloud_client/package.xml
- carma_cloud_client/src/carma_cloud_client_node.cpp
- carma_cloud_client/src/main.cpp
- carma_cloud_client/test/node_test.cpp
Create a carma_cloud_client ROS2 node in carma-platform. The functionalities for the carma_cloud_client ROS node below:
- Subscribe to carma_wm_ctrl node to get the TCR data. 
- Create a HTTP client and send a TCR post request to carma-cloud. TCR is in XML format. 
#1965 
Unit tested and locally integration tested
> create carma cloud client

- lci_strategic_plugin/include/lci_strategic_plugin/lci_strategic_plugin.h
- lci_strategic_plugin/src/lci_strategic_plugin.cpp
It was requested to add which intersection the status and intent messages are being broadcasted for from carma-platform during UC3.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1962
> Add intersection data broadcasted by carma-platform

- docker/build-image.sh
- docker/install.sh
The incremental build flags --ros1 and --ros2 are now able to be supplied in any order and multiple times
build-image.sh --ros2 ... --ros1, build-image.sh --ros1 ... --ros2, and build-image.sh --ros1 ... --ros1
are all now supported and should result in the specified packages being built correctly.
Once this change is approved, I will need to mirror this change on all other repos for consistency.
This PR addresses part of the issue #1960 , specifically the issue pertaining to the order in which build arguments are supplied. The other reported part of the issue has not yet been reproduced and is not addressed here. 
Fixes an unecessary restriction on the order in which build arguments could be passed to the incremental build process, which would cause a build failure without warning if …
> Fix argument ordering restrictions for --ros1 and --ros2

- carma/launch/plugins.launch.py
Isolating plugins in plugins.launch,py in hopes to reduce failures of service calls. Please see the issue for more details.
https://github.com/usdot-fhwa-stol/carma-platform/issues/1996
UC3 integration testing
local integration tested to see if the plugins don't crash
> Isolate plugins

- carma/launch/carma_src.launch.py
- carma/launch/message.launch.py
Opening HTTP tunnels to CARMA Cloud can be enabled and disabled using a Flag in CARMA Config
> enable and disable opening tunnels

- carma/launch/message.launch.py
The remote port for cellular communication with carma cloud is updated to allow better communication.
#2021 
Previously, both host and remote ports were set to the same value, and although it worked initially, a TCM was not being received by CARMA vehicle from CARMA cloud during isetta candidate verification tests.
With the new remote port, TCMs are successfully received.
Integration tested with Blue Lexus and Black Pacifica
> cellular port change

- lci_strategic_plugin/src/lci_strategic_plugin.cpp
There is a math bug when calculating time to stop during UC3.
UC3 verification testing
N/A
> fix bug of emergency deceleration

- plan_delegator/config/plan_delegator_params.yaml
- plan_delegator/include/plan_delegator.hpp
- plan_delegator/src/plan_delegator.cpp
This PR updates the timeout value of plan_delegator's service call to a tactical plugin's "plan_trajectory" service to be a configurable parameter. Originally, this value was hardcoded to be 100 ms; however, it has been found during integration testing at Suntrax that lane change trajectories can occasionally take longer than this. A recent PR #2074 speeds up the lane change trajectory generation considerably, but occasionally a lane change of longer length (greater than 50 meters) can still take longer than 100 ms. 
This PR makes it possible to increase the timeout duration when testing is conducted using a vector map or test environment with longer lanelet lengths (which correlates to longer lane change trajectory generation time). With this update, the timeout duration can be increased …
> Make plan_delegator's plan trajectory service call timeout value a configurable parameter

- approaching_emergency_vehicle_plugin/src/approaching_emergency_vehicle_plugin_node.cpp
TODO
This hotfix corrects an issue within carma-platforms approaching_emergency_vehicle_plugin. Prior to this fix, if an approaching ERV was not passing the host vehicle in less than `config_.approaching_threshold`, the ERV's `seconds_until_passing` was updated to 0.0 seconds. With this fix, the ERV's `seconds_until_passing` will maintain its estimated value when it is greater than the approaching threshold.
Fixes bug that triggers the host vehicle to transition to the `SLOWING_DOWN_FOR_ERV` state since the ERV's seconds_until_passing is updated to 0.0 seconds when the ERV is a significant distance away from the CMV.
Integration tested on the White Truck at Suntrax with ERV interactions.
> Fix to  maintain original estimated 'seconds until passing' for approaching ERV when it is far away from host vehicle

- approaching_emergency_vehicle_plugin/include/approaching_emergency_vehicle_plugin/approaching_emergency_vehicle_plugin_node.hpp
- approaching_emergency_vehicle_plugin/src/approaching_emergency_vehicle_plugin_node.cpp
- approaching_emergency_vehicle_plugin/test/test_approaching_erv.cpp
This PR includes a fix in approaching_emergency_vehicle_plugin in order to limit the frequency at which BSMs from non-approaching active Emergency Response Vehicles are processed by the plugin. Due to the amount of processing involved on these BSMs, in rare circumstances (due to the CARMA Platform computer reaching computational limits), it is possible that the BSMs cannot be processed at 10 Hz. This fix enables the BSMs from these vehicles to be processed in accordance with the plugin's `bsm_processing_frequency` configuration parameter
Issue #2104 
Unit tested and integration tested as part of Emergency Response test scenarios with the Silver Truck and Chevy Tahoe (ERV) at Suntrax.
> Hotfix - Update BSM processing frequency for BSMs received from non-approaching active Emergency Response Vehicles

- carma/launch/plugins.launch.py
- lci_strategic_plugin/src/lci_strategic_plugin.cpp
This PR fixes an issue in the lci strategic plugin where the node fails to load parameters from the vehicle calibration directory.
> Hotfix lci param loading

- carma_cooperative_perception/CMakeLists.txt
- carma_cooperative_perception/docs/package_design.md
- carma_cooperative_perception/docs/track_list_to_external_object_list_node.md
- carma_cooperative_perception/include/carma_cooperative_perception/msg_conversion.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/track_list_to_external_object_list_component.hpp
- carma_cooperative_perception/package.xml
- carma_cooperative_perception/src/msg_conversion.cpp
- carma_cooperative_perception/src/track_list_to_external_object_list_component.cpp
- carma_cooperative_perception/src/track_list_to_external_object_list_node.cpp
- carma_cooperative_perception/test/data/track_list.yaml
- carma_cooperative_perception/test/test_msg_conversion.cpp
- carma_cooperative_perception/test/track_list_to_external_object_list_launch_test.py
This PR adds a ROS 2 Node that converts incoming `carma_cooperative_perception_interfaces/msg/TrackList.msg` messages into `carma_perception_msgs/msg/ExternalObjectList.msg` ones. This conversion Node is necessary because the rest of CARMA Platform uses a different message format than the cooperative perception stack uses internally.
Closes #2158
[CDAR-253](https://usdot-carma.atlassian.net/browse/CDAR-253)
See description
- Unit tests for the message conversion functions
- a launch test for the conversion Node
[CDAR-253]: https://usdot-carma.atlassian.net/browse/CDAR-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add ROS 2 Node for converting TrackList messages to ExternalObjectList messages

- carma_cooperative_perception/CMakeLists.txt
- carma_cooperative_perception/config/params.yaml
- carma_cooperative_perception/docs/host_vehicle_filter_node.md
- carma_cooperative_perception/include/carma_cooperative_perception/host_vehicle_filter_component.hpp
- carma_cooperative_perception/launch/cooperative_perception_launch.py
- carma_cooperative_perception/src/host_vehicle_filter_component.cpp
- carma_cooperative_perception/src/host_vehicle_filter_node.cpp
- carma_cooperative_perception/test/data/detection_list.yaml
- carma_cooperative_perception/test/host_vehicle_filter_launch_test.py
This PR introduces a new Node in the cooperative perception stack to remove any incoming detections that likely represent the host vehicle. Detections are removed based on a configurable distance threshold from the host vehicle's current pose.
Closes #2182
Closes [CDAR-420](https://usdot-carma.atlassian.net/browse/CDAR-420)
If we don't remove detections that are associated with the host vehicle's current pose, then it will appear that we are always colliding with an external object.
[CDAR-420]: https://usdot-carma.atlassian.net/browse/CDAR-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Add host vehicle filter node

- arbitrator/include/arbitrator.hpp
- arbitrator/include/arbitrator_config.hpp
- arbitrator/include/capabilities_interface.hpp
- arbitrator/include/capabilities_interface.tpp
- arbitrator/include/cost_function.hpp
- arbitrator/include/cost_system_cost_function.hpp
- arbitrator/include/fixed_priority_cost_function.hpp
- arbitrator/include/planning_strategy.hpp
- arbitrator/include/plugin_neighbor_generator.hpp
- arbitrator/include/tree_planner.hpp
- arbitrator/src/arbitrator.cpp
- arbitrator/src/arbitrator_node.cpp
The `try...catch` block should catch any RCL-related issues when the `CapabilitiesInterface` instance tries to create a ROS 2 service client but fails. It is unclear why the DDS implementation sometimes throws an error when attempting to create a ROS 2 service client, but this at least prevents the arbitrator from shutting donw.
Closes #2193 
Closes [CDAR-502](https://usdot-carma.atlassian.net/browse/CDAR-502)
When using the Fast DDS RMW implementation, the `CapabilitiesInterface` would sometimes fail to create a service client, causing the arbitrator node to shut down due to an uncaught exception.
Manually tested with XiL environment
[CDAR-502]: https://usdot-carma.atlassian.net/browse/CDAR-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add try/catch block around client creation

- carma/launch/environment.launch.py
- carma_cooperative_perception/CMakeLists.txt
- carma_cooperative_perception/config/cp_host_vehicle_filter_node.yaml
- carma_cooperative_perception/config/cp_multiple_object_tracker_node.yaml
- carma_cooperative_perception/config/params.yaml
- carma_cooperative_perception/docs/host_vehicle_filter_node.md
- carma_cooperative_perception/include/carma_cooperative_perception/host_vehicle_filter_component.hpp
- carma_cooperative_perception/src/host_vehicle_filter_component.cpp
- carma_cooperative_perception/src/track_list_to_external_object_list_component.cpp
- carma_cooperative_perception/test/host_vehicle_filter_launch_test.py
This PR launches the cp nodes in carma-platform and connects the topics. Resulting nodes and topic connections look as follows, now:
<pre>carma@ubuntu:/$ ros2 lifecycle get | grep environment
1700556814.607293 [0]       ros2: using network interface ens33 (udp/192.168.1.159) selected arbitrarily from: ens33, docker0
/environment/bounding_box_converter: active [3]
/environment/carma_wm_broadcaster: active [3]
/environment/cp_external_object_list_to_detection_list_node: active [3]
/environment/cp_external_object_list_to_sdsm_node: active [3]
/environment/cp_host_vehicle_filter_node: active [3]
/environment/cp_multiple_object_tracker_node: active [3]
/environment/cp_sdsm_to_detection_list_node: active [3]
/environment/cp_track_list_to_external_object_list_node: active [3] …
> Launch cooperative perception nodes

- carma_cooperative_perception/include/carma_cooperative_perception/msg_conversion.hpp
- carma_cooperative_perception/src/external_object_list_to_detection_list_component.cpp
- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
The default motion model mapping values were specified in the ROS parameter declarations, but this meant the `MotionModelMapper` instance never got them. Its values wouldn't be updated unless a user changed them. Now, the default values are stored in the class instance, and the ROS parameter declarations get their default values from the instance.
Closes #2202 
Closes [CDAR-531](https://usdot-carma.atlassian.net/browse/CDAR-531)
See above
[CDAR-531]: https://usdot-carma.atlassian.net/browse/CDAR-531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Move motion model mapping default values to `MotionModelMapping` class

- carma/launch/environment.launch.py
This PR fixes the `georeference` topic name remapping for two of the carma cooperative perception nodes.
Closes #2205
Closes [CDAR-546](https://usdot-carma.atlassian.net/browse/CDAR-546)
This error prevented the nodes from getting georeference updates.
Manually tested.
[CDAR-546]: https://usdot-carma.atlassian.net/browse/CDAR-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix georeference topic name remapping for carma cooperative perception nodes

- carma_cooperative_perception/include/carma_cooperative_perception/msg_conversion.hpp
- carma_cooperative_perception/src/external_object_list_to_detection_list_component.cpp
- carma_cooperative_perception/src/host_vehicle_filter_component.cpp
This PR removes the UTM zone conversions from the `ExternalObjectListToDetectionListNode`. Incoming detections use the map frame, and CARMA uses the map frame, so there is not point in converting to UTM then back to map.
Closes #2204
Closes [CDAR-545](https://usdot-carma.atlassian.net/browse/CDAR-545)
This node was converting incoming detections to CARMA's current UTM zone, but the rest of CARMA uses the map frame, meaning we would have to do an unnecessary conversion back to the map frame.
Manually tested. Unit tests.
[CDAR-545]: https://usdot-carma.atlassian.net/browse/CDAR-545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove conversion to UTM zone

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR modifies the `MultipleObjectTrackerComponent` to use incoming detections' actual covariance matrix values instead of the zero matrix.
Closes #2215 
Closes [CDAR-605](https://usdot-carma.atlassian.net/browse/CDAR-605)
Using the incorrect covariance matrix will lead to tracking errors. Using the zero matrix leads to tracking system crashes.
[CDAR-605]: https://usdot-carma.atlassian.net/browse/CDAR-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use detections' covariance matrices in multiple object tracking

- carma_cooperative_perception/src/msg_conversion.cpp
- carma_cooperative_perception/test/test_msg_conversion.cpp
This PR resolves a bug when converting external object data to detection data in the cooperative perception stack. The external object to detection conversion function was using velocity_inst instead of velocity. The former has twist values but not the corresponding covariance matrixes.
Closes #2218 
Closes [CDAR-608](https://usdot-carma.atlassian.net/browse/CDAR-608)
The missing covariance matrices was causing issues for downstream cooperative perception stack components.
[CDAR-608]: https://usdot-carma.atlassian.net/browse/CDAR-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Switch twist source for Detections

- carma_cooperative_perception/src/msg_conversion.cpp
- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR adds semantic class information to the CP stack. Downstream CARMA components, such as the motion computation node, relies on this information to choose the appropriate propagation model. Previously, the semantic class information was being droppped.
Closes #2232 
Closes [CDAR-621](https://usdot-carma.atlassian.net/browse/CDAR-621)
[CDAR-621]: https://usdot-carma.atlassian.net/browse/CDAR-621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Add semantic class to message generation

- carma_cooperative_perception/src/track_list_to_external_object_list_component.cpp
The `TrackListToExternalObjectListNode` was not setting the `frame_id` for the message, which caused visualization issues for downstream packages.
Closes #2214 
Closes [CDAR-597](https://usdot-carma.atlassian.net/browse/CDAR-597)
Needed for visualizing external objects in rviz/foxglove studio
Manually in integration tests
[CDAR-597]: https://usdot-carma.atlassian.net/browse/CDAR-597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Add "map" to external object list frame ID

- light_controlled_intersection_tactical_plugin/src/light_controlled_intersection_tactical_plugin.cpp
Previously, LCI tactical plugin would remove outdated trajectory points based on time. 
Although most tactical plugins regenerate trajectories every 0.1 seconds, this plugin is designed to keep the last trajectory if it is still "valid" according to its purpose. Initial reason why it was designed that way is because the algorithm to generate this trajectory can be noisy and may introduce undesirable deviations. So this makes the trajectory generation more stable.
Since the plugin cannot be using old trajectory forever, so the intention was to chop the "outdated" trajectory points and if it runs out of available points, the plugin would be forced to generate a new one. 
However, the plugin previously determined the outdated trajectory by looking at its time, which is changed to distance …
> LCI Tactical plugin cuts trajectory based on distamce not on time

- arbitrator/include/capabilities_interface.hpp
- arbitrator/include/capabilities_interface.tpp
- arbitrator/src/tree_planner.cpp
This PR caches the strategic_plugin clients previously created instead of recreating it every 1hz as before.
This PR adds a guard for when none of the strategic plugins return any valid maneuvers (due to ROS failing the service calls or somehow the node froze or shut down), arbitrator should shut down with error. Currently there is no guard for empty responses, which I am guessing is the potential segfault place. Tested it by running platform and forcing shut down the only available strategic plugin and got the following error:
> [environment_perception_controller-8] 1703074934.381615035 | INFO | on_system_alert:59 | Received SystemAlert message of type: 6 with message: SHUTDOWN /guidance subsytem has failed with error: Uncaught Exception from node: arbitrator exception: None of the …
> Arbitrator should retry the failed service calls

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR fixes a parameter update issue for changing parameters through launch files. Relocate parameter declarations to after the on_set_parameters callback declaration. This is needed because declaring parameters will trigger the callback, which needs to be set in order for the parameter changes to take effect.
Closes #2243 
Closes [CDAR-630](https://usdot-carma.atlassian.net/browse/CDAR-630)
Manually through integration testing.
[CDAR-630]: https://usdot-carma.atlassian.net/browse/CDAR-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Relocate MultipleObjectTrackerNode params

- carma_cooperative_perception/src/host_vehicle_filter_component.cpp
This PR moves the filter distance parameter declaration for the host vehicle filter component to be after the `on_set_parameter` callback declaration. The parameter declaration should come after the on_set_parameters callback because declaring a new parameter will call the registered callback. This is what allows us to modify the distance threshold.
Closes #2236 
Closes [CDAR-625](https://usdot-carma.atlassian.net/browse/CDAR-625)
This was preventing the distance threshold from being updated in launch files.
Manually in integration tests.
[CDAR-625]: https://usdot-carma.atlassian.net/browse/CDAR-625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative percepion] Reorder parameter declaration for host vehicle filter

- carma_cooperative_perception/src/external_object_list_to_detection_list_component.cpp
This PR adds improved logging for PROJ transform failures. When PROJ fails to create a transformation, it throws an error. The error string we were using did not include information about the target frame.
Closes #2206 
Closes [CDAR-547](https://usdot-carma.atlassian.net/browse/CDAR-547)
Quality of life/debugging enhancement.
Manually 
[CDAR-547]: https://usdot-carma.atlassian.net/browse/CDAR-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Add improved error logging for PROJ

- carma_cooperative_perception/src/msg_conversion.cpp
This PR fixes the twist frame mismatch between the CP stack's outputted tracks and the rest of CARMA's conventions. The track to external object conversion function now also converts twist frames.
Closes #2238 
Closes [CDAR-626](https://usdot-carma.atlassian.net/browse/CDAR-626)
The frame mismatch was causing issues for downstream components.
[CDAR-626]: https://usdot-carma.atlassian.net/browse/CDAR-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Convert body frame velocities to map frame

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR resolves the issue were post-fusion track updates did not propagate. The new implementation uses the track manager's update functionality (the `update_track` function).
Closes #2213 
Closes [CDAR-595](https://usdot-carma.atlassian.net/browse/CDAR-595)
Bug fix
[CDAR-595]: https://usdot-carma.atlassian.net/browse/CDAR-595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Refactor track update calls after fusion

- carma_cooperative_perception/include/carma_cooperative_perception/external_object_list_to_detection_list_component.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/external_object_list_to_sdsm_component.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/geodetic.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/host_vehicle_filter_component.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/j2735_types.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/j3224_types.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/month.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/msg_conversion.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/multiple_object_tracker_component.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/sdsm_to_detection_list_component.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/track_list_to_external_object_list_component.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/units_extensions.hpp
- carma_cooperative_perception/src/external_object_list_to_detection_list_component.cpp
- carma_cooperative_perception/src/external_object_list_to_detection_list_node.cpp
- carma_cooperative_perception/src/external_object_list_to_sdsm_component.cpp
- carma_cooperative_perception/src/external_object_list_to_sdsm_node.cpp
- carma_cooperative_perception/src/host_vehicle_filter_component.cpp
- carma_cooperative_perception/src/host_vehicle_filter_node.cpp
- carma_cooperative_perception/src/j2735_types.cpp
- carma_cooperative_perception/src/j3224_types.cpp
- carma_cooperative_perception/src/msg_conversion.cpp
- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
- carma_cooperative_perception/src/multiple_object_tracker_node.cpp
- carma_cooperative_perception/src/track_list_to_external_object_list_component.cpp
- carma_cooperative_perception/src/track_list_to_external_object_list_node.cpp
This PR removes all `noexcept` function declaration specifiers from the `carma_cooperative_perception` package. The specifiers were added too liberally without checking to see if they were appropriate for that function. While we could selectively remove inappropriate `noexcept` specifiers, the effort involved in properly checking doesn't seem worth it. We're unsure of the tangible benefits for our use case. It also makes troubleshooting significantly more difficult due to the `std::terminate` requirement.
Closes #2255 
Closes [CDAR-658](https://usdot-carma.atlassian.net/browse/CDAR-658)
See above
[CDAR-658]: https://usdot-carma.atlassian.net/browse/CDAR-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Remove all noexcept specifiers from function declarations

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR fixes a timestamp generation error when making Track messages. The denominator for the modulo operation was too large, causing incorrect nanosecond timestamp values. The denominator should have been 1.0 instead of 10.0.
Closes #2257 
Closes [CDAR-694](https://usdot-carma.atlassian.net/browse/CDAR-694)
Bug fix
[CDAR-694]: https://usdot-carma.atlassian.net/browse/CDAR-694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Fix modulo error

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR replaces the timer type for the `MultipleObjectTrackerComponent`. The timer was a wall timer, which is tied to system time. The new general timer can switch between system and simulation time.
Closes #2260 
Closes [CDAR-699](https://usdot-carma.atlassian.net/browse/CDAR-699)
Improves the node's ability to integrate with simualation.
[CDAR-699]: https://usdot-carma.atlassian.net/browse/CDAR-699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Change multiple object tracker timer

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
The SemanticDistance2dScore combines the 2D Euclidean distance with the semantic classes between detections and tracks. The MetricSe2 is the SE(2) distance.
Closes #2264
Closes [CDAR-705](https://usdot-carma.atlassian.net/browse/CDAR-705)
Improved performance
Manually in integration tests.
[CDAR-705]: https://usdot-carma.atlassian.net/browse/CDAR-705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Add new scoring metrics

- .circleci/config.yml
- docker/checkout.bash
- docker/install.sh
The multiple object tracking library no longer installs its own dependencies, so we must install them manually. The `docker/install.sh` script now calls the library's `install_dependencies.sh` script.
Closes #2267 
Closes [CDAR-712](https://usdot-carma.atlassian.net/browse/CDAR-712)
Resolve Docker build failure
[CDAR-712]: https://usdot-carma.atlassian.net/browse/CDAR-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Install multiple object tracking deps

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR adds a step to our tracking pipeline to drop any unassociated detections that are "close" enough to an existing track. Multiple actors publish detection lists that overlap with others. Our association algorithm currently supports only one-to-one associations, so some detections will go unassociated even though they represent an existing track. To reduce the number of duplicate tracks, we drop any unassociated detection that we deem close enough.
Closes #2266 
Closes [CDAR-711](https://usdot-carma.atlassian.net/browse/CDAR-711)
Performance improvement
[CDAR-711]: https://usdot-carma.atlassian.net/browse/CDAR-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Drop unassociated duplicate detections

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR removes code that is not being used and can be safely removed.
Closes #2271
Closes [CDAR-715](https://usdot-carma.atlassian.net/browse/CDAR-715)
Code cleanup
N/A
[CDAR-715]: https://usdot-carma.atlassian.net/browse/CDAR-715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove dead code

- carma_cooperative_perception/config/cp_multiple_object_tracker_node.yaml
This PR increases the cooperative perception stacks' multiple object tracker execution frequency. It was 5 Hz, now it's 20 Hz. More frequent executions results in smoother estimate updates.
Closes #2270
Closes [CDAR-714](https://usdot-carma.atlassian.net/browse/CDAR-714)
[CDAR-714]: https://usdot-carma.atlassian.net/browse/CDAR-714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Increase CP tracker execution frequency

- carma_cooperative_perception/docs/sdsm_to_detection_list_node.md
- carma_cooperative_perception/include/carma_cooperative_perception/sdsm_to_detection_list_component.hpp
- carma_cooperative_perception/package.xml
This PR adds a georeference subscription to the SDSM conversion node. As part of a bigger-picture refactoring, we want the SDSM objects' coordinates to get projected into CARMA's map frame. Currently, they are projected into CARMA's current UTM zone frame.
Closes #2281 
Progresses [CDAR-728](https://usdot-carma.atlassian.net/browse/CDAR-728)
[CDAR-728]: https://usdot-carma.atlassian.net/browse/CDAR-728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add georeference subscription

- carma_cooperative_perception/include/carma_cooperative_perception/geodetic.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/msg_conversion.hpp
- carma_cooperative_perception/include/carma_cooperative_perception/sdsm_to_detection_list_component.hpp
- carma_cooperative_perception/src/geodetic.cpp
- carma_cooperative_perception/src/msg_conversion.cpp
- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
- carma_cooperative_perception/test/test_msg_conversion.cpp
This PR updates the SDSM conversion node to project coordinates to CARMA's map frame instead of CARMA's current UTM zone's frame. We were originally using the UTM zone frame, but none of CARMA's components use this approach, they all use the georeference origin provided by the currently-loaded map.
Closes #2283 
Progresses [CDAR-538](https://usdot-carma.atlassian.net/browse/CDAR-538)
Integration testing
[CDAR-538]: https://usdot-carma.atlassian.net/browse/CDAR-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update SDSM to detection conversion

- carma_cooperative_perception/src/msg_conversion.cpp
- carma_cooperative_perception/test/test_msg_conversion.cpp
This PR changes the way detection IDs are generated from incoming SDSMs. Previously, the detection IDs were simply the object IDs from the SDSM's contained objects. Now the detection IDs will have the SDSM's originator source ID prepended to it. This will detection IDs unique across all detections.
Closes #2286
Progresses [CDAR-538](https://usdot-carma.atlassian.net/browse/CDAR-538)
Unit tests
[CDAR-538]: https://usdot-carma.atlassian.net/browse/CDAR-538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prepend BSM ID to detections

- yield_plugin/config/parameters.yaml
- yield_plugin/include/yield_plugin/yield_config.hpp
- yield_plugin/include/yield_plugin/yield_plugin.hpp
- yield_plugin/src/yield_plugin.cpp
- yield_plugin/src/yield_plugin_node.cpp
- yield_plugin/test/test_cooperative_yield.cpp
- yield_plugin/test/test_yield.cpp
This PR is first of the two PR needed to get yield_plugin to a state where TRB videos were recorded.
On a high level, this only includes refactor changes and some guards against bad values such as nan and no large algorithmic changes. Specifically:
- Refactor: `update_traj_for_object` (which is the main function that updates trajectory to yield for detected object) was too large. So divided its portion out to a function called `get_earliest_collision_object_and_time` which handles large portion of collision detection. 
- Parameter changes: Renamed many parameters for clarification. Deleted parameters that should be set from carma-config (vehicle_length, vehicle_height and vehicle_width). And some more tuning of the default parameters. 
- max_trajectory_speed: This function gets the max …
> Refactor yield_plugin and assorted fixes

- carma_cooperative_perception/include/carma_cooperative_perception/sdsm_to_detection_list_component.hpp
- carma_cooperative_perception/src/msg_conversion.cpp
This SDSM to detected object list conversion did not generate the covariance matrix values from confidence intervals, making the resulting detection list pretty much useless.
Closes [CDAR-729](https://usdot-carma.atlassian.net/browse/CDAR-729)
SDSM to detection list conversion is necessary to receive detected object information from nearby actors.
[CDAR-729]: https://usdot-carma.atlassian.net/browse/CDAR-729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Add covariance calculations to SDSM conversions

- carma_cooperative_perception/CMakeLists.txt
- carma_cooperative_perception/include/carma_cooperative_perception/detection_list_viz_component.hpp
- carma_cooperative_perception/package.xml
- carma_cooperative_perception/src/detection_list_viz_component.cpp
- carma_cooperative_perception/src/detection_list_viz_node.cpp
This PR adds a new node to convert `DetectionList.msg` messages to `MarkerArray.msg` messages that can be used in RViz or Foxglove Studio to visualize detections. This will help with troubleshooting cooperative perception pipeline issues.
Closes [CDAR-758](https://usdot-carma.atlassian.net/browse/CDAR-758)
Helps with troubleshooting cooperative perception stack issues.
[CDAR-758]: https://usdot-carma.atlassian.net/browse/CDAR-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add DetectionList message visualization

- carma/launch/environment.launch.py
This PR adds a topic remap for the SDSM to detection list node in the environment launch file.
Closes [CDAR-766](https://usdot-carma.atlassian.net/browse/CDAR-766)
The missing remap was preventing the node from receiving georeference updates.
[CDAR-766]: https://usdot-carma.atlassian.net/browse/CDAR-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cdar 766 georeference remap

- .github/workflows/github_pages.yml
- docs/requirements.txt
- mkdocs.yaml
This PR adds a skeleton template for Platform documentation. The proposed documentation generation system uses Material for MkDocs.
[CAR-6005](https://usdot-carma.atlassian.net/browse/CAR-6005)
Our current documentation needs to be overhauled and migrated away from Confluence. This is the first step in that process for Platform.
[CAR-6005]: https://usdot-carma.atlassian.net/browse/CAR-6005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add skeleton documentation for Platform

- carma_cooperative_perception/src/detection_list_viz_component.cpp
This PR fixes a bug with the detection visualization node. The individual markers were being created, but they never got added to the marker array message to be published. This caused the node to always publish an empty marker array list.
Closes [CDAR-791](https://usdot-carma.atlassian.net/browse/CDAR-791)
[CDAR-791]: https://usdot-carma.atlassian.net/browse/CDAR-791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Populate DetectionVizNode's marker array with markers.

- carma_cooperative_perception/include/carma_cooperative_perception/multiple_object_tracker_component.hpp
- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR changes how UUIDs are generated for tracks. Previously, the multiple object tracking node would reuse the UUID from a detection when converting it to a track. This made the track identifiers misleading because tracks' states are fused from several sources, not only detections with the same identifier. It also caused issues downstream when converting the UUID to an integer due to data size limits.
The node now maintains a monotonically increasing count of lifetime-generated tracks. It uses this number when creating new tracks.
Closes [CDAR-792](https://usdot-carma.atlassian.net/browse/CDAR-792)
[CDAR-792]: https://usdot-carma.atlassian.net/browse/CDAR-792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Change UUID when creating tracks

- carma_cooperative_perception/src/multiple_object_tracker_component.cpp
This PR tightens the pruning distance threshold. Any scores (detection--track distance) that are more than 1 meter from a track will be pruned. This makes it easier on the association step since there are fewer possibilities to consider.
> [cooperative perception] Tighten pruning distance

- yield_plugin/src/yield_plugin.cpp
This is a PR to fix an issue where yield plugin can get stuck in an infinite loop in JMT_trajectory_calculation. 
The stopping condition for the loop is to accumulate downtrack in each iteration and break if reached goal downtrack. However, sometimes the equation could lead to negative speeds just before goal downtrack which could turn the accumulation back to 0 and negative infinity. The loop should stop if the speed reached negative because it indicates that the vehicle stopped. 
One earlier available log for a problematic behavior where platform yields to pedestrian but never continues shows this could be the root cause. The log showed that after certain time, all of the calls to yield_plugin timed out. However, although this is definitely one of the root cause of this behavior, this …
> Cdar 768 Fix platform does not continue after yielding

- carma_cooperative_perception/src/external_object_list_to_sdsm_component.cpp
This PR fixes a segmentation fault in the `ExternalObjectListToSdsmNode` that was caused by an unchecked pointer dereference for `map_projector_`.
Closes [CDAR-826](https://usdot-carma.atlassian.net/browse/CDAR-826)
[CDAR-826]: https://usdot-carma.atlassian.net/browse/CDAR-826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [cooperative perception] Fix segmentation fault when there is no georeference

- carma_cooperative_perception/src/msg_conversion.cpp
Encoder is not able to encode SDSM due to missing fields.
It publishes now.
N/A
https://usdot-carma.atlassian.net/browse/CDAR-831
vru verification prep
sim pc 1
> fix sdsm not publishing

- carma_cooperative_perception/include/carma_cooperative_perception/j2735_types.hpp
- carma_cooperative_perception/src/msg_conversion.cpp
- carma_cooperative_perception/test/test_msg_conversion.cpp
The `to_time_msg()` function in the `carma_cooperative_perception` package did not use the DDateTime minute and hour fields when converting `DDateTime` objects to their ROS message equivalents. This causes issues in the CP stack because the incoming detected objects will have their time stamps essentially roll back over to less than 1 minute.
It was not noticeable in previous tests because all of the simulations ran for less than a minute. Now, we are running simulations longer than a minute.
Closes [CDAR-863](https://usdot-carma.atlassian.net/browse/CDAR-863)
Bug fix
Unit tests
[CDAR-863]: https://usdot-carma.atlassian.net/browse/CDAR-863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix DDateTime to ROS message conversion for longer durations

- yield_plugin/src/yield_plugin.cpp
This PR allows more time for comfortable deceleration. Previously it was capped by the original trajectory's planning duration, which is wrong because if an obstacle is detected, the vehicle might take longer time to come to a stop. 
Partially fixes https://github.com/usdot-fhwa-stol/carma-platform/issues/2345
https://usdot-carma.atlassian.net/browse/CDAR-882
VRU verification test data analysis
Sim PC1
> Cdar 882 Give enough duration for comfortable decel in yield_plugin

- motion_computation/config/parameters.yaml
Since live vehicles don't have reliable object sensor enabled, we should turn off the motion prediction by default.
https://usdot-carma.atlassian.net/browse/CDAR-883
> turn-off-motion-computation-by-default

- carma/launch/carma_src.launch.py
- carma/launch/guidance.launch.py
- carma_wm/include/carma_wm/CARMAWorldModel.hpp
- carma_wm/src/CARMAWorldModel.cpp
- carma_wm/src/WMListener.cpp
- carma_wm/src/WMListenerWorker.cpp
- carma_wm/src/WMListenerWorker.hpp
This PR adds logic to the carma_wm to be able to process SPaT information which is based on a wall clock when running platform along with carla in simulation.
Required for VOICES where the setup doesn't involve a simulation manager like mosaic and doesn't have the traffic controller time synced with the rest of the simulation.
A offset is calculated between wall time and sim time and the spat phase timings are updated to account for this difference while processing.
https://usdot-carma.atlassian.net/browse/VOI-384
> add spat wall time process

- motion_computation/.clang-format
- motion_computation/CPPLINT.cfg
- motion_computation/include/motion_computation/impl/mobility_path_to_external_object_helpers.hpp
- motion_computation/include/motion_computation/impl/psm_to_external_object_helpers.hpp
- motion_computation/include/motion_computation/message_conversions.hpp
- motion_computation/include/motion_computation/motion_computation_config.hpp
- motion_computation/include/motion_computation/motion_computation_node.hpp
- motion_computation/include/motion_computation/motion_computation_worker.hpp
- motion_computation/src/bsm_to_external_object_convertor.cpp
- motion_computation/src/main.cpp
- motion_computation/src/mobility_path_to_external_object.cpp
- motion_computation/src/motion_computation_node.cpp
- motion_computation/src/motion_computation_worker.cpp
- motion_computation/src/psm_to_external_object_convertor.cpp
- motion_computation/test/MotionComputationTest.cpp
- motion_computation/test/TestMain.cpp
Fixing motion_computation cpplint errors introduced in here:
https://github.com/usdot-fhwa-stol/carma-platform/pull/2399
with the failing github action:
https://github.com/usdot-fhwa-stol/carma-platform/actions/runs/9449278789/job/26037602316?pr=2397#step:13:23837
My environment was never configured for clang format and only used to delete whitespaces. I improved it by:
1. I have installed clang by `sudo apt install clang`
2. installed cpplint by `sudo pip install cpplint`
3. I have then installed vscode extensions that use packages Clang-Format and cpplint
4. created a .clang-format file outside the src folder that has all the repos and started editing to get the format. If there is multiple, I believe the immediate .clang-format file in the project gets to be used first.
5. added …
> Fix cpplint test in motion_computation to support CI/CD

- bsm_generator/include/bsm_generator/bsm_generator_node.hpp
- bsm_generator/src/bsm_generator_node.cpp
This PR attempts to fix valid lat/lon generation failure in BSM generator which leads to BSM encoding failure. 
Tested on Black Pacifica and I didn't see any BSM errors for 5+ runs where I was seeing almost every run.
https://github.com/usdot-fhwa-stol/carma-platform/issues/2402
https://usdot-carma.atlassian.net/browse/CAR-6059
Seen it simulation as well as live vehicle.
Distributed Testing (VOICES) relies on vehicle's valid BSM, so encountered this issue.
Tested on Black Pacifica and I didn't see any BSM errors for 5+ runs where I was seeing almost every run.
> Add guard for georeference in BSM generator

- bsm_generator/include/bsm_generator/bsm_generator_node.hpp
- bsm_generator/src/bsm_generator_node.cpp
- carma_cooperative_perception/src/external_object_list_to_sdsm_component.cpp
- carma_wm/src/SignalizedIntersectionManager.cpp
- cooperative_lanechange/include/cooperative_lanechange/cooperative_lanechange_node.hpp
- cooperative_lanechange/src/cooperative_lanechange_node.cpp
- gnss_to_map_convertor/include/gnss_to_map_convertor/GNSSToMapConvertor.hpp
- gnss_to_map_convertor/src/GNSSToMapConvertor.cpp
- mobilitypath_publisher/include/mobilitypath_publisher/mobilitypath_publisher.hpp
- mobilitypath_publisher/src/mobilitypath_publisher.cpp
- mobilitypath_visualizer/include/mobilitypath_visualizer/mobilitypath_visualizer.hpp
- mobilitypath_visualizer/src/mobilitypath_visualizer.cpp
- motion_computation/include/motion_computation/motion_computation_worker.hpp
- motion_computation/src/motion_computation_worker.cpp
- platooning_strategic_IHP/include/platoon_strategic_ihp/platoon_strategic_ihp.h
- platooning_strategic_IHP/src/platoon_strategic_ihp.cpp
- port_drayage_plugin/include/port_drayage_plugin/port_drayage_worker.hpp
- port_drayage_plugin/src/port_drayage_worker.cpp
- traffic_incident_parser/include/traffic_incident_parser/traffic_incident_parser_worker.hpp
- traffic_incident_parser/src/traffic_incident_parser_worker.cpp
- yield_plugin/include/yield_plugin/yield_plugin.hpp
- yield_plugin/src/yield_plugin.cpp
This PR supports https://github.com/usdot-fhwa-stol/carma-platform/pull/2403
It fixes all instances of georeference processing callbacks as they might run into same issue.
I separated the 2 PRs just to make it digestable
https://github.com/usdot-fhwa-stol/carma-platform/issues/2402
https://usdot-carma.atlassian.net/browse/CAR-6059
Seen it simulation as well as live vehicle.
Distributed Testing (VOICES) relies on vehicle's valid BSM, so encountered this issue.
Tested on Black Pacifica and I didn't see any BSM errors for 5+ runs where I was seeing almost every run.
> Fix all instances of georeference

- engineering_tools/carma
This PR fixes the carma script to be able to run from any directory without relying on .env file to exist in the same directory. 
Depends on this PR: https://github.com/usdot-fhwa-stol/carma-config/pull/352
**The proposed change on a high level:**
- Bake the `.env` file into the `carma-config` container. Since `.env` file specifies carma version now, it makes sense to include it in the config, which is intended to track carma version.
- Use COMPOSE_ENV_FILES functionality under the hood from docker which allows the user to specify multiple .env files (NOTE: needs docker-compose 2.23.0+ version). `carma` script now modifies that variable as below (highest to lowest precedence):
- 1 user defined shell COMPOSE_ENV_FILES values
- 2 local .env file where `carma` is called
- 3 .env file …
> Add logic to carma script to account for env var in carma-config

- engineering_tools/carma
During verification testing of release/miura it was found that the carma config install <image-name> command fails to download all images if only 1 is not able to be downloaded. It should pull what it can and ignore what failed, which is previous behavior.  
Error introduced in this PR https://github.com/usdot-fhwa-stol/carma-platform/pull/2409
NA
https://usdot-carma.atlassian.net/browse/ARC-140
ARC-140
verification testing of release/miura 
local VM
> Update carma script to pull all images despire failure

- engineering_tools/carma
Issue is described in the jira link. But basically when `carma config install` is called, it created temporary volume of `carma-config-tmp` to read the `.env` file. 
However, currently it is mistakingly reading it from `carma-config` volume, instead of `carma-config-tmp`, which doesnt exist yet (or if existed, it would end up downloading previously set carma-config and not the one specified in install command). This PR fixes it with correct volume.
It was not caught before because I kept resetting or installing same images to verify. If different image was tested, I had tested 4.5.0 which doesnt use .env file. 
NA
https://usdot-carma.atlassian.net/browse/ARC-141
Fix for bug introduced in https://github.com/usdot-fhwa-stol/carma-platform/pull/2409
black pacifica and fusion vehicles
> use correct volume in carma script

- engineering_tools/xil-cloud-formation-v0.yaml
Updating docker-compose used in the AWS instance. 
Previous one is outdated due to carma script update.
NA
ARC-133
https://usdot-carma.atlassian.net/browse/ARC-133
Triggered by this change https://github.com/usdot-fhwa-stol/carma-platform/pull/2409
Tested by launching AWS instance and checking version of docker-compose and carma script contents:
> Update docker-compose version of AWS instance

- carma/rviz/carma_default_ros2.rviz
This PR adds rviz2 configuration port of existing carma_default.rviz. 
It also removed unused and outdated topics.
No other installation is needed, since rviz2 is shipped and installed with ros-foxy-desktop and is in carma-base already.
Result: 
NOTE1: Currently all vehicles and simulation PCs are still in ros-noetic on the host machines. So this configuration can only be used inside docker container (which I confirmed acceptable with @JonSmet). Therefore, typical usage will look like:
```
carma exec "source /opt/carma/install_ros2/setup.bash && rviz2 -d /opt/carma/install_ros2/carma/share/carma/rviz/carma_default_ros2.rviz"
```
If the platform_ros2 container is running on a specific ip (e.g. simulation PCs) , `/usr/bin/carma` should be edited to match the ip (e.g. `--network=host` to …
> rviz2 configuration port

- engineering_tools/carma
When `carma exec --gui` is called with a command, it correctly sets up nvidia runtime (such as `carma exec --gui "rviz"`
However, if it is just `carma exec --gui` the script is not setting the nvidia runtime, so `nvidia-smi` for example won't work.
NA
CAR-6061
During porting of rviz to rviz2, I have been using a lot of container with gui enabled. And noticed this inconsistency between two similar calls of same thing.
fusion vehicle pc
> Fix carma exec gui

- carma/launch/localization.launch.py
/tf topic published by ndt_matching node is renamed to avoid data duplication, particularly when in gnss_only localization.
[ARC-200](https://usdot-carma.atlassian.net/browse/ARC-200)
avoid data duplication, particularly when in gnss_only localization.
Integration tested on Blue Lexus.
[ARC-200]: https://usdot-carma.atlassian.net/browse/ARC-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> remap tf published by ndt_matching

- engineering_tools/opt_carma_setup.bash
During creation of CDASim comprehensive tutorial guide, I needed to include a step to setup CARMA. That writeup prompted opportunity to clean up our script that is referenced in our CARMA installation guide here: https://usdot-carma.atlassian.net/wiki/spaces/CRMPLT/pages/488472599/Setup+CARMA+Platform+Runtime
Changes include:
- No longer downloads autoware.ai just to copy its yolo contents. CARMA doesn't use camera at the moment so it is not needed. That repo is almost 400 MB+ so it is not ideal.
- Added support for setting up common static folders needed for CDASim because it is not documented anywhere, and my current write-up and existing installation guide will include them. 
NA
https://usdot-carma.atlassian.net/browse/CXC-94
I am writing CDASim tutorial guide. And its configuration …
> Update setup opt-carma script according to install guide

- carma/config/rosbag2_qos_overrides.yaml
Add additional topics to rosbag2 qos override to define transient_local subscribers for topics that might be published before rosbag recording process in running.
> add additional topics to rosbag2 qos overrides

- carma_record/src/CarmaRecordNode.cpp
We have seen ros1_bridge print error logs like below for a while that has no information about what is failing:
After upgrading ros1_bridge to humble, it gave me a log statement where the error is coming from:
And I confirmed that this node exits right after getting the parameters as designed:
However, this makes the ros1_bridge continuously check for the get_logger set_log_level services and fail, which is confusing many end-users as if something is wrong. 
Therefore, since can't suppress the error message from ros1_bridge, I am suggesting to just keep the node alive since it doesn't impose any big resource.
NA
ARC-156
During upgrade of ROS1_bridge to humble, it gave me more descriptive issue of what was happening
Ran CDASim use case with this new spin and no errors log anymore
> Suppress confusing error logs in carma_record

- engineering_tools/carma
For CDASim, carma exec doesn't work because network configuration is hardcoded to host, but cdasim uses different IPs. I could use `docker exec` but this won't last in between test and have to do the sourcing exporting again, which is not user-friendly. This will be useful only for Sim PCs as vehicles don't need it right away. And it can be updated whenever the script is updated next. 
This PR lets the user specify network to connect to. Usage:
`carma exec -n network_name` 
NA
NA
This happens a lot when I try to test something in CDASim, I need to change the network myself in the /usr/bin/carma script. 
CDASIM
> carma exec to accept network

- basic_autonomy/src/basic_autonomy.cpp
- basic_autonomy/test/test_waypoint_generation.cpp
Fixes an issue in basic_autonomy which causes yield plans to not be checked correctly.
Also fixes unit tests failing because of this invalid check. 
https://usdot-carma.atlassian.net/browse/CAR-6009
> Fix basic_autonomy unit test

- engineering_tools/monitor-ros-cpu.py
This PR supports efforts to create analysis scripts for control performance of CARMA. By running this before the carma starts, we are able to log the processes and see which one is taking more resources over time.
Example graph can be, which is not finalized and will be in the carma-analytics-fotda-repo.
Design document for this task is here: https://leidoscorpus.sharepoint.us/:w:/r/sites/STR/TODevelopmentLibrary/22-256%20CDA%20Design%20%26%20Architecture/Work-In-Progress/Task%207%20Architecture%20Improvement%20Implementation/CARMA%20Platform%20Controls%20Improvements/Identified%20Core%20Performance%20Metrics%20And%20Analysis%20Design%20for%20CARMA%20Platform%20Control.docx?d=w40615c2fbfb74d439215cf62c5e5c4ca&csf=1&web=1&e=NXYkMT
Before this, I tried looking to other methods, but this …
> CPU and Memory usage monitoring script for ROS

- lci_strategic_plugin/include/lci_strategic_plugin/lci_strategic_plugin.hpp
- lci_strategic_plugin/src/lci_strategic_plugin.cpp
- lci_strategic_plugin/src/lci_strategic_plugin_algo.cpp
This PR adds Permissive movements to the lci strategic plugin planning logic. It extends the functionality for protected movements to permissive movements as well.
During voices integration testing it was found that SPAT messages published by the virtual econolite controller were being published with the permissive movement type.
> add permissive movement to allowed

- engineering_tools/monitor-ros-cpu.py
Accidentally deleted the readme from the file.
Including it
> Add docs to monitor-ros-cpu.py

- Dockerfile
- carma-platform.repos
- docker/checkout.bash
- docker/install.sh
Update carma-platform to use new v2x conversion repository
related PR: https://github.com/usdot-fhwa-stol/v2x-ros-conversion/pull/10
https://usdot-carma.atlassian.net/browse/ARPA-10
Following the creation of a new repository to handle message conversion to and from binary messages to standard unit messages, this story will update the implementation in carma-platform to remove the cpp_message and j2735_convertor nodes and use the functionality from the new repo.
local integration test
> Update carma-platform to use new v2x conversion repository

- .github/workflows/Ci.yml
- docker/install.sh
This PR adds stol-j2735 to the install dependencies for carma platform following the update of cpp_message in https://github.com/usdot-fhwa-stol/v2x-ros-conversion/pull/8 to use that package in place of the locally built lib-asn1c compiler.
> Install stol j2735 dependency for cpp_message

- carma/launch/ros2_rosbag.launch.py
When we switched to Humble, rosbag2 started not recording anymore. 
`rosbag2 record -a -s mcap` works fine which means the issue is the regex. 
Previous regex had trailing `|` in the end, which is causing the issue:
```
(.*)/received_messages|(.*)/sent_messages|(.*)/scan|/detection/lidar_detector/objects|/detection/lidar_detector/objects_markers|/hardware_interface/lidar/points_raw|/hardware_interface/camera/projection_matrix/detection/lidar_detector/cloud_clusters|/environment/range_vision_fusion_01/detection/lidar_detector/objects|/environment/detection/fusion_tools/objects|/environment/detection/fusion_tools/objects_markers|/environment/detection/object_tracker/objects|/environment/detection/object_tracker/objects_markers|/environment/detection/objects|/hardware_interface/camera/camera_ …
```
> Fix rosbag2 with size 0 in humble

- carma/launch/carma_src.launch.py
- carma/launch/environment.launch.py
This PR adds a conditional launch that toggles autoware lidar perception and CP fusion. This is because:
1. Lidar object detection has not been used in at least 3 years and is now shutting down on its own. Since we don't use it, we are postponing the investigation. This shutdown doesn't prevent normal carma operation, but appears as if something broke in the logs as ERROR for someone who is not familiar. Therefore, completely turning it off.
2. SDSM fusion in the CP stack using MOT (multiple object tracking) is not widely used feature. Due to its design (hopefully gets improved in the future), this can actually slow down the object detection for a few iterations due to fusion. It is better to directly rely on the vehicle sensor (again which only exists in simulation). And the user can …
> Conditionally add lidar perception and CP fusion with SDSM

- basic_autonomy/src/basic_autonomy.cpp
During workzone pedestrian yielding field test, I noticed that the platform shuts down when lanechanging for the 2nd time. 
The issue says invalid yield trajectory, however, the pedestrian was long gone and we had successfully yielded. 
So I think we can turn off the `throw` that is forcing it to shut down in the meanwhile until we figure out the issue.
NA
CAR-6118
Pedestrian yielding demonstration during workzone in the field
Black Pacifica field test with dummy pedestrian
> Remove throw in yielding functionality

- object_visualizer/src/object_visualizer_node.cpp
We wanted to fixthe orientation of the pedestrian to fit our desired narrative of our demo. New orientation:
VIP demo
> Make pedestrian icon to have a constant orientation

- carma/launch/environment.launch.py
Fixes a syntax issue in the launch description for object visualizer currently causing platform to crash.
> Fix object visualizer launch param syntax

- engineering_tools/vector_map_scripts/xodr_transform.py
This PR includes a python script to transform an existing XODR map to a new georeference and rotate it by a specified angle in degrees.
NA
[CDAD-92](https://usdot-carma.atlassian.net/browse/CDAD-92)
This will be used as part of preparation for the ITSWC. We are currently planning to transform the Suntrax map to align with the demo location.
Confirmed that the resulting map loads into CARMA cloud and is transformed correctly.
Two Suntrax maps are overlayed with a geoReference of 0.0,0.0. One map did not have a rotation applied, the other had a rotation of 45 degrees applied.
[CDAD-92]: https://usdot-carma.atlassian.net/browse/CDAD-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CDAD 92 XODR Map Transformation

- carma/launch/message.launch.py
- carma_cloud_client/include/carma_cloud_client/carma_cloud_client_config.hpp
- carma_cloud_client/launch/carma_cloud_client_launch.py
- carma_cloud_client/launch/scripts/call.sh
- carma_cloud_client/launch/scripts/open_tunnels.sh
- carma_cloud_client/src/carma_cloud_client_node.cpp
This PR includes fixes for the cellular connection between CARMA Platform and CARMA Cloud, which can be used to support the cellular communication of TrafficControlRequest and TrafficControlMessage messages (rather than using C-V2X communications with V2X Hub) for geofence-related (e.g., work zone) use cases.
Notable updates include:
- Fixing the remote port (referred to as the webport in some locations) by changing it to `22222`, which is expected by CARMA Cloud.
- Updating the targeted carma-cloud instance and the associated .pem key file to the production instance (carma-cloud.com with key file carma-cloud-1.pem) since this is targeted for the Stingray release.
- Making comments more verbose in some locations to support future testing/troubleshooting.
It will be beneficial to do …
> Fix cellular connection between CARMA Platform and CARMA Cloud
